In [2]:
# !pip install U langchain-huggingface lightfm langchain sentence-transformers faiss-cpu langchain_community datasets chromadb ragas

In [1]:
import os
import sys
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
# from difflib import SequenceMatcher
from datasets import load_dataset
from tqdm import tqdm 
sys.path.append('../../')
from utils.memory_utils import reduce_mem_usage, process_in_chunks, save_in_chunks

user_data = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_CDs_and_Vinyl", split="full", trust_remote_code=True)
meta = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_CDs_and_Vinyl", split="full", trust_remote_code=True)

def flatten_lst(col):
    # flatten lists by joining their elements with a separator (e.g., ', ')
    col['features'] = ', '.join(col['features']) if isinstance(col['features'], list) else col['features']
    col['description'] = ', '.join(col['description']) if isinstance(col['description'], list) else col['description']
    col['categories'] = ', '.join(col['categories']) if isinstance(col['categories'], list) else col['categories']

    return col

flattened_meta = meta.map(flatten_lst)

user_df = process_in_chunks(user_data.to_pandas(), chunk_size=10000)
meta_df = process_in_chunks(flattened_meta.to_pandas(), chunk_size=10000)
# user_df = user_data.to_pandas().fillna(0)
# meta_df = flattened_meta.to_pandas().fillna(0)

Processed 0 rows. Current memory usage: 3669.80 MB
Processed 10000 rows. Current memory usage: 3674.52 MB
Processed 20000 rows. Current memory usage: 3679.16 MB
Processed 30000 rows. Current memory usage: 3683.95 MB
Processed 40000 rows. Current memory usage: 3688.42 MB
Processed 50000 rows. Current memory usage: 3693.31 MB
Processed 60000 rows. Current memory usage: 3662.27 MB
Processed 70000 rows. Current memory usage: 3602.17 MB
Processed 80000 rows. Current memory usage: 3571.69 MB
Processed 90000 rows. Current memory usage: 3578.45 MB
Processed 100000 rows. Current memory usage: 3584.86 MB
Processed 110000 rows. Current memory usage: 3591.45 MB
Processed 120000 rows. Current memory usage: 3588.08 MB
Processed 130000 rows. Current memory usage: 3575.02 MB
Processed 140000 rows. Current memory usage: 3581.03 MB
Processed 150000 rows. Current memory usage: 3586.47 MB
Processed 160000 rows. Current memory usage: 3592.58 MB
Processed 170000 rows. Current memory usage: 3534.95 MB
Processed 180000 rows. Current memory usage: 3525.09 MB
Processed 190000 rows. Current memory usage: 3531.19 MB
Processed 200000 rows. Current memory usage: 3536.75 MB
Processed 210000 rows. Current memory usage: 3542.20 MB
Processed 220000 rows. Current memory usage: 3548.25 MB
Processed 230000 rows. Current memory usage: 3554.08 MB
Processed 240000 rows. Current memory usage: 3560.98 MB
Processed 250000 rows. Current memory usage: 3566.14 MB
Processed 260000 rows. Current memory usage: 3571.23 MB
Processed 270000 rows. Current memory usage: 3576.81 MB
Processed 280000 rows. Current memory usage: 3582.97 MB
Processed 290000 rows. Current memory usage: 3591.95 MB
Processed 300000 rows. Current memory usage: 3601.59 MB
Processed 310000 rows. Current memory usage: 3607.91 MB
Processed 320000 rows. Current memory usage: 3597.78 MB
Processed 330000 rows. Current memory usage: 3603.97 MB
Processed 340000 rows. Current memory usage: 3610.34 MB
Processed 350000 rows. Current memory usage: 3616.77 MB
Processed 360000 rows. Current memory usage: 3623.61 MB
Processed 370000 rows. Current memory usage: 3632.77 MB
Processed 380000 rows. Current memory usage: 3641.12 MB
Processed 390000 rows. Current memory usage: 3620.31 MB
Processed 400000 rows. Current memory usage: 3626.33 MB
Processed 410000 rows. Current memory usage: 3631.81 MB
Processed 420000 rows. Current memory usage: 3638.98 MB
Processed 430000 rows. Current memory usage: 3647.41 MB
Processed 440000 rows. Current memory usage: 3652.95 MB
Processed 450000 rows. Current memory usage: 3639.83 MB
Processed 460000 rows. Current memory usage: 3645.27 MB
Processed 470000 rows. Current memory usage: 3651.72 MB
Processed 480000 rows. Current memory usage: 3657.56 MB
Processed 490000 rows. Current memory usage: 3663.38 MB
Processed 500000 rows. Current memory usage: 3654.75 MB
Processed 510000 rows. Current memory usage: 3661.41 MB
Processed 520000 rows. Current memory usage: 3667.89 MB
Processed 530000 rows. Current memory usage: 3672.89 MB
Processed 540000 rows. Current memory usage: 3678.88 MB
Processed 550000 rows. Current memory usage: 3684.48 MB
Processed 560000 rows. Current memory usage: 3690.38 MB
Processed 570000 rows. Current memory usage: 3697.38 MB
Processed 580000 rows. Current memory usage: 3692.56 MB
Processed 590000 rows. Current memory usage: 3686.12 MB
Processed 600000 rows. Current memory usage: 3691.95 MB
Processed 610000 rows. Current memory usage: 3701.89 MB
Processed 620000 rows. Current memory usage: 3708.12 MB
Processed 630000 rows. Current memory usage: 3714.52 MB
Processed 640000 rows. Current memory usage: 3720.41 MB
Processed 650000 rows. Current memory usage: 3726.20 MB
Processed 660000 rows. Current memory usage: 3731.67 MB
Processed 670000 rows. Current memory usage: 3742.11 MB
Processed 680000 rows. Current memory usage: 3750.05 MB
Processed 690000 rows. Current memory usage: 3666.50 MB
Processed 700000 rows. Current memory usage: 3673.23 MB
Processed 710000 rows. Current memory usage: 3680.67 MB
Processed 720000 rows. Current memory usage: 3687.52 MB
Processed 730000 rows. Current memory usage: 3693.44 MB
Processed 740000 rows. Current memory usage: 3702.05 MB
Processed 750000 rows. Current memory usage: 3709.28 MB
Processed 760000 rows. Current memory usage: 3715.59 MB
Processed 770000 rows. Current memory usage: 3726.81 MB
Processed 780000 rows. Current memory usage: 3734.16 MB
Processed 790000 rows. Current memory usage: 3744.53 MB
Processed 800000 rows. Current memory usage: 3754.39 MB
Processed 810000 rows. Current memory usage: 3763.84 MB
Processed 820000 rows. Current memory usage: 3775.03 MB
Processed 830000 rows. Current memory usage: 3786.12 MB
Processed 840000 rows. Current memory usage: 3798.98 MB
Processed 850000 rows. Current memory usage: 3807.28 MB
Processed 860000 rows. Current memory usage: 3817.06 MB
Processed 870000 rows. Current memory usage: 3825.83 MB
Processed 880000 rows. Current memory usage: 3834.75 MB
Processed 890000 rows. Current memory usage: 3841.55 MB
Processed 900000 rows. Current memory usage: 3848.55 MB
Processed 910000 rows. Current memory usage: 3855.97 MB
Processed 920000 rows. Current memory usage: 3862.97 MB
Processed 930000 rows. Current memory usage: 3860.30 MB
Processed 940000 rows. Current memory usage: 3865.98 MB
Processed 950000 rows. Current memory usage: 3871.73 MB
Processed 960000 rows. Current memory usage: 3877.86 MB
Processed 970000 rows. Current memory usage: 3884.42 MB
Processed 980000 rows. Current memory usage: 3890.72 MB
Processed 990000 rows. Current memory usage: 3898.47 MB
Processed 1000000 rows. Current memory usage: 3903.64 MB
Processed 1010000 rows. Current memory usage: 3909.55 MB
Processed 1020000 rows. Current memory usage: 3914.41 MB
Processed 1030000 rows. Current memory usage: 3920.25 MB
Processed 1040000 rows. Current memory usage: 3926.42 MB
Processed 1050000 rows. Current memory usage: 3932.47 MB
Processed 1060000 rows. Current memory usage: 3937.70 MB
Processed 1070000 rows. Current memory usage: 3942.95 MB
Processed 1080000 rows. Current memory usage: 3949.62 MB
Processed 1090000 rows. Current memory usage: 3955.22 MB
Processed 1100000 rows. Current memory usage: 3935.12 MB
Processed 1110000 rows. Current memory usage: 3887.75 MB
Processed 1120000 rows. Current memory usage: 3894.88 MB
Processed 1130000 rows. Current memory usage: 3900.42 MB
Processed 1140000 rows. Current memory usage: 3909.39 MB
Processed 1150000 rows. Current memory usage: 3920.16 MB
Processed 1160000 rows. Current memory usage: 3926.89 MB
Processed 1170000 rows. Current memory usage: 3932.27 MB
Processed 1180000 rows. Current memory usage: 3940.81 MB
Processed 1190000 rows. Current memory usage: 3950.55 MB
Processed 1200000 rows. Current memory usage: 3913.23 MB
Processed 1210000 rows. Current memory usage: 3852.91 MB
Processed 1220000 rows. Current memory usage: 3858.81 MB
Processed 1230000 rows. Current memory usage: 3865.59 MB
Processed 1240000 rows. Current memory usage: 3874.75 MB
Processed 1250000 rows. Current memory usage: 3880.70 MB
Processed 1260000 rows. Current memory usage: 3886.92 MB
Processed 1270000 rows. Current memory usage: 3895.66 MB
Processed 1280000 rows. Current memory usage: 3905.03 MB
Processed 1290000 rows. Current memory usage: 3911.97 MB
Processed 1300000 rows. Current memory usage: 3918.05 MB
Processed 1310000 rows. Current memory usage: 3924.64 MB
Processed 1320000 rows. Current memory usage: 3931.77 MB
Processed 1330000 rows. Current memory usage: 3940.69 MB
Processed 1340000 rows. Current memory usage: 3946.67 MB
Processed 1350000 rows. Current memory usage: 3953.94 MB
Processed 1360000 rows. Current memory usage: 3962.52 MB
Processed 1370000 rows. Current memory usage: 3968.17 MB
Processed 1380000 rows. Current memory usage: 3974.53 MB
Processed 1390000 rows. Current memory usage: 3982.25 MB
Processed 1400000 rows. Current memory usage: 3989.72 MB
Processed 1410000 rows. Current memory usage: 3996.95 MB
Processed 1420000 rows. Current memory usage: 4003.22 MB
Processed 1430000 rows. Current memory usage: 4010.62 MB
Processed 1440000 rows. Current memory usage: 4018.06 MB
Processed 1450000 rows. Current memory usage: 4032.66 MB
Processed 1460000 rows. Current memory usage: 4045.53 MB
Processed 1470000 rows. Current memory usage: 4054.23 MB
Processed 1480000 rows. Current memory usage: 4060.78 MB
Processed 1490000 rows. Current memory usage: 4079.16 MB
Processed 1500000 rows. Current memory usage: 4086.38 MB
Processed 1510000 rows. Current memory usage: 4094.81 MB
Processed 1520000 rows. Current memory usage: 4105.20 MB
Processed 1530000 rows. Current memory usage: 4105.83 MB
Processed 1540000 rows. Current memory usage: 4098.33 MB
Processed 1550000 rows. Current memory usage: 4104.59 MB
Processed 1560000 rows. Current memory usage: 4110.69 MB
Processed 1570000 rows. Current memory usage: 4116.86 MB
Processed 1580000 rows. Current memory usage: 4123.34 MB
Processed 1590000 rows. Current memory usage: 4130.20 MB
Processed 1600000 rows. Current memory usage: 4139.22 MB
Processed 1610000 rows. Current memory usage: 4149.28 MB
Processed 1620000 rows. Current memory usage: 4156.83 MB
Processed 1630000 rows. Current memory usage: 4163.56 MB
Processed 1640000 rows. Current memory usage: 4171.08 MB
Processed 1650000 rows. Current memory usage: 4177.00 MB
Processed 1660000 rows. Current memory usage: 4182.50 MB
Processed 1670000 rows. Current memory usage: 4188.27 MB
Processed 1680000 rows. Current memory usage: 4194.22 MB
Processed 1690000 rows. Current memory usage: 4202.66 MB
Processed 1700000 rows. Current memory usage: 4212.75 MB
Processed 1710000 rows. Current memory usage: 4146.50 MB
Processed 1720000 rows. Current memory usage: 4151.78 MB
Processed 1730000 rows. Current memory usage: 4161.45 MB
Processed 1740000 rows. Current memory usage: 4170.66 MB
Processed 1750000 rows. Current memory usage: 4176.94 MB
Processed 1760000 rows. Current memory usage: 4182.97 MB
Processed 1770000 rows. Current memory usage: 4188.42 MB
Processed 1780000 rows. Current memory usage: 4195.31 MB
Processed 1790000 rows. Current memory usage: 4201.33 MB
Processed 1800000 rows. Current memory usage: 4206.95 MB
Processed 1810000 rows. Current memory usage: 4213.59 MB
Processed 1820000 rows. Current memory usage: 4220.03 MB
Processed 1830000 rows. Current memory usage: 4226.33 MB
Processed 1840000 rows. Current memory usage: 4232.89 MB
Processed 1850000 rows. Current memory usage: 4240.27 MB
Processed 1860000 rows. Current memory usage: 4245.83 MB
Processed 1870000 rows. Current memory usage: 4251.73 MB
Processed 1880000 rows. Current memory usage: 4257.47 MB
Processed 1890000 rows. Current memory usage: 4263.78 MB
Processed 1900000 rows. Current memory usage: 4269.30 MB
Processed 1910000 rows. Current memory usage: 4274.58 MB
Processed 1920000 rows. Current memory usage: 4280.55 MB
Processed 1930000 rows. Current memory usage: 4286.80 MB
Processed 1940000 rows. Current memory usage: 4295.56 MB
Processed 1950000 rows. Current memory usage: 4303.80 MB
Processed 1960000 rows. Current memory usage: 4309.28 MB
Processed 1970000 rows. Current memory usage: 4315.64 MB
Processed 1980000 rows. Current memory usage: 4323.48 MB
Processed 1990000 rows. Current memory usage: 4330.02 MB
Processed 2000000 rows. Current memory usage: 4336.53 MB
Processed 2010000 rows. Current memory usage: 4344.22 MB
Processed 2020000 rows. Current memory usage: 4351.59 MB
Processed 2030000 rows. Current memory usage: 4361.64 MB
Processed 2040000 rows. Current memory usage: 4371.33 MB
Processed 2050000 rows. Current memory usage: 4382.50 MB
Processed 2060000 rows. Current memory usage: 4393.47 MB
Processed 2070000 rows. Current memory usage: 4404.25 MB
Processed 2080000 rows. Current memory usage: 4417.39 MB
Processed 2090000 rows. Current memory usage: 4432.38 MB
Processed 2100000 rows. Current memory usage: 4443.31 MB
Processed 2110000 rows. Current memory usage: 4455.16 MB
Processed 2120000 rows. Current memory usage: 4437.80 MB
Processed 2130000 rows. Current memory usage: 4443.41 MB
Processed 2140000 rows. Current memory usage: 4449.78 MB
Processed 2150000 rows. Current memory usage: 4455.61 MB
Processed 2160000 rows. Current memory usage: 4465.17 MB
Processed 2170000 rows. Current memory usage: 4476.36 MB
Processed 2180000 rows. Current memory usage: 4488.55 MB
Processed 2190000 rows. Current memory usage: 4500.81 MB
Processed 2200000 rows. Current memory usage: 4512.14 MB
Processed 2210000 rows. Current memory usage: 4490.80 MB
Processed 2220000 rows. Current memory usage: 4501.55 MB
Processed 2230000 rows. Current memory usage: 4512.39 MB
Processed 2240000 rows. Current memory usage: 4522.44 MB
Processed 2250000 rows. Current memory usage: 4533.12 MB
Processed 2260000 rows. Current memory usage: 4540.72 MB
Processed 2270000 rows. Current memory usage: 4546.80 MB
Processed 2280000 rows. Current memory usage: 4553.50 MB
Processed 2290000 rows. Current memory usage: 4558.98 MB
Processed 2300000 rows. Current memory usage: 4564.59 MB
Processed 2310000 rows. Current memory usage: 4570.19 MB
Processed 2320000 rows. Current memory usage: 4575.80 MB
Processed 2330000 rows. Current memory usage: 4583.56 MB
Processed 2340000 rows. Current memory usage: 4593.45 MB
Processed 2350000 rows. Current memory usage: 4599.17 MB
Processed 2360000 rows. Current memory usage: 4605.62 MB
Processed 2370000 rows. Current memory usage: 4611.47 MB
Processed 2380000 rows. Current memory usage: 4617.20 MB
Processed 2390000 rows. Current memory usage: 4624.22 MB
Processed 2400000 rows. Current memory usage: 4629.91 MB
Processed 2410000 rows. Current memory usage: 4636.17 MB
Processed 2420000 rows. Current memory usage: 4642.44 MB
Processed 2430000 rows. Current memory usage: 4649.64 MB
Processed 2440000 rows. Current memory usage: 4655.42 MB
Processed 2450000 rows. Current memory usage: 4662.19 MB
Processed 2460000 rows. Current memory usage: 4668.16 MB
Processed 2470000 rows. Current memory usage: 4673.86 MB
Processed 2480000 rows. Current memory usage: 4681.06 MB
Processed 2490000 rows. Current memory usage: 4692.19 MB
Processed 2500000 rows. Current memory usage: 4705.36 MB
Processed 2510000 rows. Current memory usage: 4714.25 MB
Processed 2520000 rows. Current memory usage: 4720.30 MB
Processed 2530000 rows. Current memory usage: 4726.69 MB
Processed 2540000 rows. Current memory usage: 4736.06 MB
Processed 2550000 rows. Current memory usage: 4742.47 MB
Processed 2560000 rows. Current memory usage: 4750.52 MB
Processed 2570000 rows. Current memory usage: 4759.47 MB
Processed 2580000 rows. Current memory usage: 4771.16 MB
Processed 2590000 rows. Current memory usage: 4780.53 MB
Processed 2600000 rows. Current memory usage: 4789.66 MB
Processed 2610000 rows. Current memory usage: 4796.17 MB
Processed 2620000 rows. Current memory usage: 4792.39 MB
Processed 2630000 rows. Current memory usage: 4800.84 MB
Processed 2640000 rows. Current memory usage: 4807.80 MB
Processed 2650000 rows. Current memory usage: 4814.88 MB
Processed 2660000 rows. Current memory usage: 4821.34 MB
Processed 2670000 rows. Current memory usage: 4827.73 MB
Processed 2680000 rows. Current memory usage: 4835.66 MB
Processed 2690000 rows. Current memory usage: 4843.23 MB
Processed 2700000 rows. Current memory usage: 4795.81 MB
Processed 2710000 rows. Current memory usage: 4803.58 MB
Processed 2720000 rows. Current memory usage: 4810.17 MB
Processed 2730000 rows. Current memory usage: 4818.17 MB
Processed 2740000 rows. Current memory usage: 4824.17 MB
Processed 2750000 rows. Current memory usage: 4835.78 MB
Processed 2760000 rows. Current memory usage: 4844.88 MB
Processed 2770000 rows. Current memory usage: 4854.25 MB
Processed 2780000 rows. Current memory usage: 4861.78 MB
Processed 2790000 rows. Current memory usage: 4870.42 MB
Processed 2800000 rows. Current memory usage: 4877.44 MB
Processed 2810000 rows. Current memory usage: 4883.73 MB
Processed 2820000 rows. Current memory usage: 4890.83 MB
Processed 2830000 rows. Current memory usage: 4897.03 MB
Processed 2840000 rows. Current memory usage: 4904.38 MB
Processed 2850000 rows. Current memory usage: 4914.31 MB
Processed 2860000 rows. Current memory usage: 4921.92 MB
Processed 2870000 rows. Current memory usage: 4928.33 MB
Processed 2880000 rows. Current memory usage: 4934.67 MB
Processed 2890000 rows. Current memory usage: 4943.73 MB
Processed 2900000 rows. Current memory usage: 4949.30 MB
Processed 2910000 rows. Current memory usage: 4956.11 MB
Processed 2920000 rows. Current memory usage: 4961.89 MB
Processed 2930000 rows. Current memory usage: 4969.42 MB
Processed 2940000 rows. Current memory usage: 4976.53 MB
Processed 2950000 rows. Current memory usage: 4982.92 MB
Processed 2960000 rows. Current memory usage: 4990.69 MB
Processed 2970000 rows. Current memory usage: 4998.55 MB
Processed 2980000 rows. Current memory usage: 5005.64 MB
Processed 2990000 rows. Current memory usage: 5012.23 MB
Processed 3000000 rows. Current memory usage: 5018.52 MB
Processed 3010000 rows. Current memory usage: 5026.06 MB
Processed 3020000 rows. Current memory usage: 5033.95 MB
Processed 3030000 rows. Current memory usage: 5040.12 MB
Processed 3040000 rows. Current memory usage: 5045.92 MB
Processed 3050000 rows. Current memory usage: 5052.09 MB
Processed 3060000 rows. Current memory usage: 5058.30 MB
Processed 3070000 rows. Current memory usage: 5065.14 MB
Processed 3080000 rows. Current memory usage: 5072.06 MB
Processed 3090000 rows. Current memory usage: 5079.48 MB
Processed 3100000 rows. Current memory usage: 5085.73 MB
Processed 3110000 rows. Current memory usage: 5094.84 MB
Processed 3120000 rows. Current memory usage: 5105.48 MB
Processed 3130000 rows. Current memory usage: 5116.22 MB
Processed 3140000 rows. Current memory usage: 5122.61 MB
Processed 3150000 rows. Current memory usage: 5130.56 MB
Processed 3160000 rows. Current memory usage: 5140.12 MB
Processed 3170000 rows. Current memory usage: 5149.34 MB
Processed 3180000 rows. Current memory usage: 5115.22 MB
Processed 3190000 rows. Current memory usage: 5124.50 MB
Processed 3200000 rows. Current memory usage: 5132.92 MB
Processed 3210000 rows. Current memory usage: 5140.91 MB
Processed 3220000 rows. Current memory usage: 5148.64 MB
Processed 3230000 rows. Current memory usage: 5157.39 MB
Processed 3240000 rows. Current memory usage: 5165.45 MB
Processed 3250000 rows. Current memory usage: 5172.27 MB
Processed 3260000 rows. Current memory usage: 5179.55 MB
Processed 3270000 rows. Current memory usage: 5186.66 MB
Processed 3280000 rows. Current memory usage: 5193.94 MB
Processed 3290000 rows. Current memory usage: 5200.44 MB
Processed 3300000 rows. Current memory usage: 5207.59 MB
Processed 3310000 rows. Current memory usage: 5213.64 MB
Processed 3320000 rows. Current memory usage: 5224.66 MB
Processed 3330000 rows. Current memory usage: 5239.03 MB
Processed 3340000 rows. Current memory usage: 5244.86 MB
Processed 3350000 rows. Current memory usage: 5251.31 MB
Processed 3360000 rows. Current memory usage: 5257.56 MB
Processed 3370000 rows. Current memory usage: 5265.78 MB
Processed 3380000 rows. Current memory usage: 5272.66 MB
Processed 3390000 rows. Current memory usage: 5278.53 MB
Processed 3400000 rows. Current memory usage: 5284.66 MB
Processed 3410000 rows. Current memory usage: 5291.61 MB
Processed 3420000 rows. Current memory usage: 5298.02 MB
Processed 3430000 rows. Current memory usage: 5304.02 MB
Processed 3440000 rows. Current memory usage: 5310.27 MB
Processed 3450000 rows. Current memory usage: 5316.73 MB
Processed 3460000 rows. Current memory usage: 5323.12 MB
Processed 3470000 rows. Current memory usage: 5329.42 MB
Processed 3480000 rows. Current memory usage: 5335.73 MB
Processed 3490000 rows. Current memory usage: 5341.95 MB
Processed 3500000 rows. Current memory usage: 5348.55 MB
Processed 3510000 rows. Current memory usage: 5355.45 MB

In [4]:
user_df.head(5)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,[],B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,0,1
1,5.0,Five Stars,LOVE!!,[],B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,0,1
2,3.0,Three Stars,Sad there is not the versions with the real/or...,[],B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,0,1
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,[],B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,3,1
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,[],B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,0,0

In [5]:
user_df['verified_purchase'] = user_df['verified_purchase'].astype(int)
user_df.head(5)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,[],B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,0,1
1,5.0,Five Stars,LOVE!!,[],B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,0,1
2,3.0,Three Stars,Sad there is not the versions with the real/or...,[],B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,0,1
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,[],B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,3,1
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,[],B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,0,0

In [6]:
user_df['rating'] = user_df['rating'].astype('float32')
user_df.groupby(['rating','verified_purchase']).size().reset_index().pivot(columns='rating', index='verified_purchase', values=0)

rating                1.0    2.0     3.0     4.0      5.0
verified_purchase
0                   81604  63704  117798  288213   996369
1                  106123  76853  165893  376301  2554415

In [7]:
user = user_df.drop(['images'], axis='columns')

In [8]:
user_df2 = user[['rating', 'asin', 'parent_asin', 'user_id', 'timestamp']]
user_df2

,rating,asin,parent_asin,user_id,timestamp
0,5.0,B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000
1,5.0,B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000
2,3.0,B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000
3,3.0,B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000
4,5.0,B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946
...,...,...,...,...,...
4827268,5.0,B000002VPH,B000002VPH,AHM36UEBOF2I6VH7CGAGHCDDUITQ,1308413175000
4827269,5.0,B000084T18,B000084T18,AHM36UEBOF2I6VH7CGAGHCDDUITQ,1308412875000
4827270,5.0,B004OFWLO0,B004OFWLO0,AHRJPHOI5JHYEQVSDMNX6736QH3Q,1505425559120
4827271,1.0,B000GIXIAK,B000GIXIAK,AH4PJ73QN75AJM5VSCT53AOADCGA,1157470110000
4827272,5.0,B0001ADALU,B0001ADALU,AH4PJ73QN75AJM5VSCT53AOADCGA,1077661382000

In [9]:
meta_df.head(5)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Digital Music,Release Some Tension,4.601562,112,,Swv ~ Release Some Tension,12.05,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",SWV Format: Audio CD,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro...",B000002X4C,None,None,None
1,Digital Music,Rio Angie,5.000000,1,,"Shrimp City Slim (aka Gary Erwin, b. 1953, Chi...",14.98,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Shrimp City Slim (Artist) Format: Audio CD,"CDs & Vinyl, Jazz, Avant Garde & Free Jazz","{""Product Dimensions"": ""5.6 x 0.4 x 4.9 inches...",B00902T10Y,None,None,None
2,Digital Music,Lost in Love,5.000000,9,,,24.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Nastyboy Klick Format: Audio CD,"CDs & Vinyl, Rap & Hip-Hop, Gangsta & Hardcore","{""Package Dimensions"": ""4.7 x 4.6 x 0.1 inches...",B00000DALY,None,None,None
3,Digital Music,Somewhere in Time,4.800781,1186,,The 1980 soundtrack to the now classic motion ...,11.55,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}","John Barry (Composer), Barry, John (Comp...","CDs & Vinyl, Soundtracks, Movie Scores","{""Is Discontinued By Manufacturer"": ""No"", ""Lan...",B0000086D1,None,None,None
4,Digital Music,Kimmon Waldruff,5.000000,1,,Solo acoustic fingerstyle guitar.,14.07,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Kimmon Waldruff (Artist) Format: Audio CD,"CDs & Vinyl, Folk","{""Is Discontinued By Manufacturer"": ""No"", ""Pro...",B000S6W7KC,None,None,None

In [10]:
meta_df['main_category'].unique()

array(['Digital Music', 'Movies & TV', 'Cell Phones & Accessories',
       'Books', 'Musical Instruments', 'Tools & Home Improvement',
       'Amazon Home', 'All Electronics', 'Toys & Games',
       'Health & Personal Care', 'Office Products', None, 'Software',
       'Home Audio & Theater', 'Video Games', 'Audible Audiobooks',
       'Industrial & Scientific', 'Grocery', 'All Beauty',
       'Arts, Crafts & Sewing', 'Sports & Outdoors', 'Pet Supplies',
       'Baby', 'Camera & Photo', 'Appliances', 'Computers',
       'AMAZON FASHION', 'Collectible Coins', 'Entertainment',
       'Automotive'], dtype=object)

In [11]:
meta_df.shape

(701959, 16)

In [12]:
meta_df = meta_df.drop_duplicates(subset=['parent_asin'],keep='last')
meta_df.shape

(701959, 16)

In [13]:
# drop cols dont provide contextual meaning
meta = meta_df.drop(['images', 'features', 'videos', 'store', 'price', 'details', 'bought_together', 'subtitle', 'author'], axis='columns')
meta

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,main_category,title,average_rating,rating_number,description,categories,parent_asin
0,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",B000002X4C
1,Digital Music,Rio Angie,5.000000,1,"Shrimp City Slim (aka Gary Erwin, b. 1953, Chi...","CDs & Vinyl, Jazz, Avant Garde & Free Jazz",B00902T10Y
2,Digital Music,Lost in Love,5.000000,9,,"CDs & Vinyl, Rap & Hip-Hop, Gangsta & Hardcore",B00000DALY
3,Digital Music,Somewhere in Time,4.800781,1186,The 1980 soundtrack to the now classic motion ...,"CDs & Vinyl, Soundtracks, Movie Scores",B0000086D1
4,Digital Music,Kimmon Waldruff,5.000000,1,Solo acoustic fingerstyle guitar.,"CDs & Vinyl, Folk",B000S6W7KC
...,...,...,...,...,...,...,...
701954,Digital Music,Forever Gold: British Invasion,3.000000,1,British Invasion ~ Forever Gold: British Invasion,"CDs & Vinyl, International Music, Europe, Brit...",B00005AVHN
701955,Digital Music,"Joan Hammond, Historical Recordings from 1941-49",5.000000,1,,"CDs & Vinyl, Classical",B000T001IM
701956,Digital Music,Come Alive,4.500000,4,The Second Full Length Album from the Winner o...,"CDs & Vinyl, International Music, Africa, Sout...",B00069I6RO
701957,Digital Music,Long Day in the Milky Way,4.398438,16,2020 release from the folk/Americana singer/so...,"CDs & Vinyl, Folk",B08BF2PH1X
701958,Digital Music,Genius of Valiha,3.000000,1,World Music Library 122. Track List: 1 Faly mi...,"CDs & Vinyl, International Music",B000001LW6

In [14]:
merge = user_df2.merge(meta, on='parent_asin', how='right')
merge

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,asin,parent_asin,user_id,timestamp,main_category,title,average_rating,rating_number,description,categories
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
2,4.0,B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,9.534267e+11,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
3,5.0,B000002X4C,B000002X4C,AE73R3KLFKXFNWUBOA4JCLT5UWKA,1.427480e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
4,2.0,B000002X4C,B000002X4C,AFICHVZ62IFAWIBZK3U6B7NZWAVQ,1.289638e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
...,...,...,...,...,...,...,...,...,...,...,...
4827554,5.0,B000T001IM,B000T001IM,AFICGLJ62Y3YRTYN7PNYM6UUOA6Q,1.387540e+12,Digital Music,"Joan Hammond, Historical Recordings from 1941-49",5.000000,1,,"CDs & Vinyl, Classical"
4827555,4.0,B00069I6RO,B00069I6RO,AHLRFMDIVAQF7ARTPM6PVJO6DTYQ,1.199348e+12,Digital Music,Come Alive,4.500000,4,The Second Full Length Album from the Winner o...,"CDs & Vinyl, International Music, Africa, Sout..."
4827556,5.0,B00069I6RO,B00069I6RO,AGZVQUGBE64F3M2A5EBU2CNDTKIA,1.103150e+12,Digital Music,Come Alive,4.500000,4,The Second Full Length Album from the Winner o...,"CDs & Vinyl, International Music, Africa, Sout..."
4827557,5.0,B08BF2PH1X,B08BF2PH1X,AEZET6CFIEJWTU7UTEK57IDARX2A,1.612912e+12,Digital Music,Long Day in the Milky Way,4.398438,16,2020 release from the folk/Americana singer/so...,"CDs & Vinyl, Folk"
4827558,3.0,B000001LW6,B000001LW6,AGL4DWXKWAREPMSTB4OVWH3OY3KQ,1.091994e+12,Digital Music,Genius of Valiha,3.000000,1,World Music Library 122. Track List: 1 Faly mi...,"CDs & Vinyl, International Music"

In [15]:
date_min = pd.to_datetime(merge.timestamp,unit='ms').min()
date_max = pd.to_datetime(merge.timestamp,unit='ms').max()
date_min, date_max

(Timestamp('1997-09-09 03:13:17'), Timestamp('2023-09-09 15:33:39.315000'))

In [16]:
date_gap = (date_max-date_min)//(26*2)
date_gap

Timedelta('182 days 15:00:23.506057692')

In [17]:
merge_df2 = merge.copy()
merge_df2.columns

Index(['rating', 'asin', 'parent_asin', 'user_id', 'timestamp',
       'main_category', 'title', 'average_rating', 'rating_number',
       'description', 'categories'],
      dtype='object')

In [18]:
merge_df2.columns = ['rating', 'iid', 'parent_iid', 'uid', 'timestamp',
       'main_category', 'title', 'average_rating', 'rating_number',
       'description', 'categories']
merge_df2.head(2)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,iid,parent_iid,uid,timestamp,main_category,title,average_rating,rating_number,description,categories
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"

In [19]:
merge_df2.shape

(4827559, 11)

In [20]:
merge_df2['year'] = pd.to_datetime(merge_df2['timestamp'], unit='ms').dt.year
merge_df2.head(2)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,iid,parent_iid,uid,timestamp,main_category,title,average_rating,rating_number,description,categories,year
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2015.0
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2013.0

In [21]:
merge_df2 = merge_df2.dropna()
merge_df2.shape

(4823633, 12)

In [22]:
merge_df2.iid.nunique(), merge_df2.parent_iid.unique(), merge_df2.uid.nunique()

(700877,
 array(['B000002X4C', 'B00902T10Y', 'B00000DALY', ..., 'B00069I6RO',
        'B08BF2PH1X', 'B000001LW6'], shape=(700844,), dtype=object),
 1752912)

In [23]:
np.sort(merge_df2.year.unique())

array([1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005.,
       2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014.,
       2015., 2016., 2017., 2018., 2019., 2020., 2021., 2022., 2023.])

In [24]:
#  number of ratings given by each user in the s_rating
merge_df2.groupby('uid').agg({"rating":'count'})

                              rating
uid
AE22232OB6S7UAC75JUFYRGBSHIQ       1
AE22236AFRRSMQIKGG7TPTB75QEA       4
AE222GY2VH7MEWI4N5AHPXB5CP5A       1
AE222H3FGXWLHRFUMGMS2RR57NDQ       8
AE222K4ISB45WWMKN7VSYH5WBNNQ       2
...                              ...
AHZZZSX4HTKLTFHCS4MEXKCNMJAA       1
AHZZZWVHLYTQU55PD4FJULUEKTXA       1
AHZZZZ3CH2ZFY4CLZTVGAJYCAWIA       1
AHZZZZUZCRIUWGMXKFAJO3T5S45A       1
AHZZZZYA4NULLM5PNACIU3GA5OQQ       1

[1752912 rows x 1 columns]

In [25]:
item_info = merge_df2.groupby('iid').agg({"rating_number": 'first'})
user_info = merge_df2.groupby('uid').agg({"rating":'count'})

In [26]:
# filters the user_info, item_info DF to select items that have received more than 20 ratings
active_item = item_info[item_info['rating_number']>20].index
active_user = user_info[user_info['rating']>20].index
active_item.shape, active_user.shape

((258651,), (21839,))

In [39]:
# filters the item_info df to select items that have received more than 20 ratings
# .index is then used to retrieve the IDs of these active items
merge_df3 = merge_df2[merge_df2['uid'].isin(active_user)]
print(merge_df3.shape)
merge_df3 = merge_df2[merge_df2['iid'].isin(active_item)]
print(merge_df3.shape)

(1165602, 12)
(3937092, 12)

In [40]:
item_info2 = merge_df3.groupby('iid').agg({"rating_number": 'first'})
user_info2 = merge_df3.groupby('uid').agg({"rating":'count'})
user_info2.mean(), item_info2.mean()

(rating    2.526467
 dtype: float64,
 rating_number    289.008289
 dtype: float64)

In [41]:
merge_df3 = merge_df2[merge_df2['iid'].isin(active_item)]
merge_df3.shape

(3937092, 12)

In [42]:
merge_df3.iid.nunique(), merge_df3.parent_iid.nunique(), merge_df3.uid.nunique()

(258651, 258637, 1558339)

In [37]:
merge_df3.head(3)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,iid,parent_iid,uid,timestamp,main_category,title,average_rating,rating_number,description,categories,year
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2015.0
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2013.0
2,4.0,B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,9.534267e+11,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2000.0

In [43]:
merge_df3.groupby('year').agg({'rating':'count'}).reset_index().plot(x='year',kind='bar')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [44]:
merge_df3['label'] = 0
merge_df3.loc[merge_df3['rating'] >= 4, 'label'] = 1
merge_df3['label'].describe()

/var/folders/1l/fxxxl8p13clcn13ph4b5wcjc0000gn/T/ipykernel_99256/2042806392.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge_df3['label'] = 0

count    3.937092e+06
mean     8.744667e-01
std      3.313226e-01
min      0.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: label, dtype: float64

In [32]:
# creates mappings for user IDs and item IDs to consecutive numerical values, starting from 1
users = merge_df3.uid.unique()
items = merge_df3.iid.unique()

# creates dicts users_map, items_map where each unique uid, iid is mapped to a consecutive numerical value starting from 1
users_map = dict(zip(users, np.arange(users.shape[0])+1))
items_map = dict(zip(items, np.arange(items.shape[0])+1))

merge_df3['uid'] = merge_df3['uid'].map(users_map)
merge_df3['iid'] = merge_df3['iid'].map(items_map)
merge_df3.uid.max(), merge_df3.iid.max()

/var/folders/1l/fxxxl8p13clcn13ph4b5wcjc0000gn/T/ipykernel_94953/1897254940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge_df3['uid'] = merge_df3['uid'].map(users_map)
/var/folders/1l/fxxxl8p13clcn13ph4b5wcjc0000gn/T/ipykernel_94953/1897254940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge_df3['iid'] = merge_df3['iid'].map(items_map)

(1558339, 258651)

In [33]:
merge_df3.head(3)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,iid,parent_iid,uid,timestamp,main_category,title,average_rating,rating_number,description,categories,year,label
0,1.0,1,B000002X4C,1,1.420266e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2015.0,0
1,1.0,1,B000002X4C,2,1.379363e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2013.0,0
2,4.0,1,B000002X4C,3,9.534267e+11,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2000.0,1

In [34]:
merge_df3['time'] = ((pd.to_datetime(merge_df3['timestamp'], unit='ms') - date_min) // date_gap).astype(int)
merge_df3.head(5)

/var/folders/1l/fxxxl8p13clcn13ph4b5wcjc0000gn/T/ipykernel_94953/3529764540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge_df3['time'] = ((pd.to_datetime(merge_df3['timestamp'], unit='ms') - date_min) // date_gap).astype(int)
/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,iid,parent_iid,uid,timestamp,main_category,title,average_rating,rating_number,description,categories,year,label,time
0,1.0,1,B000002X4C,1,1.420266e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2015.0,0,34
1,1.0,1,B000002X4C,2,1.379363e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2013.0,0,32
2,4.0,1,B000002X4C,3,9.534267e+11,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2000.0,1,5
3,5.0,1,B000002X4C,4,1.427480e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2015.0,1,35
4,2.0,1,B000002X4C,5,1.289638e+12,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",2010.0,0,26

In [35]:
#  splits the merge_df3 into train, val and test sets based on time
rating_train = merge_df3[merge_df3['time'].isin(range(2 * 26 - 2))].copy()
rating_valid_test = merge_df3[merge_df3['time'] == 2 * 26 - 2].copy()
rating_valid_test.sort_values(by='timestamp', inplace=True)
n = rating_valid_test.shape[0] // 2
rating_valid = rating_valid_test.iloc[:n].copy()
rating_test = rating_valid_test.iloc[n:].copy()
rating_train.shape, rating_valid.shape, rating_test.shape

((3862643, 14), (27538, 14), (27539, 14))

In [36]:
# identify cold-start, warm-start for val and test sets
# Adds a 'not_cold' column to rating_valid, marking interactions as 1 if both user and item exist in the training set, else 0
train_user = rating_train['uid'].unique()
train_item = rating_train['iid'].unique()
rating_valid['not_cold'] = rating_valid[['uid','iid']].apply(lambda x: x.uid in train_user and x.iid in train_item, axis=1).astype("int")
rating_test['not_cold'] = rating_test[['uid','iid']].apply(lambda x: x.uid in train_user and x.iid in train_item, axis=1).astype("int")

In [37]:
rating_train.shape, rating_valid.shape, rating_test.shape

((3862643, 14), (27538, 15), (27539, 15))

In [38]:
rating_valid.not_cold.value_counts(), rating_test.not_cold.value_counts()

(not_cold
 0    16396
 1    11142
 Name: count, dtype: int64,
 not_cold
 0    17649
 1     9890
 Name: count, dtype: int64)

In [39]:
# remove cold-start interactions from the validation and test sets
# cold-start interactions involve users or items that were not present in the training data
def filter_cold_start(train,valid,test):
    train_user = train.uid.unique()
    train_item = train.iid.unique()
    valid = valid[valid['uid'].isin(train_user)]
    test = test[test['uid'].isin(train_user)]
    valid = valid[valid['iid'].isin(train_item)]
    test = test[test['iid'].isin(train_item)]
    return valid, test

In [40]:
rating_train.label.mean(), rating_valid.label.mean(), rating_test.label.mean()

(np.float64(0.8750749163202501),
 np.float64(0.8467572082213668),
 np.float64(0.8432768074367261))

In [41]:
# processes interaction data for each user
# creating a list of tuples representing each interaction along with the user's history
import copy

def deal_with_each_u(x,u):
    items = np.array(x.iid)
    labels = np.array(x.label)
    titles = np.array(x.title)
    categories = list(x.categories)
    timestamp = np.array(x.timestamp)
    flags =  np.array(x.flag)# adding a '0' by default
    his = [0] # adding a '0' by default
    his_title = ['']
    his_cats = ['']
    results = []
    for i in range(items.shape[0]):
        results.append((u, items[i], timestamp[i], np.array(his), copy.copy(his_title), copy.copy(his_cats), titles[i], categories[i], labels[i], flags[i]))
        # training data
        #  If the interaction is positive, the item ID and title are added to the user's history lists
        if labels[i] > 0: # positive
            his.append(items[i])
            his_title.append(titles[i])
            his_cats.append(categories[i])
        # validation data
    return results

In [42]:
rating_valid_2 = rating_valid
rating_test_2 = rating_test

In [43]:
# adds a 'flag' column to the training, validation, and test sets
# assigns a value of -1 to all rows in this column, indicating that these rows belong to the training set
rating_train['flag'] =  pd.DataFrame(np.ones(rating_train.shape[0])*-1, index = rating_train.index) # 0 ~ valid set
rating_valid_2['flag'] = pd.DataFrame(np.zeros(rating_valid_2.shape[0]), index = rating_valid_2.index)  # 1 ~ test set
rating_test_2['flag'] = pd.DataFrame(np.ones(rating_test_2.shape[0]), index = rating_test_2.index)
data = pd.concat([rating_train, rating_valid_2, rating_test_2], axis = 0, ignore_index = True)
data = data.sort_values(by = ['uid','timestamp'])

# groups data df by user ID
# for each user group, it creates lists of item IDs ('iid'), labels, titles, description, timestamps, flags
u_inter_all = data.groupby('uid').agg({'iid':list, 'label':list, 'title':list, 'categories': list, 'timestamp':list,'flag':list})

In [44]:
data.flag.unique()

array([-1.,  1.,  0.])

In [45]:
data.head(5)

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,rating,iid,parent_iid,uid,timestamp,main_category,title,average_rating,rating_number,description,categories,year,label,time,flag,not_cold
1745738,3.0,105479,B001QCKJAM,1,1.372449e+12,Digital Music,Xscape: Super Hits,4.699219,826,I will ship by EMS or SAL items in stock in Ja...,"CDs & Vinyl, Pop, Dance Pop",2013.0,0,31,-1.0,NaN
1724819,5.0,104236,B000063BQL,1,1.398165e+12,Digital Music,Ultimate Collection,4.800781,406,Johnny Gill Collection gathers his best solo h...,"CDs & Vinyl, R&B, Soul",2014.0,1,33,-1.0,NaN
2635765,5.0,158516,B000001E3R,1,1.400653e+12,Digital Music,Natural Thing,4.699219,40,,"CDs & Vinyl, R&B, Soul",2014.0,1,33,-1.0,NaN
562036,1.0,33730,B000251Y1C,1,1.413461e+12,Digital Music,Understanding,4.699219,50,CD,"CDs & Vinyl, Pop, Dance Pop",2014.0,0,34,-1.0,NaN
2696436,5.0,162105,B0002Y4SUC,1,1.414292e+12,Digital Music,Soulful Sounds of Christmas,4.601562,40,"Product Description, Get your holiday groove o...","CDs & Vinyl, Holiday & Wedding, Christmas",2014.0,1,34,-1.0,NaN

In [46]:
u_inter_all.head(5)

,iid,label,title,categories,timestamp,flag
uid,,,,,,
1,"[105479, 104236, 158516, 33730, 162105, 218784...","[0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, ...","[Xscape: Super Hits, Ultimate Collection, Natu...","[CDs & Vinyl, Pop, Dance Pop, CDs & Vinyl, R&B...","[1372448540000.0, 1398165102000.0, 14006530020...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
2,"[29331, 145502, 193578, 51302, 39011, 136252, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, ...","[Haunted, Mexican Moon, Ten, For Unlawful Carn...","[CDs & Vinyl, Pop, Singer-Songwriters, CDs & V...","[1282765017000.0, 1300378226000.0, 13014264660...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
3,"[183280, 188922, 215753, 42891, 84885, 151334,...","[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, ...","[1999, This Is Your Night, Design of a Decade ...","[CDs & Vinyl, Indie & Alternative, New Wave & ...","[946548860000.0, 946556194000.0, 947984281000....","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
4,"[215749, 109076, 45769, 154300, 201946, 163658...","[1, 1, 1, 1, 1, 1, 1, 1, 1]","[Piece of Mind Explicit Lyrics, Shabba R...","[CDs & Vinyl, R&B, Funk, CDs & Vinyl, Reggae, ...","[1356674276000.0, 1358400582000.0, 13584006580...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
5,"[214310, 53073, 81194, 197200, 124266, 33678, ...","[1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, ...","[Charmbracelet, The Soul Sessions, Javier, The...","[CDs & Vinyl, Pop, Adult Contemporary, CDs & V...","[1057855934000.0, 1066771811000.0, 10691320250...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."

In [47]:
# each user in the u_inter_all df  
# apply the deal_with_each_u function to process their interaction data
# retrieves the row corresponding to the current uid and uid then add it to results
results = []
for u in u_inter_all.index:
    results.extend(deal_with_each_u(u_inter_all.loc[u], u))

In [48]:
len(results)

3917720

In [49]:
u, i, time, label, his, his_title, his_cats, title, categories, flag = [], [], [], [], [], [], [], [], [], []
for re in results:
    u.append(re[0])
    i.append(re[1])
    time.append(re[2])
    his.append(re[3])
    his_title.append(re[4])
    his_cats.append(re[5])
    title.append(re[6])
    categories.append(re[7])
    label.append(re[8])
    flag.append(re[9])

In [50]:
data = pd.DataFrame({"uid": u,'iid': i,'label': label, 'timestamp': time, 'his': his,'his_title': his_title, 'his_cats': his_cats, 'title': title, 'categories': categories, 'flag': flag})

In [51]:
data.head(5)

,uid,iid,label,timestamp,his,his_title,his_cats,title,categories,flag
0,1,105479,0,1.372449e+12,[0],[],[],Xscape: Super Hits,"CDs & Vinyl, Pop, Dance Pop",-1.0
1,1,104236,1,1.398165e+12,[0],[],[],Ultimate Collection,"CDs & Vinyl, R&B, Soul",-1.0
2,1,158516,1,1.400653e+12,"[0, 104236]","[, Ultimate Collection]","[, CDs & Vinyl, R&B, Soul]",Natural Thing,"CDs & Vinyl, R&B, Soul",-1.0
3,1,33730,0,1.413461e+12,"[0, 104236, 158516]","[, Ultimate Collection, Natural Thing]","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Understanding,"CDs & Vinyl, Pop, Dance Pop",-1.0
4,1,162105,1,1.414292e+12,"[0, 104236, 158516]","[, Ultimate Collection, Natural Thing]","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Soulful Sounds of Christmas,"CDs & Vinyl, Holiday & Wedding, Christmas",-1.0

In [52]:
data.tail(5)

,uid,iid,label,timestamp,his,his_title,his_cats,title,categories,flag
3917715,1558335,258646,1,1.572986e+12,[0],[],[],My Love Is Your Love,"CDs & Vinyl, Pop, Adult Contemporary",-1.0
3917716,1558336,258648,1,1.537987e+12,[0],[],[],Streets of Gold explicit_lyrics,"CDs & Vinyl, Pop, Adult Alternative",-1.0
3917717,1558337,258649,1,1.525041e+12,[0],[],[],EXO-K Mama 1st Mini Album CD Korean Language K...,"CDs & Vinyl, Pop, Korean Pop",-1.0
3917718,1558338,258649,1,1.447653e+12,[0],[],[],EXO-K Mama 1st Mini Album CD Korean Language K...,"CDs & Vinyl, Pop, Korean Pop",-1.0
3917719,1558339,258649,1,1.515795e+12,[0],[],[],EXO-K Mama 1st Mini Album CD Korean Language K...,"CDs & Vinyl, Pop, Korean Pop",-1.0

In [53]:
data.label.describe()

count    3.917720e+06
mean     8.746523e-01
std      3.311127e-01
min      0.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: label, dtype: float64

In [54]:
train = data[data['flag'].isin([-1])].copy()
val = data[data['flag'].isin([0])].copy()
test = data[data['flag'].isin([1])].copy()
train.shape,val.shape,test.shape

((3862643, 10), (27538, 10), (27539, 10))

In [55]:
train_user = train['uid'].unique()
train_item = train['iid'].unique()
val['not_cold'] = val[['uid','iid']].apply(lambda x: x.uid in train_user and x.iid in train_item, axis=1).astype("int")
test['not_cold'] = test[['uid','iid']].apply(lambda x: x.uid in train_user and x.iid in train_item, axis=1).astype("int")

In [56]:
train['not_cold'] = pd.DataFrame(np.ones(train.shape[0]), index = train.index).astype("int")
train.head(2)

,uid,iid,label,timestamp,his,his_title,his_cats,title,categories,flag,not_cold
0,1,105479,0,1.372449e+12,[0],[],[],Xscape: Super Hits,"CDs & Vinyl, Pop, Dance Pop",-1.0,1
1,1,104236,1,1.398165e+12,[0],[],[],Ultimate Collection,"CDs & Vinyl, R&B, Soul",-1.0,1

In [57]:
train.shape, val.shape, test.shape

((3862643, 11), (27538, 11), (27539, 11))

In [58]:
train.head(10)

,uid,iid,label,timestamp,his,his_title,his_cats,title,categories,flag,not_cold
0,1,105479,0,1.372449e+12,[0],[],[],Xscape: Super Hits,"CDs & Vinyl, Pop, Dance Pop",-1.0,1
1,1,104236,1,1.398165e+12,[0],[],[],Ultimate Collection,"CDs & Vinyl, R&B, Soul",-1.0,1
2,1,158516,1,1.400653e+12,"[0, 104236]","[, Ultimate Collection]","[, CDs & Vinyl, R&B, Soul]",Natural Thing,"CDs & Vinyl, R&B, Soul",-1.0,1
3,1,33730,0,1.413461e+12,"[0, 104236, 158516]","[, Ultimate Collection, Natural Thing]","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Understanding,"CDs & Vinyl, Pop, Dance Pop",-1.0,1
4,1,162105,1,1.414292e+12,"[0, 104236, 158516]","[, Ultimate Collection, Natural Thing]","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Soulful Sounds of Christmas,"CDs & Vinyl, Holiday & Wedding, Christmas",-1.0,1
5,1,218784,1,1.419318e+12,"[0, 104236, 158516, 162105]","[, Ultimate Collection, Natural Thing, Soulful...","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Number Ones,"CDs & Vinyl, Pop, Adult Contemporary",-1.0,1
6,1,93473,1,1.419323e+12,"[0, 104236, 158516, 162105, 218784]","[, Ultimate Collection, Natural Thing, Soulful...","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Pure 80's Love: The #1 Hits,"CDs & Vinyl, Pop",-1.0,1
7,1,10494,1,1.419512e+12,"[0, 104236, 158516, 162105, 218784, 93473]","[, Ultimate Collection, Natural Thing, Soulful...","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",NKOTBSB,"CDs & Vinyl, Pop",-1.0,1
8,1,219864,1,1.419647e+12,"[0, 104236, 158516, 162105, 218784, 93473, 10494]","[, Ultimate Collection, Natural Thing, Soulful...","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Faith Evans,"CDs & Vinyl, Dance & Electronic, House",-1.0,1
9,1,146041,1,1.419647e+12,"[0, 104236, 158516, 162105, 218784, 93473, 104...","[, Ultimate Collection, Natural Thing, Soulful...","[, CDs & Vinyl, R&B, Soul, CDs & Vinyl, R&B, S...",Special Christmas,"CDs & Vinyl, Holiday & Wedding, Christmas",-1.0,1

In [59]:
shuffled_train = train.sample(frac=1, random_state=42).reset_index(drop=True)

# 10k and 100k interaction samples
sample_10k = shuffled_train.iloc[:10_000].copy()
sample_100k = shuffled_train.iloc[:100_000].copy()

In [61]:
save_to_path = "../../data/amazon/samples"
os.makedirs(save_to_path, exist_ok=True)

sample_10k.to_csv(os.path.join(save_to_path, "sample_10k.csv"), index=False)
sample_100k.to_csv(os.path.join(save_to_path, "sample_100k.csv"), index=False)
print("Saved 10k and 100k interaction samples.")

Saved 10k and 100k interaction samples.

In [58]:
# get sample of 100k users
unique_users = train['uid'].unique()
sampled_user_ids = pd.Series(unique_users).sample(n=100000, random_state=42)

sampled_train = train[train['uid'].isin(sampled_user_ids)].copy()

print(f"Sampled {len(sampled_user_ids)} users")
print(f"Resulting dataset has {len(sampled_train)} interactions")
print(f"Unique items in sampled set: {sampled_train['iid'].nunique()}")

Sampled 100000 users
Resulting dataset has 248383 interactions
Unique items in sampled set: 92781

In [59]:
# dataset = Dataset()
from lightfm import LightFM
from lightfm.data import Dataset


def fit_and_train(data, learning_rate, epochs):
    dataset = Dataset()
    dataset.fit(data['uid'], data['iid'])

    # build interaction matrices
    interactions, weights = dataset.build_interactions((row['uid'], row['iid'], row['label']) for id, row in data.iterrows())

    model = LightFM(loss='warp', learning_rate=learning_rate, item_alpha=1e-6, user_alpha=1e-6)
    # train model
    model.fit(interactions, epochs=epochs, num_threads=4, sample_weight=weights)
    return model, dataset, interactions
    
    # test_interactions, test_w = dataset.build_interactions((row['user_id_encoded'], row['asin_encoded']) for id, row in df_test.iterrows())

/Users/vynguyen/anaconda3/envs/thesis/lib/python3.11/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(

In [ ]:
def get_top_k(model, dataset, data, user_id, k):    
    n_users, n_items = dataset.interactions_shape()
    user_id_to_index, item_id_to_index, _, _ = dataset.mapping()
    user_index = user_id_to_index[user_id]
    rated_raw_items = set(data[data['uid'] == user_id]['iid'])

    # convert raw IDs to valid indices (skip unseen items)
    rated_indices = [
        item_id_to_index[i] 
        for i in rated_raw_items 
        if i in item_id_to_index 
    ]
    user_indices = np.full(n_items, user_index)
    item_indices = np.arange(n_items)
    scores = model.predict(user_indices, item_indices)
    
    # user_ids = np.full(n_items, user_id)  # or use np.repeat(user_id, n_items)
    # # item_ids = np.arange(n_items)
    # rated_items = set(data[data['uid']==user_id]['iid'])

    # scores = model.predict(user_ids, np.arange(n_items))
    # scores[list(rated_items)] = -np.inf
    # top_items = np.argsort(-scores)[:k]

    scores[rated_indices] = -np.inf

    # Get top-k items (as LightFM indices)
    top_indices = np.argsort(-scores)[:k]

    # Map top indices back to raw IDs for lookup
    index_to_item_id = {v: k for k, v in item_id_to_index.items()}
    top_raw_items = [index_to_item_id[i] for i in top_indices]

    items_lookup = {
        iid: {
            'iid': iid,
            'title': title,
            'categories': cat,
        }
        for iid, title, cat in zip(data['iid'], data['title'], data['categories'])
    }
    
    # recs = [
    #     {
    #         **items_lookup[i],
    #         'score': float(scores[i])
    #     }
    #     for i in top_items if i in items_lookup
    # ]

    recs = [{
            **items_lookup[iid],
            'score': float(scores[item_id_to_index[iid]])
        }
        for iid in top_raw_items if iid in items_lookup]
    
    # iid_info = dict(zip(data['iid'], zip(data['iid'], data['title'], data['description'])))
    # recs = [iid_info[item] for item in top_items if item in iid_info]
    return recs


# def get_recs(user_id):
#     return recs_dict.get(user_id, [])

In [60]:
def get_all_user_recommendations_batch(model, dataset, data, k=50, batch_size=100):
    """
    Optimized version using batch prediction for better performance
    """
    n_users, n_items = dataset.interactions_shape()
    user_id_to_index, item_id_to_index = dataset.mapping()[:2]
    
    # Get all unique user IDs from training data
    all_user_ids = data['uid'].unique()
    
    # Create reverse mapping
    index_to_item_id = {v: k for k, v in item_id_to_index.items()}
    
    user_recommendations = {}
    
    print(f"Processing {len(all_user_ids)} users in batches of {batch_size}")
    
    for i in tqdm(range(0, len(all_user_ids), batch_size)):
        batch_user_ids = all_user_ids[i:i+batch_size]
        
        # Filter valid users
        valid_users = [uid for uid in batch_user_ids if uid in user_id_to_index]
        
        if not valid_users:
            continue
            
        # Create user and item index arrays for batch prediction
        user_indices = np.array([user_id_to_index[uid] for uid in valid_users])
        
        # For each user, predict against all items
        for user_id in valid_users:
            try:
                user_index = user_id_to_index[user_id]
                
                # Get rated items
                rated_items = set(data[data['uid'] == user_id]['iid'])
                rated_indices = [item_id_to_index[i] for i in rated_items if i in item_id_to_index]
                
                # Predict for this user against all items
                user_array = np.full(n_items, user_index, dtype=np.int32)
                item_array = np.arange(n_items, dtype=np.int32)
                
                scores = model.predict(user_array, item_array)
                
                # Mask rated items
                scores[rated_indices] = -np.inf
                
                # Get top-k
                top_indices = np.argsort(-scores)[:k]
                
                # Convert to recommendations
                recommendations = []
                for idx in top_indices:
                    if idx in index_to_item_id:
                        raw_item_id = index_to_item_id[idx]
                        item_data = data[data['iid'] == raw_item_id]
                        if not item_data.empty:
                            item_row = item_data.iloc[0]
                            recommendations.append({
                                'iid': raw_item_id,
                                'title': item_row['title'],
                                'categories': item_row['categories'],
                                'score': float(scores[idx])
                            })
                
                user_recommendations[user_id] = recommendations
                
            except Exception as e:
                print(f"Error processing user {user_id}: {e}")
                continue
    
    return user_recommendations

In [61]:
 model, dataset, interactions = fit_and_train(sampled_train, learning_rate=0.01, epochs=50)

In [62]:
user_recs = get_all_user_recommendations_batch(model, dataset, sampled_train, k=50)
print(f"Generated recommendations for {len(user_recs)} users")
print(f"Sample user recommendations: {list(user_recs.keys())[:3]}")

Processing 100000 users in batches of 100

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [26:08<00:00,  1.57s/it]

Generated recommendations for 100000 users
Sample user recommendations: [np.int64(32), np.int64(34), np.int64(77)]

In [63]:
print(f"Sample user recommendations: {list(user_recs.values())[:5]}")

Sample user recommendations: [[{'iid': 170245, 'title': np.str_('Of Vengeance & Violence'), 'categories': 'CDs & Vinyl, Metal, Alternative Metal', 'score': 0.9593205451965332}, {'iid': 95724, 'title': np.str_('Colour the Small One'), 'categories': 'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock', 'score': 0.9240134954452515}, {'iid': 155333, 'title': np.str_('Pastel Blues'), 'categories': 'CDs & Vinyl, Broadway & Vocalists, Cabaret', 'score': 0.9088192582130432}, {'iid': 185782, 'title': np.str_('Wishbone Four'), 'categories': "CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10", 'score': 0.8685558438301086}, {'iid': 185493, 'title': np.str_('Roy Orbisons Greatest Hits'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.8253015875816345}, {'iid': 1331, 'title': np.str_('Coral Fang       Explicit Lyrics'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk', 'score': 0.8169475197792053}, {'iid': 77088, 'title': np.str_('Hammered Dulcimer Christmas'), 'categories': 'CDs & Vinyl, Holiday & Wedding, Christmas', 'score': 0.7892606854438782}, {'iid': 1322, 'title': np.str_('On the Night - Live'), 'categories': "CDs & Vinyl, Today's Deals in Music, Classic Rock, Album-Oriented Rock (AOR), CDs $7 - $10", 'score': 0.766628086566925}, {'iid': 191392, 'title': np.str_('Millennium Collection - 20th Century Masters'), 'categories': 'CDs & Vinyl, Christian & Gospel, Pop & Contemporary', 'score': 0.7593280673027039}, {'iid': 110457, 'title': np.str_('Story of the Clash I'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk', 'score': 0.7441343069076538}, {'iid': 12652, 'title': np.str_('The "Angry" Young Them!'), 'categories': 'CDs & Vinyl, Rock, Blues Rock', 'score': 0.7407299876213074}, {'iid': 76343, 'title': np.str_('Eddy Duchin Story + Eddy Duchin Remembered'), 'categories': 'CDs & Vinyl, Pop, Easy Listening', 'score': 0.6850771903991699}, {'iid': 77414, 'title': np.str_('The Comeback Kid'), 'categories': 'CDs & Vinyl, Indie & Alternative, Alternative Rock', 'score': 0.6695731282234192}, {'iid': 2019, 'title': np.str_('Greatest Hits, Vol. 01'), 'categories': 'CDs & Vinyl, Pop, Oldies, Doo Wop', 'score': 0.6692941784858704}, {'iid': 34223, 'title': np.str_('Greatest Hits'), 'categories': "CDs & Vinyl, Today's Deals in Music, Alternative Rock, Alternative General, CDs $7 - $10", 'score': 0.6344746351242065}, {'iid': 102548, 'title': np.str_('Hello Happiness'), 'categories': 'CDs & Vinyl, R&B, Soul, Blue-Eyed Soul', 'score': 0.626410186290741}, {'iid': 27066, 'title': np.str_('St. Cecelia Mass'), 'categories': 'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Masses', 'score': 0.6263030767440796}, {'iid': 32882, 'title': np.str_('Gaither Gospel Series: The Isaacs Live From Norway'), 'categories': 'CDs & Vinyl, Christian & Gospel, Gospel, Southern', 'score': 0.6153507828712463}], [{'iid': 95724, 'title': np.str_('Colour the Small One'), 'categories': 'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock', 'score': 1.179807424545288}, {'iid': 191392, 'title': np.str_('Millennium Collection - 20th Century Masters'), 'categories': 'CDs & Vinyl, Christian & Gospel, Pop & Contemporary', 'score': 1.1531850099563599}, {'iid': 155333, 'title': np.str_('Pastel Blues'), 'categories': 'CDs & Vinyl, Broadway & Vocalists, Cabaret', 'score': 1.1502381563186646}, {'iid': 139750, 'title': np.str_('Mendelssohn: The Complete String Quartets / Pacifica Quartet'), 'categories': 'CDs & Vinyl, Classical, Chamber Music', 'score': 1.0161371231079102}, {'iid': 120292, 'title': np.str_('Scarred'), 'categories': 'CDs & Vinyl, Folk, Contemporary Folk', 'score': 0.8742977976799011}, {'iid': 185493, 'title': np.str_('Roy Orbisons Greatest Hits'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.8704085946083069}, {'iid': 175348, 'title': np.str_('Careless People'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.8688889741897583}, {'iid': 27066, 'title': np.str_('St. Cecelia Mass'), 'categories': 'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Masses', 'score': 0.8585649132728577}, {'iid': 12652, 'title': np.str_('The "Angry" Young Them!'), 'categories': 'CDs & Vinyl, Rock, Blues Rock', 'score': 0.8579466938972473}, {'iid': 116971, 'title': np.str_('Everything Is Possible: The Very Best of Living Colour'), 'categories': "CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10", 'score': 0.8436163663864136}, {'iid': 15082, 'title': np.str_('Blue Suede Shoes Set'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.7879559397697449}, {'iid': 8803, 'title': np.str_('Wicked Mans Rest'), 'categories': 'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock', 'score': 0.7767699956893921}, {'iid': 76840, 'title': np.str_('Where Have All Flowers Gone: Songs of Pete Seeger'), 'categories': 'CDs & Vinyl, Folk, British & Celtic Folk, British Folk', 'score': 0.7722450494766235}, {'iid': 119659, 'title': np.str_('Live It Up'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.7721186876296997}, {'iid': 29930, 'title': np.str_('Total Depravity'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.7690561413764954}], [{'iid': 95724, 'title': np.str_('Colour the Small One'), 'categories': 'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock', 'score': 1.0397413969039917}, {'iid': 32882, 'title': np.str_('Gaither Gospel Series: The Isaacs Live From Norway'), 'categories': 'CDs & Vinyl, Christian & Gospel, Gospel, Southern', 'score': 0.9836426973342896}, {'iid': 170245, 'title': np.str_('Of Vengeance & Violence'), 'categories': 'CDs & Vinyl, Metal, Alternative Metal', 'score': 0.9694384932518005}, {'iid': 139750, 'title': np.str_('Mendelssohn: The Complete String Quartets / Pacifica Quartet'), 'categories': 'CDs & Vinyl, Classical, Chamber Music', 'score': 0.9677174091339111}, {'iid': 155333, 'title': np.str_('Pastel Blues'), 'categories': 'CDs & Vinyl, Broadway & Vocalists, Cabaret', 'score': 0.9393640756607056}, {'iid': 120292, 'title': np.str_('Scarred'), 'categories': 'CDs & Vinyl, Folk, Contemporary Folk', 'score': 0.8884671330451965}, {'iid': 185493, 'title': np.str_('Roy Orbisons Greatest Hits'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.857556939125061}, {'iid': 175348, 'title': np.str_('Careless People'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.8370770812034607}, {'iid': 77088, 'title': np.str_('Hammered Dulcimer Christmas'), 'categories': 'CDs & Vinyl, Holiday & Wedding, Christmas', 'score': 0.8194761872291565}, {'iid': 12652, 'title': np.str_('The "Angry" Young Them!'), 'categories': 'CDs & Vinyl, Rock, Blues Rock', 'score': 0.8177226185798645}, {'iid': 191722, 'title': np.str_('Dancing Fantasy'), 'categories': 'CDs & Vinyl, Country, Bluegrass', 'score': 0.8117514848709106}, {'iid': 191392, 'title': np.str_('Millennium Collection - 20th Century Masters'), 'categories': 'CDs & Vinyl, Christian & Gospel, Pop & Contemporary', 'score': 0.8095672130584717}, {'iid': 196061, 'title': np.str_('Peso In My Pocket'), 'categories': 'CDs & Vinyl, Country', 'score': 0.7960558533668518}, {'iid': 110457, 'title': np.str_('Story of the Clash I'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk', 'score': 0.7820938229560852}, {'iid': 164686, 'title': np.str_('Grey Britain       explicit_lyrics'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk', 'score': 0.7810849547386169}, {'iid': 185782, 'title': np.str_('Wishbone Four'), 'categories': "CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10", 'score': 0.7703360319137573}, {'iid': 80100, 'title': np.str_('Distant Worlds IV: more music from FINAL FANTASY'), 'categories': 'CDs & Vinyl, Soundtracks', 'score': 0.7667213678359985}, {'iid': 217651, 'title': np.str_('Ghost Train The Studio B Sessions'), 'categories': 'CDs & Vinyl, Country, Bluegrass', 'score': 0.7653096318244934}, {'iid': 77414, 'title': np.str_('The Comeback Kid'), 'categories': 'CDs & Vinyl, Indie & Alternative, Alternative Rock', 'score': 0.7542975544929504}], [{'iid': 1331, 'title': np.str_('Coral Fang       Explicit Lyrics'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk', 'score': 0.854903519153595}, {'iid': 122938, 'title': np.str_('The Dave Edmunds Anthology 1968-1990'), 'categories': 'CDs & Vinyl, International Music, Europe, Britain & Ireland, Britain', 'score': 0.7666874527931213}, {'iid': 95724, 'title': np.str_('Colour the Small One'), 'categories': 'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock', 'score': 0.7661548256874084}, {'iid': 153634, 'title': np.str_('Serenity Suite: Music & Nature'), 'categories': 'CDs & Vinyl, Rock, Progressive, Electronic', 'score': 0.758841335773468}, {'iid': 41719, 'title': np.str_('Marching Orders'), 'categories': 'CDs & Vinyl, Reggae', 'score': 0.753349244594574}, {'iid': 185493, 'title': np.str_('Roy Orbisons Greatest Hits'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.716498613357544}, {'iid': 19884, 'title': np.str_('Encore'), 'categories': 'CDs & Vinyl, Christian & Gospel, Pop & Contemporary', 'score': 0.7025163173675537}, {'iid': 1542, 'title': np.str_('Get Closer'), 'categories': "CDs & Vinyl, Country, Today's Country", 'score': 0.6896149516105652}, {'iid': 242916, 'title': np.str_("Boys Don't Cry"), 'categories': 'CDs & Vinyl, Pop', 'score': 0.6552667021751404}, {'iid': 32882, 'title': np.str_('Gaither Gospel Series: The Isaacs Live From Norway'), 'categories': 'CDs & Vinyl, Christian & Gospel, Gospel, Southern', 'score': 0.6204848289489746}, {'iid': 95758, 'title': np.str_('Take What You Want'), 'categories': 'CDs & Vinyl, Metal', 'score': 0.613437294960022}, {'iid': 77088, 'title': np.str_('Hammered Dulcimer Christmas'), 'categories': 'CDs & Vinyl, Holiday & Wedding, Christmas', 'score': 0.5961393117904663}, {'iid': 110457, 'title': np.str_('Story of the Clash I'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk', 'score': 0.5720419883728027}, {'iid': 175348, 'title': np.str_('Careless People'), 'categories': 'CDs & Vinyl, Pop', 'score': 0.5664554238319397}, {'iid': 191392, 'title': np.str_('Millennium Collection - 20th Century Masters'), 'categories': 'CDs & Vinyl, Christian & Gospel, Pop & Contemporary', 'score': 0.5651916861534119}, {'iid': 116971, 'title': np.str_('Everything Is Possible: The Very Best of Living Colour'), 'categories': "CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10", 'score': 0.5651488900184631}, {'iid': 27910, 'title': np.str_('Legend, John : All of Me'), 'categories': 'CDs & Vinyl, Rap & Hip-Hop, Pop Rap', 'score': 0.5457369685173035}], [{'iid': 110457, 'title': np.str_('Story of the Clash I'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk', 'score': 1.1176230907440186}, {'iid': 175348, 'title': np.str_('Careless People'), 'categories': 'CDs & Vinyl, Pop', 'score': 1.0510196685791016}, {'iid': 139750, 'title': np.str_('Mendelssohn: The Complete String Quartets / Pacifica Quartet'), 'categories': 'CDs & Vinyl, Classical, Chamber Music', 'score': 1.0013443231582642}, {'iid': 1331, 'title': np.str_('Coral Fang       Explicit Lyrics'), 'categories': 'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk', 'score': 0.9239700436592102}, {'iid': 116421, 'title': np.str_('IN DIS LIFE'), 'categories': 'CDs & Vinyl, International Music, Pacific Islands, Hawaii', 'score': 0.8927935361862183}, {'iid': 218094, 'title': np.str_('Make Your Mark: Ultimate Playlist'), 'categories': "CDs & Vinyl, Children's Music, Disney", 'score': 0.8545542359352112}, {'iid': 32882, 'title': np.str_('Gaither Gospel Series: The Isaacs Live From Norway'), 'categories': 'CDs & Vinyl, Christian & Gospel, Gospel, Southern', 'score': 0.8426943421363831}, {'iid': 191722, 'title': np.str_('Dancing Fantasy'), 'categories': 'CDs & Vinyl, Country, Bluegrass', 'score': 0.8374431133270264}, {'iid': 155333, 'title': np.str_('Pastel Blues'), 'categories': 'CDs & Vinyl, Broadway & Vocalists, Cabaret', 'score': 0.7879119515419006}, {'iid': 165952, 'title': np.str_('Jon Secada - Greatest Hits'), 'categories': 'CDs & Vinyl, Latin Music, Latin Pop', 'score': 0.7749817967414856}, {'iid': 150255, 'title': np.str_('Hateful Eight Ost       explicit_lyrics'), 'categories': 'CDs & Vinyl, Soundtracks', 'score': 0.7719210982322693}, {'iid': 12652, 'title': np.str_('The "Angry" Young Them!'), 'categories': 'CDs & Vinyl, Rock, Blues Rock', 'score': 0.7689598798751831}, {'iid': 196061, 'title': np.str_('Peso In My Pocket'), 'categories': 'CDs & Vinyl, Country', 'score': 0.7619524598121643}]]

In [64]:
print("Top 50 recommendations for first 5 users:\n")

for i, (user_id, recs) in enumerate(user_recs.items()):
    if i >= 5:
        break
    print(f"user_id: {user_id}  top 50 is:")
    for rec in recs:
        print(f"  'iid': {rec['iid']}, 'title': {rec['title']}, 'categories': {rec['categories']}, 'score': {rec['score']}")
    print()

Top 50 recommendations for first 5 users:

user_id: 32  top 50 is:
  'iid': 170245, 'title': Of Vengeance & Violence, 'categories': CDs & Vinyl, Metal, Alternative Metal, 'score': 0.9593205451965332
  'iid': 95724, 'title': Colour the Small One, 'categories': CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, 'score': 0.9240134954452515
  'iid': 155333, 'title': Pastel Blues, 'categories': CDs & Vinyl, Broadway & Vocalists, Cabaret, 'score': 0.9088192582130432
  'iid': 185782, 'title': Wishbone Four, 'categories': CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10, 'score': 0.8685558438301086
  'iid': 185493, 'title': Roy Orbisons Greatest Hits, 'categories': CDs & Vinyl, Pop, 'score': 0.8253015875816345
  'iid': 1331, 'title': Coral Fang       Explicit Lyrics, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk, 'score': 0.8169475197792053
  'iid': 77088, 'title': Hammered Dulcimer Christmas, 'categories': CDs & Vinyl, Holiday & Wedding, Christmas, 'score': 0.7892606854438782
  'iid': 1322, 'title': On the Night - Live, 'categories': CDs & Vinyl, Today's Deals in Music, Classic Rock, Album-Oriented Rock (AOR), CDs $7 - $10, 'score': 0.766628086566925
  'iid': 191392, 'title': Millennium Collection - 20th Century Masters, 'categories': CDs & Vinyl, Christian & Gospel, Pop & Contemporary, 'score': 0.7593280673027039
  'iid': 110457, 'title': Story of the Clash I, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk, 'score': 0.7441343069076538
  'iid': 12652, 'title': The "Angry" Young Them!, 'categories': CDs & Vinyl, Rock, Blues Rock, 'score': 0.7407299876213074
  'iid': 76343, 'title': Eddy Duchin Story + Eddy Duchin Remembered, 'categories': CDs & Vinyl, Pop, Easy Listening, 'score': 0.6850771903991699
  'iid': 77414, 'title': The Comeback Kid, 'categories': CDs & Vinyl, Indie & Alternative, Alternative Rock, 'score': 0.6695731282234192
  'iid': 2019, 'title': Greatest Hits, Vol. 01, 'categories': CDs & Vinyl, Pop, Oldies, Doo Wop, 'score': 0.6692941784858704
  'iid': 34223, 'title': Greatest Hits, 'categories': CDs & Vinyl, Today's Deals in Music, Alternative Rock, Alternative General, CDs $7 - $10, 'score': 0.6344746351242065
  'iid': 102548, 'title': Hello Happiness, 'categories': CDs & Vinyl, R&B, Soul, Blue-Eyed Soul, 'score': 0.626410186290741
  'iid': 27066, 'title': St. Cecelia Mass, 'categories': CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Masses, 'score': 0.6263030767440796
  'iid': 32882, 'title': Gaither Gospel Series: The Isaacs Live From Norway, 'categories': CDs & Vinyl, Christian & Gospel, Gospel, Southern, 'score': 0.6153507828712463

user_id: 34  top 50 is:
  'iid': 95724, 'title': Colour the Small One, 'categories': CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, 'score': 1.179807424545288
  'iid': 191392, 'title': Millennium Collection - 20th Century Masters, 'categories': CDs & Vinyl, Christian & Gospel, Pop & Contemporary, 'score': 1.1531850099563599
  'iid': 155333, 'title': Pastel Blues, 'categories': CDs & Vinyl, Broadway & Vocalists, Cabaret, 'score': 1.1502381563186646
  'iid': 139750, 'title': Mendelssohn: The Complete String Quartets / Pacifica Quartet, 'categories': CDs & Vinyl, Classical, Chamber Music, 'score': 1.0161371231079102
  'iid': 120292, 'title': Scarred, 'categories': CDs & Vinyl, Folk, Contemporary Folk, 'score': 0.8742977976799011
  'iid': 185493, 'title': Roy Orbisons Greatest Hits, 'categories': CDs & Vinyl, Pop, 'score': 0.8704085946083069
  'iid': 175348, 'title': Careless People, 'categories': CDs & Vinyl, Pop, 'score': 0.8688889741897583
  'iid': 27066, 'title': St. Cecelia Mass, 'categories': CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Masses, 'score': 0.8585649132728577
  'iid': 12652, 'title': The "Angry" Young Them!, 'categories': CDs & Vinyl, Rock, Blues Rock, 'score': 0.8579466938972473
  'iid': 116971, 'title': Everything Is Possible: The Very Best of Living Colour, 'categories': CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10, 'score': 0.8436163663864136
  'iid': 15082, 'title': Blue Suede Shoes Set, 'categories': CDs & Vinyl, Pop, 'score': 0.7879559397697449
  'iid': 8803, 'title': Wicked Mans Rest, 'categories': CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, 'score': 0.7767699956893921
  'iid': 76840, 'title': Where Have All Flowers Gone: Songs of Pete Seeger, 'categories': CDs & Vinyl, Folk, British & Celtic Folk, British Folk, 'score': 0.7722450494766235
  'iid': 119659, 'title': Live It Up, 'categories': CDs & Vinyl, Pop, 'score': 0.7721186876296997
  'iid': 29930, 'title': Total Depravity, 'categories': CDs & Vinyl, Pop, 'score': 0.7690561413764954

user_id: 77  top 50 is:
  'iid': 95724, 'title': Colour the Small One, 'categories': CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, 'score': 1.0397413969039917
  'iid': 32882, 'title': Gaither Gospel Series: The Isaacs Live From Norway, 'categories': CDs & Vinyl, Christian & Gospel, Gospel, Southern, 'score': 0.9836426973342896
  'iid': 170245, 'title': Of Vengeance & Violence, 'categories': CDs & Vinyl, Metal, Alternative Metal, 'score': 0.9694384932518005
  'iid': 139750, 'title': Mendelssohn: The Complete String Quartets / Pacifica Quartet, 'categories': CDs & Vinyl, Classical, Chamber Music, 'score': 0.9677174091339111
  'iid': 155333, 'title': Pastel Blues, 'categories': CDs & Vinyl, Broadway & Vocalists, Cabaret, 'score': 0.9393640756607056
  'iid': 120292, 'title': Scarred, 'categories': CDs & Vinyl, Folk, Contemporary Folk, 'score': 0.8884671330451965
  'iid': 185493, 'title': Roy Orbisons Greatest Hits, 'categories': CDs & Vinyl, Pop, 'score': 0.857556939125061
  'iid': 175348, 'title': Careless People, 'categories': CDs & Vinyl, Pop, 'score': 0.8370770812034607
  'iid': 77088, 'title': Hammered Dulcimer Christmas, 'categories': CDs & Vinyl, Holiday & Wedding, Christmas, 'score': 0.8194761872291565
  'iid': 12652, 'title': The "Angry" Young Them!, 'categories': CDs & Vinyl, Rock, Blues Rock, 'score': 0.8177226185798645
  'iid': 191722, 'title': Dancing Fantasy, 'categories': CDs & Vinyl, Country, Bluegrass, 'score': 0.8117514848709106
  'iid': 191392, 'title': Millennium Collection - 20th Century Masters, 'categories': CDs & Vinyl, Christian & Gospel, Pop & Contemporary, 'score': 0.8095672130584717
  'iid': 196061, 'title': Peso In My Pocket, 'categories': CDs & Vinyl, Country, 'score': 0.7960558533668518
  'iid': 110457, 'title': Story of the Clash I, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk, 'score': 0.7820938229560852
  'iid': 164686, 'title': Grey Britain       explicit_lyrics, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk, 'score': 0.7810849547386169
  'iid': 185782, 'title': Wishbone Four, 'categories': CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10, 'score': 0.7703360319137573
  'iid': 80100, 'title': Distant Worlds IV: more music from FINAL FANTASY, 'categories': CDs & Vinyl, Soundtracks, 'score': 0.7667213678359985
  'iid': 217651, 'title': Ghost Train The Studio B Sessions, 'categories': CDs & Vinyl, Country, Bluegrass, 'score': 0.7653096318244934
  'iid': 77414, 'title': The Comeback Kid, 'categories': CDs & Vinyl, Indie & Alternative, Alternative Rock, 'score': 0.7542975544929504

user_id: 84  top 50 is:
  'iid': 1331, 'title': Coral Fang       Explicit Lyrics, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk, 'score': 0.854903519153595
  'iid': 122938, 'title': The Dave Edmunds Anthology 1968-1990, 'categories': CDs & Vinyl, International Music, Europe, Britain & Ireland, Britain, 'score': 0.7666874527931213
  'iid': 95724, 'title': Colour the Small One, 'categories': CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, 'score': 0.7661548256874084
  'iid': 153634, 'title': Serenity Suite: Music & Nature, 'categories': CDs & Vinyl, Rock, Progressive, Electronic, 'score': 0.758841335773468
  'iid': 41719, 'title': Marching Orders, 'categories': CDs & Vinyl, Reggae, 'score': 0.753349244594574
  'iid': 185493, 'title': Roy Orbisons Greatest Hits, 'categories': CDs & Vinyl, Pop, 'score': 0.716498613357544
  'iid': 19884, 'title': Encore, 'categories': CDs & Vinyl, Christian & Gospel, Pop & Contemporary, 'score': 0.7025163173675537
  'iid': 1542, 'title': Get Closer, 'categories': CDs & Vinyl, Country, Today's Country, 'score': 0.6896149516105652
  'iid': 242916, 'title': Boys Don't Cry, 'categories': CDs & Vinyl, Pop, 'score': 0.6552667021751404
  'iid': 32882, 'title': Gaither Gospel Series: The Isaacs Live From Norway, 'categories': CDs & Vinyl, Christian & Gospel, Gospel, Southern, 'score': 0.6204848289489746
  'iid': 95758, 'title': Take What You Want, 'categories': CDs & Vinyl, Metal, 'score': 0.613437294960022
  'iid': 77088, 'title': Hammered Dulcimer Christmas, 'categories': CDs & Vinyl, Holiday & Wedding, Christmas, 'score': 0.5961393117904663
  'iid': 110457, 'title': Story of the Clash I, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk, 'score': 0.5720419883728027
  'iid': 175348, 'title': Careless People, 'categories': CDs & Vinyl, Pop, 'score': 0.5664554238319397
  'iid': 191392, 'title': Millennium Collection - 20th Century Masters, 'categories': CDs & Vinyl, Christian & Gospel, Pop & Contemporary, 'score': 0.5651916861534119
  'iid': 116971, 'title': Everything Is Possible: The Very Best of Living Colour, 'categories': CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10, 'score': 0.5651488900184631
  'iid': 27910, 'title': Legend, John : All of Me, 'categories': CDs & Vinyl, Rap & Hip-Hop, Pop Rap, 'score': 0.5457369685173035

user_id: 95  top 50 is:
  'iid': 110457, 'title': Story of the Clash I, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, British Punk, 'score': 1.1176230907440186
  'iid': 175348, 'title': Careless People, 'categories': CDs & Vinyl, Pop, 'score': 1.0510196685791016
  'iid': 139750, 'title': Mendelssohn: The Complete String Quartets / Pacifica Quartet, 'categories': CDs & Vinyl, Classical, Chamber Music, 'score': 1.0013443231582642
  'iid': 1331, 'title': Coral Fang       Explicit Lyrics, 'categories': CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk, 'score': 0.9239700436592102
  'iid': 116421, 'title': IN DIS LIFE, 'categories': CDs & Vinyl, International Music, Pacific Islands, Hawaii, 'score': 0.8927935361862183
  'iid': 218094, 'title': Make Your Mark: Ultimate Playlist, 'categories': CDs & Vinyl, Children's Music, Disney, 'score': 0.8545542359352112
  'iid': 32882, 'title': Gaither Gospel Series: The Isaacs Live From Norway, 'categories': CDs & Vinyl, Christian & Gospel, Gospel, Southern, 'score': 0.8426943421363831
  'iid': 191722, 'title': Dancing Fantasy, 'categories': CDs & Vinyl, Country, Bluegrass, 'score': 0.8374431133270264
  'iid': 155333, 'title': Pastel Blues, 'categories': CDs & Vinyl, Broadway & Vocalists, Cabaret, 'score': 0.7879119515419006
  'iid': 165952, 'title': Jon Secada - Greatest Hits, 'categories': CDs & Vinyl, Latin Music, Latin Pop, 'score': 0.7749817967414856
  'iid': 150255, 'title': Hateful Eight Ost       explicit_lyrics, 'categories': CDs & Vinyl, Soundtracks, 'score': 0.7719210982322693
  'iid': 12652, 'title': The "Angry" Young Them!, 'categories': CDs & Vinyl, Rock, Blues Rock, 'score': 0.7689598798751831
  'iid': 196061, 'title': Peso In My Pocket, 'categories': CDs & Vinyl, Country, 'score': 0.7619524598121643

In [65]:
mappings = dataset.mapping()
print(f"Number of elements returned: {len(mappings)}")
print(f"Type of elements: {[type(m) for m in mappings]}")

Number of elements returned: 4
Type of elements: [<class 'dict'>, <class 'dict'>, <class 'dict'>, <class 'dict'>]

In [66]:
print("Users:", len(dataset.mapping()[0]), "Items:", len(dataset.mapping()[1]))

Users: 100000 Items: 100000

In [66]:
recs = get_top_k(model, dataset, train, user_id=1518328, k=5)
for item in recs:
    print(f"ID: {item['iid']}, Title: {item['title']}, Categories: {item['categories']}, Score: {item['score']:.3f}")
    
# recommendations = get_top_k(model, dataset, interactions, train, user_id=1, k=10)
# print("Top recommendations")
# for item in recommendations:
#     print(f"{item['title']} (score: {item['score']:.3f})")

ID: 2150, Title: Fool for the City, Categories: CDs & Vinyl, Classic Rock, Album-Oriented Rock (AOR), Score: 2.013
ID: 8617, Title: Gulag Orkestar, Categories: CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, Score: 1.998
ID: 3167, Title: Operation Mindcrime Lp (Original Issue), Categories: CDs & Vinyl, Rock, Progressive, Progressive Rock, Score: 1.956
ID: 2885, Title: Daytime Friends-The Best of Kenny Rogers, Categories: CDs & Vinyl, Country, Today's Country, Score: 1.876
ID: 6923, Title: Alternative Christmas Album / Various, Categories: CDs & Vinyl, Pop, Vocal Pop, Score: 1.793

In [67]:
recs = get_top_k(model, dataset, train, user_id=18628, k=5)
for item in recs:
    print(f"ID: {item['iid']}, Title: {item['title']}, Categories: {item['categories']}, Score_FM: {item['score']:.3f}")

ID: 18766, Title: Joe Pass: Portraits of Duke Ellington [ LP Vinyl ], Categories: CDs & Vinyl, Vinyl Store, Score_FM: 1.992
ID: 2150, Title: Fool for the City, Categories: CDs & Vinyl, Classic Rock, Album-Oriented Rock (AOR), Score_FM: 1.981
ID: 8617, Title: Gulag Orkestar, Categories: CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock, Score_FM: 1.935
ID: 2317, Title: Source Presents: Hip Hop Hits, Vol. 7       Clean Version, Categories: CDs & Vinyl, R&B, Soul, Score_FM: 1.848
ID: 2685, Title: Mizerable 2, Categories: CDs & Vinyl, International Music, Far East & Asia, Japan, Score_FM: 1.830

From this line

In [ ]:
# user_recs = {}
# for uid in train['uid'].unique():
#     recs = get_top_k(model, dataset, train, user_id=uid, k=50)
#     user_recs[uid]=recs

In [74]:
import chromadb
from chromadb.config import Settings

chroma_client = chromadb.Client(Settings(
    persist_directory="chroma_storage",  
    anonymized_telemetry=False
))

collection = chroma_client.get_or_create_collection("recommendations")

In [76]:
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm
import numpy as np
from sentence_transformers import SentenceTransformer
import uuid

model_embedding = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

def cast_metadata(metadata):
    return {
        k: (
            int(v) if isinstance(v, (np.integer,))
            else float(v) if isinstance(v, (np.floating,))
            else str(v) if isinstance(v, (list, dict))
            else v
        )
        for k, v in metadata.items()
    }

def prepare_data_for_insertion(user_recs):
    combined_texts, metadata_list, id_list = [], [], []

    for user_id, recs in user_recs.items():
        for rec in recs:
            text = f"Title: {rec['title']}. Categories: {rec['categories']}"
            metadata = cast_metadata({
                "user_id": str(user_id),
                "iid": rec['iid'],
                "title": rec['title'],
                "categories": rec['categories'],
                "cf_score": rec['score'],
                "combined_text": text
            })

            combined_texts.append(text)
            metadata_list.append(metadata)
            id_list.append(str(uuid.uuid4()))

    return combined_texts, metadata_list, id_list

def batch_insert_with_parallelism(model, collection, user_recs, batch_size=512, max_workers=4):
    texts, metadatas, ids = prepare_data_for_insertion(user_recs)

    # Batch encode using SentenceTransformer
    print("Encoding embeddings...")
    embeddings = model.encode(texts, batch_size=128, show_progress_bar=True)

    # Split into batches
    total = len(texts)
    batches = range(0, total, batch_size)

    print("Inserting into ChromaDB...")
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in tqdm(batches, desc="Inserting batches"):
            futures.append(executor.submit(
                collection.add,
                documents=texts[i:i+batch_size],
                embeddings=embeddings[i:i+batch_size],
                metadatas=metadatas[i:i+batch_size],
                ids=ids[i:i+batch_size]
            ))

        for f in futures:
            f.result()

In [77]:
def query_recommendations_by_text(user_query: str, user_id: str, model, collection, top_k=10):
    query_embedding = model.encode(user_query).tolist()

    # query ChromaDB with user filter
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        where={"user_id": {"$eq": str(user_id)}},
        include=["metadatas", "documents", "distances"]
    )

    retrieved = []
    if results["metadatas"] and results["metadatas"][0]:
        for i in range(len(results["ids"][0])):
            meta = results["metadatas"][0][i]
            retrieved.append({
                "iid": meta["iid"],
                "title": meta["title"],
                "categories": meta["categories"],
                "cf_score": meta["cf_score"],
                "similarity_score": 1 - results["distances"][0][i]
            })

    return retrieved

In [80]:
print("Running insert...")
batch_insert_with_parallelism(model_embedding, collection, user_recs)

Running insert...
Encoding embeddings...

Batches:   0%|          | 0/12388 [00:00<?, ?it/s]

Inserting into ChromaDB...

Inserting batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 3097/3097 [00:01<00:00, 2252.31it/s]

In [81]:
collection.count()

1585614

In [103]:
user_query = "recommend some love songs"
beauty_users = sampled_train[sampled_train['categories'].str.contains("beauty", case=False, na=False)]['uid'].unique()

beauty_user_ids = [uid for uid in beauty_users if uid in user_recs]
user_id = beauty_user_ids[0] if beauty_user_ids else next(iter(user_recs.keys()))


results = query_recommendations_by_text(user_query, str(user_id), model_embedding, collection, top_k=10)

for r in results:
    print(f"Title: {r['title']}, Categories: {r['categories']}, Similarity: {r['similarity_score']:.3f}, CF Score: {r['cf_score']:.3f}")

In [85]:
peeked = collection.peek()

print("Number of documents in peek:", len(peeked["ids"]))

if "metadatas" in peeked and len(peeked["metadatas"]) > 0:
    print("Example user_id in ChromaDB metadata:")
    print(peeked["metadatas"][0]["user_id"]) 
else:
    print("No metadata found in peek.")

Number of documents in peek: 10
Example user_id in ChromaDB metadata:
592

In [86]:
print("Chosen user_id:", user_id)
print("Type:", type(user_id))

Chosen user_id:
32
Type: <class 'numpy.int64'>

In [89]:
user_id = peeked["metadatas"][0]["user_id"]
results = query_recommendations_by_text(user_query, str(user_id), model_embedding, collection, top_k=10)

In [91]:
user_query = " "
user_id = peeked["metadatas"][0]["user_id"]
results = query_recommendations_by_text(user_query, user_id, model_embedding, collection, top_k=10)
print("user_id:", user_id)
print("Type of user_id:", type(user_id))

if not results:
    print("No recommendations found.")
else:
    print(f"Top {len(results)} results for user_id: {user_id}")
    for r in results:
        print(f"Title: {r['title']}, Categories: {r['categories']}, Similarity: {r['similarity_score']:.3f}, CF Score: {r['cf_score']:.3f}")

user_id: 592
Type of user_id: <class 'str'>
No recommendations found.

In [93]:
matches = collection.get(limit=1, include=["metadatas", "documents"])
sample_meta = matches["metadatas"][0]

print("Sample metadata:", sample_meta)
print("Stored user_id:", sample_meta.get("user_id"), "Type:", type(sample_meta.get("user_id")))

Sample metadata: {'user_id': '592', 'iid': 191722, 'title': 'Dancing Fantasy', 'categories': 'CDs & Vinyl, Country, Bluegrass', 'cf_score': 0.7575958371162415, 'combined_text': 'Title: Dancing Fantasy. Categories: CDs & Vinyl, Country, Bluegrass'}
Stored user_id: 592 Type: <class 'str'>

In [97]:
matches = collection.get(where={"user_id": {"$eq": "592"}}, include=["metadatas"])
print("Number of records for user_id='592':", len(matches["ids"]))

Number of records for user_id='592': 15

In [99]:
results = collection.query(
    query_embeddings=[model_embedding.encode(user_query).tolist()],
    n_results=10,
    include=["metadatas", "documents", "distances"]
)
print(results)

{'ids': [['e6bcc6a1-a1f4-43a2-9042-77680d7598dd', 'f6528e0d-3a11-4631-9018-063b1124aa69', '97b5b024-00e7-4330-b11e-0640439a1cbb', '6098c7d4-9078-4f1e-8573-3fcb2f8d677c', '8ec5a681-583f-4394-9a84-8ea46dff1e29', '3b49a8e6-6ca3-4074-a1f9-7642fac71d12', '0d7522d9-d4b5-4d48-af6b-f8e44f400577', '8939ed17-42c8-463a-a121-783e2e8f4b86', '621c0122-4118-4d62-9678-b7aa4add59a9', '0c7af11e-70f7-4134-b2ad-ea29a69bde7a']], 'embeddings': None, 'documents': [['Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'categories': 'CDs & Vinyl, Jazz', 'user_id': '1347602', 'cf_score': 0.7624362111091614, 'iid': 72863, 'title': 'Love Will Find a Way'}, {'iid': 72863, 'title': 'Love Will Find a Way', 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'categories': 'CDs & Vinyl, Jazz', 'user_id': '1347734', 'cf_score': 0.7220661044120789}, {'user_id': '1347105', 'iid': 72863, 'categories': 'CDs & Vinyl, Jazz', 'cf_score': 0.7244486808776855, 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'title': 'Love Will Find a Way'}, {'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'categories': 'CDs & Vinyl, Jazz', 'title': 'Love Will Find a Way', 'user_id': '1347218', 'cf_score': 0.8262364268302917, 'iid': 72863}, {'title': 'Love Will Find a Way', 'categories': 'CDs & Vinyl, Jazz', 'iid': 72863, 'cf_score': 0.7581400275230408, 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'user_id': '1347237'}, {'iid': 72863, 'user_id': '1347257', 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'categories': 'CDs & Vinyl, Jazz', 'title': 'Love Will Find a Way', 'cf_score': 0.7586832046508789}, {'cf_score': 0.7975409626960754, 'title': 'Love Will Find a Way', 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'categories': 'CDs & Vinyl, Jazz', 'user_id': '1347341', 'iid': 72863}, {'title': 'Love Will Find a Way', 'cf_score': 0.7298668622970581, 'categories': 'CDs & Vinyl, Jazz', 'iid': 72863, 'user_id': '1347823', 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz'}, {'cf_score': 0.7629309296607971, 'user_id': '1348103', 'iid': 72863, 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'title': 'Love Will Find a Way', 'categories': 'CDs & Vinyl, Jazz'}, {'iid': 72863, 'title': 'Love Will Find a Way', 'combined_text': 'Title: Love Will Find a Way. Categories: CDs & Vinyl, Jazz', 'categories': 'CDs & Vinyl, Jazz', 'cf_score': 0.7635536193847656, 'user_id': '1348148'}]], 'distances': [[1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534, 1.6018322706222534]]}

In [104]:
user_query = "recommend some different love songs"

# Run the raw query without filtering by user_id
query_embedding = model_embedding.encode(user_query).tolist()

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=10,
    include=["metadatas", "documents", "distances"]
)

print(f"\n User query: \"{user_query}\"\n")

for i, meta in enumerate(results["metadatas"][0]):
    cosine_similarity = 1 - results["distances"][0][i]
    print(f"Result #{i+1}")
    print(f"  User ID: {meta['user_id']}")
    print(f"  Item ID: {meta['iid']}")
    print(f"  Title: {meta['title']}")
    print(f"  Categories: {meta['categories']}")
    print(f"  CF Score: {meta['cf_score']:.3f}")
    print(f"  Cosine Similarity: {cosine_similarity:.3f}")
    print("-" * 50)

 User query: "recommend some different love songs"

Result #1
  User ID: 46214
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.442
  Cosine Similarity: -0.155
--------------------------------------------------
Result #2
  User ID: 46701
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.812
  Cosine Similarity: -0.155
--------------------------------------------------
Result #3
  User ID: 46720
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.931
  Cosine Similarity: -0.155
--------------------------------------------------
Result #4
  User ID: 47080
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.961
  Cosine Similarity: -0.155
--------------------------------------------------
Result #5
  User ID: 47100
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.695
  Cosine Similarity: -0.155
--------------------------------------------------
Result #6
  User ID: 47106
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.759
  Cosine Similarity: -0.155
--------------------------------------------------
Result #7
  User ID: 47523
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 1.060
  Cosine Similarity: -0.155
--------------------------------------------------
Result #8
  User ID: 47537
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.969
  Cosine Similarity: -0.155
--------------------------------------------------
Result #9
  User ID: 48134
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 1.057
  Cosine Similarity: -0.155
--------------------------------------------------
Result #10
  User ID: 48747
  Item ID: 1542
  Title: Get Closer
  Categories: CDs & Vinyl, Country, Today's Country
  CF Score: 0.802
  Cosine Similarity: -0.155
--------------------------------------------------

In [73]:
import os
import pinecone
from pinecone import Pinecone, ServerlessSpec
from sentence_transformers import SentenceTransformer
from langchain.text_splitter import RecursiveCharacterTextSplitter

model_embeddings = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)

In [75]:
def batch_query_user_recommendations(user_recs, model, collection, top_k=10):
    queries = []
    user_ids = []

    for user_id, recs in user_recs.items():
        if recs:
            top_rec = recs[0]
            query_text = f"Title: {top_rec['title']}. Categories: {top_rec['categories']}"
            queries.append(query_text)
            user_ids.append(str(user_id))

    query_embeddings = model.encode(queries, batch_size=128, show_progress_bar=True)

    result_dict = {}

    for i in tqdm(range(len(user_ids)), desc="Querying users"):
        results = collection.query(
            query_embeddings=[query_embeddings[i]],
            n_results=top_k,
            where={"user_id": {"$eq": user_ids[i]}},
            include=["metadatas", "documents", "distances"]
        )

        if results and results["metadatas"][0]:
            result_dict[user_ids[i]] = [
                {
                    "iid": meta["iid"],
                    "title": meta["title"],
                    "categories": meta["categories"],
                    "cf_score": meta["cf_score"],
                    "similarity_score": 1 - dist
                }
                for meta, dist in zip(results["metadatas"][0], results["distances"][0])
            ]

    return result_dict

In [ ]:
def prep_docs_pinecone(user_id, recs):
    docs = []
    ids = []
    metadatas = []

    for cand in recs:
        combined_text = f"Title: {cand['title']}. Categories: {cand['categories']}"
        chunks = text_splitter.split_text(combined_text)

        for i, chunk in enumerate(chunks):
            chunk_id = f"{item['iid']}_{i}"

            meta_data = {
                "iid": cand['iid'],
                "title": cand['title'],
                "categories": cand['categories'],
                "combined_text": cand['combined_text"],
                "fm_score": cand['score'],
                "chunk": cand['chunk']
            }

            ids.append(chunk_id)
            docs.append(chunks)
            metadatas.append(meta_data)
            
    return ids, docs, metadatas

In [81]:
os.environ["PINECONE_API_KEY"]= "pcsk_6mDSEp_B8EBirbyCBt5wUsw8QDFrwp8Z1jeyGvjytLpabnV2my2tJSZ1eNgCYt5xmcwgzk"
pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"])

# project_info = pc.describe_project()
# print("Allowed cloud+regions:", project_info.cloud_region_defaults)

# Create index if not exists
index_name = "recommendations-index"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=768,
        metric="cosine"     
    )

index = pc.Index(index_name)

# pinecone.init(api_key="pcsk_6mDSEp_B8EBirbyCBt5wUsw8QDFrwp8Z1jeyGvjytLpabnV2my2tJSZ1eNgCYt5xmcwgzk", environment="YOUR_ENVIRONMENT")
# index_name = "recommendations-index"

# if index_name not in pinecone.list_indexes():
#     pinecone.create_index(name=index_name,
#                           dimension=768,
#                           metric="cosine")

# index = pinecone.Index(index_name)

PINECONE_API_KEY_ID = "pcsk_6mDSEp_B8EBirbyCBt5wUsw8QDFrwp8Z1jeyGvjytLpabnV2my2tJSZ1eNgCYt5xmcwgzk"

TypeError: Pinecone.create_index() missing 1 required positional argument: 'spec'

In [ ]:
ids, docs, metadatas = prep_docs_pinecone(train['uid'], recs)

In [82]:
collection.count()

0

In [ ]:
batch_size = 32
for i in range(0, len(docs), batch_size):
    batch_ids = ids[i:i+batch_size]
    batch_docs = docs[i:i+batch_size]
    batch_metas = metadatas[i:i+batch_size]

    embeddings = model.encode(batch_docs)
    vectors = []

    for id, embedding, meta in zip(batch_ids, embeddings, batch_meatas):
        vectors.append((id, embedding.tolist(), meta))

    index.upsert(vectors = vectors)

In [ ]:
def get_search_result(user_query, index, model, k):
    query_embedding = model.encode(user_query).to_list()

    result = index.query(vector=query_embedding,
                        topk=k,
                        include_metadata=True,
                        include_values=False)
    search_results = []
    for match in search_results:
        metadata = match['metadata']
        search_results.append({
            "iid": metadata['iid'],
            "title": metadata['title'],
            "categories": metadata['categories'],
            "combined_text": metadata['combined_text'],
            "fm_score": metadata['fm_score'],
            "similarity_score": metadata['score']
        })

    return search_results

In [79]:
user_query = "beauty magazine that can provide beauty tips"
beauty_users = sampled_train[sampled_train['categories'].str.contains("beauty", case=False, na=False)]['uid'].unique()

beauty_user_ids = [uid for uid in beauty_users if uid in user_recs]
user_id = beauty_user_ids[0] if beauty_user_ids else next(iter(user_recs.keys()))


results = query_recommendations_by_text(user_query, user_id, model_embedding, collection, top_k=10)

for r in results:
    print(f"Title: {r['title']}, Categories: {r['categories']}, Similarity: {r['similarity_score']:.3f}, CF Score: {r['cf_score']:.3f}")

In [81]:
for r in results:
    print(f"Title: {r['title']}, Categories: {r['categories']}, Similarity: {r['similarity_score']:.3f}, CF Score: {r['cf_score']:.3f}")

In [80]:
print(results)

[]

In [ ]:
from sentence_transformers import SentenceTransformer
import uuid

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

def cast_metadata(metadata):
    return {
        k: (
            int(v) if isinstance(v, (np.integer,))
            else float(v) if isinstance(v, (np.floating,))
            else str(v) if isinstance(v, (list, dict))
            else v
        )
        for k, v in metadata.items()
    }

for user_id, recs in user_recs.items():
    for rec in recs:
        combined_text = f"Title: {rec['title']}. Categories: {rec['categories']}"
        embedding = model.encode(combined_text).tolist()

        metadata = cast_metadata({
            "user_id": str(user_id),
            "iid": rec['iid'],
            "title": rec['title'],
            "categories": rec['categories'],
            "cf_score": rec['score'],
            "combined_text": combined_text
        })

        collection.add(
            documents=[combined_text],
            embeddings=[embedding],
            ids=[str(uuid.uuid4())],
            metadatas=[metadata]
        )

In [ ]:
def query_user_recommendations(user_id, top_k=10):
    # Use one of the top LightFM items for this user to build the query
    # You can also use a user profile embedding if available
    top_rec = user_recs[user_id][0]  # or some average over top recs
    query_text = f"Title: {top_rec['title']}. Categories: {top_rec['categories']}"
    query_embedding = model.encode(query_text).tolist()

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        where={"user_id": {"$eq": str(user_id)}},  # Optional: filter only this user's candidates
        include=["metadatas", "documents", "distances"]
    )

    # Combine results into a list of dicts
    retrieved = []
    for i in range(len(results["ids"][0])):
        meta = results["metadatas"][0][i]
        retrieved.append({
            "iid": meta["iid"],
            "title": meta["title"],
            "categories": meta["categories"],
            "cf_score": meta["cf_score"],
            "similarity_score": 1 - results["distances"][0][i],  # Convert cosine distance to similarity
        })

    return retrieved

In [ ]:
print(train[['uid', 'iid', 'title']].head())
print(f"Unique users: {train['uid'].nunique()}")
print(f"Unique items: {train['iid'].nunique()}")

In [ ]:
small_train = train.head(1000)  # Test with smaller dataset
model, dataset, _ = fit_and_train(small_train)
recs = get_top_k(model, dataset, small_train, user_id=1, k=3)

In [ ]:
# user_id_encoder = dict(zip(merged_df['user_id_encoded'], merged_df['user_id']))
recs_dict = {user_id: get_top_k(model, dataset, train, user_id, k=50) for user_id in train['uid'].unique()}

In [ ]:
def get_purchase_history(merged_df, user_id, k):
    user_hist = merged_df[merged_df['user_id_encoded']==user_id]
    user_hist_sorted = user_hist.sort_values(by='timestamp', ascending=False)
    recent_purchase = user_hist_sorted[['asin', 'title_meta', 'description', 'combined_text']].head(k)
    return recent_purchase

def get_like_items(merged_df, user_id):
    like_items = merged_df[(merged_df['user_id_encoded']==user_id) & (merged_df['like']==True)].sort_values(by='timestamp', ascending=False)
    like_items = like_items[['asin', 'title_meta', 'description']].iloc[:10]
    return like_items

def get_dislike_items(merged_df, user_id):
    dislike_items = merged_df[(merged_df['user_id_encoded']==user_id) & (merged_df['like']==False)].sort_values(by='timestamp', ascending=False)
    dislike_items = dislike_items[['asin', 'title_meta', 'description']].iloc[:10]
    return like_items

In [ ]:
def evaluate_recall(model, train_interactions, test_interactions, k):
    precision= precision_at_k(model, test_interactions, train_interactions=train_interactions, k=k).mean()
    recall= recall_at_k(model, test_interactions, train_interactions=train_interactions, k=k).mean()
    auc= auc_score(model, test_interactions, train_interactions=train_interactions).mean()
    return precision, recall, auc

eval_metrics = evaluate_recall(model, train_interactions, test_interactions, k=50)

In [ ]:
def get_top_k(model, dataset, merged_df, user_id, k):
    n_users, n_items = dataset.interactions_shape()

    user_ids = np.full(n_items, user_id)  # or use np.repeat(user_id, n_items)
    # item_ids = np.arange(n_items)
    interacted_items = set(merged_df[merged_df['user_id_encoded']==user_id]['asin_encoded'])

    scores = model.predict(user_ids, np.arange(n_items))
    scores[list(interacted_items)] = -np.inf

    top_items_encoded = np.argsort(-scores)[:k]
    asin_info = dict(zip(merged_df['asin_encoded'], zip(merged_df['asin'], merged_df['title_meta'], merged_df['combined_text'])))
    recs = [asin_info[item] for item in top_items_encoded if item in asin_info]
    return recs

# user_id_encoder = dict(zip(merged_df['user_id_encoded'], merged_df['user_id']))
recs_dict = {user_id: get_top_k(model, dataset, merged_df, user_id, k=50) for user_id in merged_df['user_id_encoded'].unique()}

def get_recs(user_id):
    return recs_dict.get(user_id, [])

In [ ]:
user_id_test = merged_df['user_id_encoded'].iloc[8]
recent_purchases = get_purchase_history(merged_df, user_id_test, k=10)
like_items = get_like_items(merged_df, user_id_test)
dislike_items = get_dislike_items(merged_df, user_id_test)
top_k_recs= get_recs(user_id_test)

In [ ]:
# save
save_path = "../../data/amazon"

save_in_chunks(train, os.path.join(save_path, "train_amazon.pkl"), chunk_size=1000)
save_in_chunks(val, os.path.join(save_path, "val_amazon.pkl"), chunk_size=1000)
save_in_chunks(test, os.path.join(save_path, "test_amazon.pkl"), chunk_size=1000)

Saved 0 rows. Current memory usage: 970.27 MB
Saved 10000 rows. Current memory usage: 833.91 MB
Saved 20000 rows. Current memory usage: 827.78 MB
Saved 30000 rows. Current memory usage: 792.19 MB
Saved 40000 rows. Current memory usage: 799.44 MB
Saved 50000 rows. Current memory usage: 808.91 MB
Saved 60000 rows. Current memory usage: 831.64 MB
Saved 70000 rows. Current memory usage: 921.38 MB
Saved 80000 rows. Current memory usage: 957.84 MB
Saved 90000 rows. Current memory usage: 993.12 MB
Saved 100000 rows. Current memory usage: 1023.00 MB
Saved 110000 rows. Current memory usage: 1055.94 MB
Saved 120000 rows. Current memory usage: 1088.94 MB
Saved 130000 rows. Current memory usage: 1046.52 MB
Saved 140000 rows. Current memory usage: 1058.25 MB
Saved 150000 rows. Current memory usage: 1058.50 MB
Saved 160000 rows. Current memory usage: 1084.78 MB
Saved 170000 rows. Current memory usage: 1073.72 MB
Saved 180000 rows. Current memory usage: 1103.55 MB
Saved 190000 rows. Current memory usage: 1125.89 MB
Saved 200000 rows. Current memory usage: 1150.20 MB
Saved 210000 rows. Current memory usage: 1177.42 MB
Saved 220000 rows. Current memory usage: 1197.81 MB
Saved 230000 rows. Current memory usage: 1217.53 MB
Saved 240000 rows. Current memory usage: 1241.52 MB
Saved 250000 rows. Current memory usage: 1269.33 MB
Saved 260000 rows. Current memory usage: 1295.58 MB
Saved 270000 rows. Current memory usage: 1317.50 MB
Saved 280000 rows. Current memory usage: 1339.12 MB
Saved 290000 rows. Current memory usage: 1361.31 MB
Saved 300000 rows. Current memory usage: 1383.50 MB
Saved 310000 rows. Current memory usage: 1405.52 MB
Saved 320000 rows. Current memory usage: 1423.94 MB
Saved 330000 rows. Current memory usage: 1442.38 MB
Saved 340000 rows. Current memory usage: 1463.72 MB
Saved 350000 rows. Current memory usage: 1484.05 MB
Saved 360000 rows. Current memory usage: 1502.25 MB
Saved 370000 rows. Current memory usage: 1521.31 MB
Saved 380000 rows. Current memory usage: 1541.50 MB
Saved 390000 rows. Current memory usage: 1555.91 MB
Saved 400000 rows. Current memory usage: 1577.39 MB
Saved 410000 rows. Current memory usage: 1594.23 MB
Saved 420000 rows. Current memory usage: 1613.92 MB
Saved 430000 rows. Current memory usage: 1625.95 MB
Saved 440000 rows. Current memory usage: 1640.22 MB
Saved 450000 rows. Current memory usage: 1657.16 MB
Saved 460000 rows. Current memory usage: 1679.28 MB
Saved 470000 rows. Current memory usage: 1691.83 MB
Saved 480000 rows. Current memory usage: 1706.05 MB
Saved 490000 rows. Current memory usage: 1723.17 MB
Saved 500000 rows. Current memory usage: 1737.02 MB
Saved 510000 rows. Current memory usage: 1735.44 MB
Saved 520000 rows. Current memory usage: 1736.33 MB
Saved 530000 rows. Current memory usage: 1724.03 MB
Saved 540000 rows. Current memory usage: 1745.08 MB
Saved 550000 rows. Current memory usage: 1764.52 MB
Saved 560000 rows. Current memory usage: 1781.52 MB
Saved 570000 rows. Current memory usage: 1751.58 MB
Saved 580000 rows. Current memory usage: 1767.72 MB
Saved 590000 rows. Current memory usage: 1783.67 MB
Saved 600000 rows. Current memory usage: 1804.02 MB
Saved 610000 rows. Current memory usage: 1793.64 MB
Saved 620000 rows. Current memory usage: 1812.23 MB
Saved 630000 rows. Current memory usage: 1782.91 MB
Saved 640000 rows. Current memory usage: 1797.77 MB
Saved 650000 rows. Current memory usage: 1813.59 MB
Saved 660000 rows. Current memory usage: 1827.94 MB
Saved 670000 rows. Current memory usage: 1808.06 MB
Saved 680000 rows. Current memory usage: 1823.16 MB
Saved 690000 rows. Current memory usage: 1837.00 MB
Saved 700000 rows. Current memory usage: 1851.44 MB
Saved 710000 rows. Current memory usage: 1865.95 MB
Saved 720000 rows. Current memory usage: 1835.20 MB
Saved 730000 rows. Current memory usage: 1849.70 MB
Saved 740000 rows. Current memory usage: 1845.47 MB
Saved 750000 rows. Current memory usage: 1859.06 MB
Saved 760000 rows. Current memory usage: 1873.03 MB
Saved 770000 rows. Current memory usage: 1880.67 MB
Saved 780000 rows. Current memory usage: 1891.75 MB
Saved 790000 rows. Current memory usage: 1869.03 MB
Saved 800000 rows. Current memory usage: 1884.02 MB
Saved 810000 rows. Current memory usage: 1896.77 MB
Saved 820000 rows. Current memory usage: 1910.06 MB
Saved 830000 rows. Current memory usage: 1923.86 MB
Saved 840000 rows. Current memory usage: 1895.09 MB
Saved 850000 rows. Current memory usage: 1908.78 MB
Saved 860000 rows. Current memory usage: 1922.41 MB
Saved 870000 rows. Current memory usage: 1901.33 MB
Saved 880000 rows. Current memory usage: 1914.42 MB
Saved 890000 rows. Current memory usage: 1891.30 MB
Saved 900000 rows. Current memory usage: 1885.84 MB
Saved 910000 rows. Current memory usage: 1898.97 MB
Saved 920000 rows. Current memory usage: 1911.95 MB
Saved 930000 rows. Current memory usage: 1924.84 MB
Saved 940000 rows. Current memory usage: 1889.92 MB
Saved 950000 rows. Current memory usage: 1903.80 MB
Saved 960000 rows. Current memory usage: 1915.95 MB
Saved 970000 rows. Current memory usage: 1875.14 MB
Saved 980000 rows. Current memory usage: 1888.36 MB
Saved 990000 rows. Current memory usage: 1901.12 MB
Saved 1000000 rows. Current memory usage: 1843.92 MB
Saved 1010000 rows. Current memory usage: 1856.81 MB
Saved 1020000 rows. Current memory usage: 1869.05 MB
Saved 1030000 rows. Current memory usage: 1884.27 MB
Saved 1040000 rows. Current memory usage: 1895.33 MB
Saved 1050000 rows. Current memory usage: 1861.09 MB
Saved 1060000 rows. Current memory usage: 1873.34 MB
Saved 1070000 rows. Current memory usage: 1817.95 MB
Saved 1080000 rows. Current memory usage: 1830.17 MB
Saved 1090000 rows. Current memory usage: 1799.56 MB
Saved 1100000 rows. Current memory usage: 1811.97 MB
Saved 1110000 rows. Current memory usage: 1824.16 MB
Saved 1120000 rows. Current memory usage: 1836.08 MB
Saved 1130000 rows. Current memory usage: 1848.48 MB
Saved 1140000 rows. Current memory usage: 1783.02 MB
Saved 1150000 rows. Current memory usage: 1795.47 MB
Saved 1160000 rows. Current memory usage: 1807.52 MB
Saved 1170000 rows. Current memory usage: 1819.94 MB
Saved 1180000 rows. Current memory usage: 1831.86 MB
Saved 1190000 rows. Current memory usage: 1784.30 MB
Saved 1200000 rows. Current memory usage: 1796.25 MB
Saved 1210000 rows. Current memory usage: 1807.77 MB
Saved 1220000 rows. Current memory usage: 1813.02 MB
Saved 1230000 rows. Current memory usage: 1824.81 MB
Saved 1240000 rows. Current memory usage: 1763.28 MB
Saved 1250000 rows. Current memory usage: 1774.80 MB
Saved 1260000 rows. Current memory usage: 1786.64 MB
Saved 1270000 rows. Current memory usage: 1798.80 MB
Saved 1280000 rows. Current memory usage: 1810.89 MB
Saved 1290000 rows. Current memory usage: 1814.20 MB
Saved 1300000 rows. Current memory usage: 1772.84 MB
Saved 1310000 rows. Current memory usage: 1674.02 MB
Saved 1320000 rows. Current memory usage: 1680.67 MB
Saved 1330000 rows. Current memory usage: 1692.31 MB
Saved 1340000 rows. Current memory usage: 1704.80 MB
Saved 1350000 rows. Current memory usage: 1704.67 MB
Saved 1360000 rows. Current memory usage: 1716.38 MB
Saved 1370000 rows. Current memory usage: 1729.36 MB
Saved 1380000 rows. Current memory usage: 1741.20 MB
Saved 1390000 rows. Current memory usage: 1752.88 MB
Saved 1400000 rows. Current memory usage: 1764.31 MB
Saved 1410000 rows. Current memory usage: 1776.36 MB
Saved 1420000 rows. Current memory usage: 1787.56 MB
Saved 1430000 rows. Current memory usage: 1799.45 MB
Saved 1440000 rows. Current memory usage: 1810.91 MB
Saved 1450000 rows. Current memory usage: 1750.94 MB
Saved 1460000 rows. Current memory usage: 1762.12 MB
Saved 1470000 rows. Current memory usage: 1773.00 MB
Saved 1480000 rows. Current memory usage: 1784.33 MB
Saved 1490000 rows. Current memory usage: 1796.02 MB
Saved 1500000 rows. Current memory usage: 1800.16 MB
Saved 1510000 rows. Current memory usage: 1811.66 MB
Saved 1520000 rows. Current memory usage: 1822.83 MB
Saved 1530000 rows. Current memory usage: 1833.66 MB
Saved 1540000 rows. Current memory usage: 1845.31 MB
Saved 1550000 rows. Current memory usage: 1856.16 MB
Saved 1560000 rows. Current memory usage: 1810.20 MB
Saved 1570000 rows. Current memory usage: 1822.39 MB
Saved 1580000 rows. Current memory usage: 1833.62 MB
Saved 1590000 rows. Current memory usage: 1844.66 MB
Saved 1600000 rows. Current memory usage: 1855.98 MB
Saved 1610000 rows. Current memory usage: 1866.94 MB
Saved 1620000 rows. Current memory usage: 1868.75 MB
Saved 1630000 rows. Current memory usage: 1879.84 MB
Saved 1640000 rows. Current memory usage: 1861.62 MB
Saved 1650000 rows. Current memory usage: 1874.12 MB
Saved 1660000 rows. Current memory usage: 1884.88 MB
Saved 1670000 rows. Current memory usage: 1895.30 MB
Saved 1680000 rows. Current memory usage: 1906.66 MB
Saved 1690000 rows. Current memory usage: 1888.91 MB
Saved 1700000 rows. Current memory usage: 1899.86 MB
Saved 1710000 rows. Current memory usage: 1910.58 MB
Saved 1720000 rows. Current memory usage: 1921.30 MB
Saved 1730000 rows. Current memory usage: 1888.25 MB
Saved 1740000 rows. Current memory usage: 1899.38 MB
Saved 1750000 rows. Current memory usage: 1853.36 MB
Saved 1760000 rows. Current memory usage: 1864.39 MB
Saved 1770000 rows. Current memory usage: 1875.20 MB
Saved 1780000 rows. Current memory usage: 1886.03 MB
Saved 1790000 rows. Current memory usage: 1897.28 MB
Saved 1800000 rows. Current memory usage: 1908.20 MB
Saved 1810000 rows. Current memory usage: 1853.02 MB
Saved 1820000 rows. Current memory usage: 1863.97 MB
Saved 1830000 rows. Current memory usage: 1874.75 MB
Saved 1840000 rows. Current memory usage: 1885.66 MB
Saved 1850000 rows. Current memory usage: 1864.36 MB
Saved 1860000 rows. Current memory usage: 1875.70 MB
Saved 1870000 rows. Current memory usage: 1886.52 MB
Saved 1880000 rows. Current memory usage: 1897.36 MB
Saved 1890000 rows. Current memory usage: 1908.41 MB
Saved 1900000 rows. Current memory usage: 1858.66 MB
Saved 1910000 rows. Current memory usage: 1869.27 MB
Saved 1920000 rows. Current memory usage: 1854.94 MB
Saved 1930000 rows. Current memory usage: 1865.58 MB
Saved 1940000 rows. Current memory usage: 1825.97 MB
Saved 1950000 rows. Current memory usage: 1836.78 MB
Saved 1960000 rows. Current memory usage: 1847.61 MB
Saved 1970000 rows. Current memory usage: 1853.48 MB
Saved 1980000 rows. Current memory usage: 1864.19 MB
Saved 1990000 rows. Current memory usage: 1874.44 MB
Saved 2000000 rows. Current memory usage: 1806.62 MB
Saved 2010000 rows. Current memory usage: 1818.86 MB
Saved 2020000 rows. Current memory usage: 1829.41 MB
Saved 2030000 rows. Current memory usage: 1806.84 MB
Saved 2040000 rows. Current memory usage: 1817.47 MB
Saved 2050000 rows. Current memory usage: 1828.17 MB
Saved 2060000 rows. Current memory usage: 1804.92 MB
Saved 2070000 rows. Current memory usage: 1814.78 MB
Saved 2080000 rows. Current memory usage: 1825.22 MB
Saved 2090000 rows. Current memory usage: 1835.34 MB
Saved 2100000 rows. Current memory usage: 1845.58 MB
Saved 2110000 rows. Current memory usage: 1808.38 MB
Saved 2120000 rows. Current memory usage: 1818.94 MB
Saved 2130000 rows. Current memory usage: 1802.89 MB
Saved 2140000 rows. Current memory usage: 1813.86 MB
Saved 2150000 rows. Current memory usage: 1822.84 MB
Saved 2160000 rows. Current memory usage: 1762.22 MB
Saved 2170000 rows. Current memory usage: 1773.05 MB
Saved 2180000 rows. Current memory usage: 1782.50 MB
Saved 2190000 rows. Current memory usage: 1761.02 MB
Saved 2200000 rows. Current memory usage: 1771.72 MB
Saved 2210000 rows. Current memory usage: 1781.86 MB
Saved 2220000 rows. Current memory usage: 1792.12 MB
Saved 2230000 rows. Current memory usage: 1740.30 MB
Saved 2240000 rows. Current memory usage: 1750.44 MB
Saved 2250000 rows. Current memory usage: 1760.78 MB
Saved 2260000 rows. Current memory usage: 1771.27 MB
Saved 2270000 rows. Current memory usage: 1753.66 MB
Saved 2280000 rows. Current memory usage: 1763.92 MB
Saved 2290000 rows. Current memory usage: 1776.08 MB
Saved 2300000 rows. Current memory usage: 1786.19 MB
Saved 2310000 rows. Current memory usage: 1783.86 MB
Saved 2320000 rows. Current memory usage: 1794.05 MB
Saved 2330000 rows. Current memory usage: 1803.62 MB
Saved 2340000 rows. Current memory usage: 1813.72 MB
Saved 2350000 rows. Current memory usage: 1823.88 MB
Saved 2360000 rows. Current memory usage: 1798.05 MB
Saved 2370000 rows. Current memory usage: 1807.86 MB
Saved 2380000 rows. Current memory usage: 1817.95 MB
Saved 2390000 rows. Current memory usage: 1827.78 MB
Saved 2400000 rows. Current memory usage: 1806.78 MB
Saved 2410000 rows. Current memory usage: 1817.31 MB
Saved 2420000 rows. Current memory usage: 1827.14 MB
Saved 2430000 rows. Current memory usage: 1826.48 MB
Saved 2440000 rows. Current memory usage: 1771.84 MB
Saved 2450000 rows. Current memory usage: 1782.06 MB
Saved 2460000 rows. Current memory usage: 1792.17 MB
Saved 2470000 rows. Current memory usage: 1801.97 MB
Saved 2480000 rows. Current memory usage: 1797.25 MB
Saved 2490000 rows. Current memory usage: 1807.11 MB
Saved 2500000 rows. Current memory usage: 1817.09 MB
Saved 2510000 rows. Current memory usage: 1826.81 MB
Saved 2520000 rows. Current memory usage: 1805.70 MB
Saved 2530000 rows. Current memory usage: 1815.70 MB
Saved 2540000 rows. Current memory usage: 1825.06 MB
Saved 2550000 rows. Current memory usage: 1834.86 MB
Saved 2560000 rows. Current memory usage: 1773.44 MB
Saved 2570000 rows. Current memory usage: 1783.39 MB
Saved 2580000 rows. Current memory usage: 1793.25 MB
Saved 2590000 rows. Current memory usage: 1803.02 MB
Saved 2600000 rows. Current memory usage: 1812.81 MB
Saved 2610000 rows. Current memory usage: 1799.14 MB
Saved 2620000 rows. Current memory usage: 1808.97 MB
Saved 2630000 rows. Current memory usage: 1819.03 MB
Saved 2640000 rows. Current memory usage: 1828.91 MB
Saved 2650000 rows. Current memory usage: 1838.31 MB
Saved 2660000 rows. Current memory usage: 1847.48 MB
Saved 2670000 rows. Current memory usage: 1833.86 MB
Saved 2680000 rows. Current memory usage: 1843.77 MB
Saved 2690000 rows. Current memory usage: 1853.47 MB
Saved 2700000 rows. Current memory usage: 1844.77 MB
Saved 2710000 rows. Current memory usage: 1854.39 MB
Saved 2720000 rows. Current memory usage: 1864.22 MB
Saved 2730000 rows. Current memory usage: 1873.69 MB
Saved 2740000 rows. Current memory usage: 1883.42 MB
Saved 2750000 rows. Current memory usage: 1893.06 MB
Saved 2760000 rows. Current memory usage: 1891.64 MB
Saved 2770000 rows. Current memory usage: 1901.33 MB
Saved 2780000 rows. Current memory usage: 1910.66 MB
Saved 2790000 rows. Current memory usage: 1920.14 MB
Saved 2800000 rows. Current memory usage: 1929.67 MB
Saved 2810000 rows. Current memory usage: 1893.48 MB
Saved 2820000 rows. Current memory usage: 1902.98 MB
Saved 2830000 rows. Current memory usage: 1912.61 MB
Saved 2840000 rows. Current memory usage: 1922.06 MB
Saved 2850000 rows. Current memory usage: 1931.38 MB
Saved 2860000 rows. Current memory usage: 1919.45 MB
Saved 2870000 rows. Current memory usage: 1895.27 MB
Saved 2880000 rows. Current memory usage: 1904.45 MB
Saved 2890000 rows. Current memory usage: 1914.06 MB
Saved 2900000 rows. Current memory usage: 1921.92 MB
Saved 2910000 rows. Current memory usage: 1931.48 MB
Saved 2920000 rows. Current memory usage: 1941.06 MB
Saved 2930000 rows. Current memory usage: 1950.31 MB
Saved 2940000 rows. Current memory usage: 1883.75 MB
Saved 2950000 rows. Current memory usage: 1893.05 MB
Saved 2960000 rows. Current memory usage: 1902.34 MB
Saved 2970000 rows. Current memory usage: 1911.59 MB
Saved 2980000 rows. Current memory usage: 1920.89 MB
Saved 2990000 rows. Current memory usage: 1890.67 MB
Saved 3000000 rows. Current memory usage: 1900.00 MB
Saved 3010000 rows. Current memory usage: 1909.16 MB
Saved 3020000 rows. Current memory usage: 1897.70 MB
Saved 3030000 rows. Current memory usage: 1906.78 MB
Saved 3040000 rows. Current memory usage: 1915.92 MB
Saved 3050000 rows. Current memory usage: 1924.95 MB
Saved 3060000 rows. Current memory usage: 1920.83 MB
Saved 3070000 rows. Current memory usage: 1885.70 MB
Saved 3080000 rows. Current memory usage: 1894.97 MB
Saved 3090000 rows. Current memory usage: 1904.50 MB
Saved 3100000 rows. Current memory usage: 1913.69 MB
Saved 3110000 rows. Current memory usage: 1922.98 MB
Saved 3120000 rows. Current memory usage: 1932.22 MB
Saved 3130000 rows. Current memory usage: 1888.69 MB
Saved 3140000 rows. Current memory usage: 1898.09 MB
Saved 3150000 rows. Current memory usage: 1907.34 MB
Saved 3160000 rows. Current memory usage: 1880.52 MB
Saved 3170000 rows. Current memory usage: 1889.73 MB
Saved 3180000 rows. Current memory usage: 1898.72 MB
Saved 3190000 rows. Current memory usage: 1901.25 MB
Saved 3200000 rows. Current memory usage: 1910.45 MB
Saved 3210000 rows. Current memory usage: 1919.50 MB
Saved 3220000 rows. Current memory usage: 1928.55 MB
Saved 3230000 rows. Current memory usage: 1898.11 MB
Saved 3240000 rows. Current memory usage: 1907.47 MB
Saved 3250000 rows. Current memory usage: 1916.83 MB
Saved 3260000 rows. Current memory usage: 1926.02 MB
Saved 3270000 rows. Current memory usage: 1916.36 MB
Saved 3280000 rows. Current memory usage: 1925.55 MB
Saved 3290000 rows. Current memory usage: 1934.56 MB
Saved 3300000 rows. Current memory usage: 1943.64 MB
Saved 3310000 rows. Current memory usage: 1934.70 MB
Saved 3320000 rows. Current memory usage: 1943.77 MB
Saved 3330000 rows. Current memory usage: 1952.72 MB
Saved 3340000 rows. Current memory usage: 1961.75 MB
Saved 3350000 rows. Current memory usage: 1970.81 MB
Saved 3360000 rows. Current memory usage: 1953.06 MB
Saved 3370000 rows. Current memory usage: 1962.08 MB
Saved 3380000 rows. Current memory usage: 1970.94 MB
Saved 3390000 rows. Current memory usage: 1980.00 MB
Saved 3400000 rows. Current memory usage: 1951.95 MB
Saved 3410000 rows. Current memory usage: 1961.20 MB
Saved 3420000 rows. Current memory usage: 1970.34 MB
Saved 3430000 rows. Current memory usage: 1979.55 MB
Saved 3440000 rows. Current memory usage: 1988.19 MB
Saved 3450000 rows. Current memory usage: 1997.06 MB
Saved 3460000 rows. Current memory usage: 2005.98 MB
Saved 3470000 rows. Current memory usage: 1946.16 MB
Saved 3480000 rows. Current memory usage: 1955.12 MB
Saved 3490000 rows. Current memory usage: 1963.94 MB
Saved 3500000 rows. Current memory usage: 1972.86 MB
Saved 3510000 rows. Current memory usage: 1982.08 MB
Saved 3520000 rows. Current memory usage: 1990.97 MB
Saved 3530000 rows. Current memory usage: 1941.25 MB
Saved 3540000 rows. Current memory usage: 1950.17 MB
Saved 3550000 rows. Current memory usage: 1958.86 MB
Saved 3560000 rows. Current memory usage: 1968.70 MB
Saved 3570000 rows. Current memory usage: 1977.84 MB
Saved 3580000 rows. Current memory usage: 1986.77 MB
Saved 3590000 rows. Current memory usage: 1965.39 MB
Saved 3600000 rows. Current memory usage: 1971.61 MB
Saved 3610000 rows. Current memory usage: 1980.91 MB
Saved 3620000 rows. Current memory usage: 1989.77 MB
Saved 3630000 rows. Current memory usage: 1998.73 MB
Saved 3640000 rows. Current memory usage: 2007.50 MB
Saved 3650000 rows. Current memory usage: 1953.31 MB
Saved 3660000 rows. Current memory usage: 1962.14 MB
Saved 3670000 rows. Current memory usage: 1971.22 MB
Saved 3680000 rows. Current memory usage: 1980.33 MB
Saved 3690000 rows. Current memory usage: 1982.88 MB
Saved 3700000 rows. Current memory usage: 1992.16 MB
Saved 3710000 rows. Current memory usage: 2001.12 MB
Saved 3720000 rows. Current memory usage: 1976.67 MB
Saved 3730000 rows. Current memory usage: 1985.97 MB
Saved 3740000 rows. Current memory usage: 1994.84 MB
Saved 3750000 rows. Current memory usage: 1931.36 MB
Saved 3760000 rows. Current memory usage: 1940.67 MB
Saved 3770000 rows. Current memory usage: 1949.69 MB
Saved 3780000 rows. Current memory usage: 1958.81 MB

# Remove from here

In [6]:
# save
save_path = "../../data/amazon/saved/"

train.to_pickle(save_path + "train_amazon.pkl")
val.to_pickle(save_path + "valid_amazon.pkl")
test.to_pickle(save_path + "test_amazon.pkl")

NameError: name 'train' is not defined

In [ ]:
# merge df vs meta
merged_df = user_df.merge(meta_df, on='parent_asin', how='right', suffixes=('', '_meta'))
merged_df = merged_df.rename(columns={'title': 'title_review'})
merged_df['timestamp'] = pd.to_datetime(merged_df['timestamp'], unit='s')
merged_df

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,title_meta,average_rating,rating_number,features,description,categories,details
0,1.0,Weak,Definitely the weakest of the three albums SWV...,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,2015-01-03 06:22:17.000,1.0,0.0,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
1,1.0,Too Many Guest Spots,Unlike It's About Time and New Beginning this ...,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,2013-09-16 20:19:59.000,1.0,1.0,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
2,4.0,"When &quot;Tension&quot; is released, expect q...","Their third and final album as a group, &quot;...",B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,2000-03-19 00:44:40.000,1.0,0.0,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
3,5.0,Thanks,thank you,B000002X4C,B000002X4C,AE73R3KLFKXFNWUBOA4JCLT5UWKA,2015-03-27 18:15:21.000,0.0,1.0,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
4,2.0,Release Some Tension - 2.5 stars,When I was trying to decide whether or not to ...,B000002X4C,B000002X4C,AFICHVZ62IFAWIBZK3U6B7NZWAVQ,2010-11-13 08:44:58.000,3.0,0.0,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4827554,5.0,A Singer of Distinction,"Dame Joan Hilda Hood Hammond, DBE, CMG (24 May...",B000T001IM,B000T001IM,AFICGLJ62Y3YRTYN7PNYM6UUOA6Q,2013-12-20 11:54:02.000,1.0,1.0,"Joan Hammond, Historical Recordings from 1941-49",5.0,1,,,"CDs & Vinyl, Classical",{}
4827555,4.0,Great Performer!,I first saw Heinz Winckler in a Broadway music...,B00069I6RO,B00069I6RO,AHLRFMDIVAQF7ARTPM6PVJO6DTYQ,2008-01-03 08:10:12.000,2.0,1.0,Come Alive,4.5,4,,The Second Full Length Album from the Winner o...,"CDs & Vinyl, International Music, Africa, Sout...","{""Package Dimensions"": ""5.55 x 4.97 x 0.54 inc..."
4827556,5.0,Cheaper,"OK, loves, it's cheaper to go to amazon.co.uk ...",B00069I6RO,B00069I6RO,AGZVQUGBE64F3M2A5EBU2CNDTKIA,2004-12-15 22:34:52.000,5.0,0.0,Come Alive,4.5,4,,The Second Full Length Album from the Winner o...,"CDs & Vinyl, International Music, Africa, Sout...","{""Package Dimensions"": ""5.55 x 4.97 x 0.54 inc..."
4827557,5.0,Beautiful and poignant.,Wonderful collection of songs with haunting tu...,B08BF2PH1X,B08BF2PH1X,AEZET6CFIEJWTU7UTEK57IDARX2A,2021-02-09 22:59:55.740,0.0,1.0,Long Day in the Milky Way,4.4,16,,2020 release from the folk/Americana singer/so...,"CDs & Vinyl, Folk","{""Product Dimensions"": ""5.5 x 4.9 x 0.4 inches..."
4827558,3.0,"Technically good, but sparse",Justin Vali is a modern-day master of the nati...,B000001LW6,B000001LW6,AGL4DWXKWAREPMSTB4OVWH3OY3KQ,2004-08-08 19:37:55.000,3.0,0.0,Genius of Valiha,3.0,1,,World Music Library 122. Track List: 1 Faly mi...,"CDs & Vinyl, International Music","{""Package Dimensions"": ""5.55 x 4.97 x 0.54 inc..."

In [ ]:
# filter merge_df with rating >= 3
merged_df['like'] = merged_df['rating']>3

# data.drop_duplicates(subset=['asin'])

In [ ]:
# encode user_id and asin
merged_df['user_id_encoded'] = LabelEncoder().fit_transform(merged_df['user_id'])
merged_df['asin_encoded'] = LabelEncoder().fit_transform(merged_df['asin'])
merged_df['parent_asin_encoded'] = LabelEncoder().fit_transform(merged_df['parent_asin'])

# data partition
# merged_df = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)
df_train, df_test = train_test_split(merged_df, test_size=0.2, random_state=42)
train_interactions_set = set(zip(df_train['user_id_encoded'], df_train['asin_encoded']))
df_test = df_test[~df_test[['user_id_encoded', 'asin_encoded']].apply(tuple, axis=1).isin(train_interactions_set)]

## Lightfm

In [ ]:
dataset = Dataset()
dataset.fit(users= merged_df['user_id_encoded'], items = merged_df['asin_encoded'])
train_interactions, train_w = dataset.build_interactions((row['user_id_encoded'], row['asin_encoded']) for id, row in df_train.iterrows())
test_interactions, test_w = dataset.build_interactions((row['user_id_encoded'], row['asin_encoded']) for id, row in df_test.iterrows())

In [ ]:
model = LightFM(loss='warp', item_alpha=1e-6, user_alpha=1e-6)
# train model
model.fit(train_interactions, epochs=50, num_threads=2, sample_weight=train_w)

In [ ]:
def add_combined_text(row):
    combined_text = f"title_review: {str(row['title_review'])}, text: {str(row['text'])}, title_meta: {str(row['title_meta'])}, features: {str(row['features'])}, description: {str(row['description'])}, details: {str(row['details'])}, categories: {str(row['categories'])}"
    row['combined_text'] = combined_text
    return row

# data = merged_df.map(add_combined_text)
merged_df = merged_df.apply(add_combined_text, axis=1)
# combined_texts = merged_df["combined_text"]
merged_df

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,title_meta,...,rating_number,features,description,categories,details,like,user_id_encoded,asin_encoded,parent_asin_encoded,combined_text
0,3.0,Three Stars,all advertizements,B00FA7T630,B00FA7T630,AFNRZBYAPLFKJNJU5BK3TTRWHJ6A,2015-10-26 17:49:26.000,0,1,GQ Print Access Print Magazine,...,10,,"Product Description, Dive into, GQ, ’s culture...",,"{""Date First Available"": ""June 2, 2020"", ""Manu...",False,24328,2499,2499,"title_review: Three Stars, text: all advertize..."
1,5.0,A great audiophile audio magazine that covers ...,A great audiophile audio magazine that covers ...,B00F8P62PO,B00F8P62PO,AETSCPCEEZ3S3BGNU4WCIN4H62ZQ,2018-01-11 07:17:33.014,6,1,Hi-Fi + Print Magazine,...,44,,Hi-Fi+ is Europe's premier English-language hi...,"Magazine Subscriptions, Arts, Music & Photogra...","{""Date First Available"": ""September 19, 2013"",...",True,12133,2498,2498,title_review: A great audiophile audio magazin...
2,3.0,inspirational,i really like the ideas they have in this maga...,B003F1W9T6,B003F1W9T6,AGQCHHMSO6S2DJLWGGFLCVUY477Q,2011-12-24 03:36:48.000,2,1,Paper Crafts,...,3,,,,"{""Date First Available"": ""May 12, 2021""}",False,40505,2095,2095,"title_review: inspirational, text: i really li..."
3,2.0,Should be called card making,"I ordered this magazine because I enjoy ""paper...",B003F1W9T6,B003F1W9T6,AEIKS6KU32T7VBIAP7YIMR2LICQQ,2013-03-03 05:28:59.000,0,1,Paper Crafts,...,3,,,,"{""Date First Available"": ""May 12, 2021""}",False,6799,2095,2095,"title_review: Should be called card making, te..."
4,4.0,Four Stars,Son loves this,B00007AXX1,B00007AXX1,AGDDHCNIGZPKBQRST6UVTCVPD53A,2015-12-04 12:24:30.000,0,1,Horse Illustrated,...,284,,,"Magazine Subscriptions, Sports, Recreation & O...","{""Package Dimensions"": ""10.79 x 8.11 x 0.31 in...",True,34411,871,871,"title_review: Four Stars, text: Son loves this..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71492,1.0,"Beautiful fashion magazine, subscription never...",I have been subscribing to V for a few years n...,B0007INIGI,B0007INIGI,AFDU3G7WMDWWA2XJLYNQLHSIEZMQ,2012-03-01 16:47:32.000,1,1,V Magazine - Ny Print Magazine,...,5,,"V Magazine, was launched in September 1999 as ...","Magazine Subscriptions, Fashion & Style, Men","{""Date First Available"": ""September 14, 2006"",...",False,19700,1315,1315,"title_review: Beautiful fashion magazine, subs..."
71493,1.0,What a fiasco,I subscribed to this magazine a year ago and n...,B0002800W8,B0002800W8,AG5BWPCEIS6FEJKQZTLJVQLGQNGA,2007-09-05 15:08:34.000,2,0,Victorian Review Print Magazine,...,1,,"Published since 1972,, Victorian Review, is an...",,"{""Date First Available"": ""September 14, 2006"",...",False,31564,1248,1248,"title_review: What a fiasco, text: I subscribe..."
71494,1.0,Have yet to receive the first issue,It has been a month since I purchased this mag...,B00007L0RC,B00007L0RC,AHA6K63RE5ODXSTDNPRND73U3EMQ,2011-02-15 16:55:54.000,0,1,Visto Print Magazine,...,2,,"A news magazine targeted at the wider public, ...",,"{""Date First Available"": ""September 15, 2013"",...",False,47920,1032,1032,title_review: Have yet to receive the first is...
71495,4.0,Super Fast Delivery,I was totally surprised how fast I received th...,B00007L0RC,B00007L0RC,AGQT3FF5NHZUOS3YSEAMIRY65VRQ,2012-01-18 22:58:43.000,0,1,Visto Print Magazine,...,2,,"A news magazine targeted at the wider public, ...",,"{""Date First Available"": ""September 15, 2013"",...",True,40744,1032,1032,"title_review: Super Fast Delivery, text: I was..."
71496,5.0,Five Stars,Don't remember buying this but I am sure it is...,B017L2BFQC,B017L2BFQC,AFBE73KK74B6YSG333PPIPCUBYKA,2018-03-03 16:04:21.386,0,1,Modern Pioneer Print Magazine,...,4,,,"Magazine Subscriptions, Sports, Recreation & O...","{""Date First Available"": ""November 4, 2015"", ""...",True,18564,2860,2860,"title_review: Five Stars, text: Don't remember..."

In [ ]:
def get_purchase_history(merged_df, user_id, k):
    user_hist = merged_df[merged_df['user_id_encoded']==user_id]
    user_hist_sorted = user_hist.sort_values(by='timestamp', ascending=False)
    recent_purchase = user_hist_sorted[['asin', 'title_meta', 'description', 'combined_text']].head(k)
    return recent_purchase

def get_like_items(merged_df, user_id):
    like_items = merged_df[(merged_df['user_id_encoded']==user_id) & (merged_df['like']==True)].sort_values(by='timestamp', ascending=False)
    like_items = like_items[['asin', 'title_meta', 'description']].iloc[:10]
    return like_items

def get_dislike_items(merged_df, user_id):
    dislike_items = merged_df[(merged_df['user_id_encoded']==user_id) & (merged_df['like']==False)].sort_values(by='timestamp', ascending=False)
    dislike_items = dislike_items[['asin', 'title_meta', 'description']].iloc[:10]
    return like_items

In [ ]:
def evaluate_recall(model, train_interactions, test_interactions, k):
    precision= precision_at_k(model, test_interactions, train_interactions=train_interactions, k=k).mean()
    recall= recall_at_k(model, test_interactions, train_interactions=train_interactions, k=k).mean()
    auc= auc_score(model, test_interactions, train_interactions=train_interactions).mean()
    return precision, recall, auc

eval_metrics = evaluate_recall(model, train_interactions, test_interactions, k=50)

In [ ]:
print(eval_metrics)

(0.010412165, 0.20115773521154753, 0.85380054)

In [ ]:
def get_top_k(model, dataset, merged_df, user_id, k):
    n_users, n_items = dataset.interactions_shape()

    user_ids = np.full(n_items, user_id)  # or use np.repeat(user_id, n_items)
    # item_ids = np.arange(n_items)
    interacted_items = set(merged_df[merged_df['user_id_encoded']==user_id]['asin_encoded'])

    scores = model.predict(user_ids, np.arange(n_items))
    scores[list(interacted_items)] = -np.inf

    top_items_encoded = np.argsort(-scores)[:k]
    asin_info = dict(zip(merged_df['asin_encoded'], zip(merged_df['asin'], merged_df['title_meta'], merged_df['combined_text'])))
    recs = [asin_info[item] for item in top_items_encoded if item in asin_info]
    return recs

# user_id_encoder = dict(zip(merged_df['user_id_encoded'], merged_df['user_id']))
recs_dict = {user_id: get_top_k(model, dataset, merged_df, user_id, k=50) for user_id in merged_df['user_id_encoded'].unique()}

def get_recs(user_id):
    return recs_dict.get(user_id, [])

In [ ]:
user_id_test = merged_df['user_id_encoded'].iloc[8]
recent_purchases = get_purchase_history(merged_df, user_id_test, k=10)
like_items = get_like_items(merged_df, user_id_test)
dislike_items = get_dislike_items(merged_df, user_id_test)
top_k_recs= get_recs(user_id_test)

In [ ]:
top_k_recs

[('B00007B1JS',
  'Soap Opera Digest',
  'title_review: Subscription, text: I am unable to review this magazine  I have never received an issue.<br /><br />Needless to say, I am not happy about this.<br /><br />Lynda Epler, title_meta: Soap Opera Digest, features: , description: , details: {"Date First Available": "April 30, 2015"}, categories: Magazine Subscriptions, Entertainment & Pop Culture, Television'),
 ('B00GBJIEQG',
  'Inked',
  'title_review: Five Stars, text: Great magazine, title_meta: Inked, features: , description: , details: {"Date First Available": "October 31, 2013"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Arts, Photography'),
 ('B00007EN1O',
  'Alpaca    Print Magazine',
  'title_review: Excellent publication about alpacas, text: This magazine is a must for any alpaca owner, would be alpaca owner, or one who is just learning about these beautiful animals.<br />It is beautifully done, showing pictures of alpacas,advertisements for alpaca farms, as well as very well-written articles.<br />The articles are timely and of great interest and learning tools for alpaca owners., title_meta: Alpaca    Print Magazine, features: , description: , details: {}, categories: '),
 ('B00005N7T1',
  'Teddy Bear and Friends    Print Magazine',
  'title_review: gift, text: I love ti so much it was a great gift and a surprise. I just had it renewed.again this year, title_meta: Teddy Bear and Friends    Print Magazine, features: , description: Teddy Bear & Friends is an art magazine for adult teddy bear collectors. Content includes artist and manufacturer profiles, secondary market pricing, convention coverage and calendars, and crafting patterns and tips. Along with coverage of collectible teddy bears, attention is given to other plush animals (friends) and to miniature teddy bears. Teddy Bear & Friends sponsors the TOBY program, an annual awards program in which plush creations are judged first by industry experts and then readers, honors the best of artist and manufactured teddy bears and friends in the industry. While Teddy Bear & Friends is mainly a consumer publication, it is also read as a trade magazine by retailers, artists, show promoters, and other members of the bear industry., details: {"Date First Available": "September 14, 2006", "Manufacturer": "JP Media LLC"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Arts, Crafts & Collectibles'),
 ('B00XDAH85O',
  'NEWSWEEK SPECIAL    Print Magazine',
  'title_review: Five Stars, text: The &#34;Dead&#34; are a legend!, title_meta: NEWSWEEK SPECIAL    Print Magazine, features: , description: Newsweek Special Issues celebrates the storied and legendary rock & roll band the Grateful Dead. Born in 1965 during the rise of counterculture, the Dead, as they are forever known, revolutionized music with their unique blend of rock, blues, folk, bluegrass, reggae, country, psychedelic and more. Fifty years later, the surviving members of the band—Mickey Hart, Bill Kreutzmann, Phil Lesh and Bob Weir—will take the stage together for their final concerts, Fare Thee Well. Produced in partnership with these living legends, this fully illustrated, 100-page special issue brings you a celebration of the peerless band to commemorate their 50th anniversary and the 20th anniversary of the death of their celebrated frontman and guitarist, Jerry Garcia., details: {"Package Dimensions": "8 x 0.5 x 0.2 inches; 11.2 Ounces", "Date First Available": "May 8, 2015", "Manufacturer": "Media Lab Publishing"}, categories: '),
 ('B01N2JMFXE',
  "Harper's Bazaar    Print Magazine",
  'title_review: Misleading, text: Beware! I didn’t receive all the issues, title_meta: Harper\'s Bazaar    Print Magazine, features: , description: Harper?s BAZAAR, the fashion authority, brings you the latest new looks from the hottest designers. You?ll get 12 beautiful issues a year full of best dressed secrets, must-haves and great finds. Experience the best in style and beauty with Harper?s BAZAAR., details: {"Date First Available": "November 21, 2016", "Manufacturer": "Hearst Magazines"}, categories: Magazine Subscriptions, Fashion & Style, Men'),
 ('B002NM7VNM',
  'Log Home Living',
  'title_review: Where\'s the magazine???!!!, text: STILL WAITING!!!  Purchased it over a month ago and haven\'t gotten it yet.  Is everything done by hand in these companies?  Why is it taking so long???  Oh, well, I\'ll let you know when I know., title_meta: Log Home Living, features: , description: , details: {"Date First Available": "September 3, 2009"}, categories: Magazine Subscriptions, Home & Garden, Design & Decoration'),
 ('B00F8P2VOK',
  'New Pioneer    Print Magazine',
  'title_review: Five Stars, text: great Magazine, wish there was more than just 4 issues., title_meta: New Pioneer    Print Magazine, features: , description: , details: {"Date First Available": "September 19, 2013", "Manufacturer": "Harris Publications"}, categories: '),
 ('B0000EI1K6',
  'Franchise Handbook    Print Magazine',
  'title_review: One Star, text: Poor information wrong numbers etc<br />Ex McDonalds pricing now is less than ten years ago I think not, title_meta: Franchise Handbook    Print Magazine, features: , description: The Franchise Handbook provides information about franchises available for purchase, costs to expect and other details about owning a franchise. The book outlines 1,700+ franchises, and listings are arranged alphabetically both by type of business and company name., details: {"Date First Available": "September 18, 2006", "Manufacturer": "Enterprise Magazines Inc"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Economics & Economic Theory'),
 ('B01I9FTYR2',
  "Woman's Day    Print Magazine",
  'title_review: Five Stars, text: Great, title_meta: Woman\'s Day    Print Magazine, features: , description: , details: {"Date First Available": "July 11, 2016"}, categories: '),
 ('B00CRPCWEI',
  'Simple Things',
  'title_review: A Trip to the UK, text: This is an amazing and beautiful magazine. I have subscribed to it for years. I’ve enjoyed articles on stone circles, historic bathhouses, nature, and recipes. Unfortunately, American mail service changed about 6 months ago. It now takes at least 3 months to receive an issue. Before that, they came within a week to a month., title_meta: Simple Things, features: , description: , details: {"Date First Available": "May 14, 2013"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Psychology'),
 ('B00005N7T6',
  'The Saturday Evening Post',
  'title_review: Not Worth The Price of a Subscription, text: As an aficionado of all things historic, old, and traditional, I subscribed to "The Saturday Evening Post." I was disappointed by what I received. With the exception of the excellent illustrations by Norman Rockwell, the magazine was largely advertisements for prescription medications and puff pieces about popular actors, authors, and other celebrities. This is not a worthy heir to the legacy of its founder, Benjamin Franklin, and the many gifted and talented individuals who have been associated with the magazine throughout its history. Simply put, it was not worth the price of a subscription., title_meta: The Saturday Evening Post, features: , description: , details: {"Date First Available": "September 14, 2006"}, categories: Magazine Subscriptions, Travel, City & Regional, United States, Midwest'),
 ('B005ML7WLM',
  'Man Magnum    Print Magazine',
  'title_review: Just fun reading. If you really want to put yourself ..., text: Disclosure:  I have written and published in Man Magnum.  An Alaskan hunting in Africa.  The magazine is a rich taste of hunting in Africa, and the real deal.  Think of this as Outdoor Life back in the 40\'s, 50\'s and 60\'s, but African.  Just fun reading.  If you really want to put yourself into Africa... and its adventures... this is the magazine for you., title_meta: Man Magnum    Print Magazine, features: , description: Magnum is Africa s oldest and leading magazine for hunters and shooters. Subjects include wingshooting, gundogs, rifles, shotguns, handguns, personal defence, ammo, ballistics, hand-loading, military weapons, antiques, muzzle-loaders, history, big game hunting and more. All with an African flavour., details: {"Date First Available": "September 14, 2011", "Manufacturer": "Media 24"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Baseball'),
 ('B002PXVZHM',
  'Gun Dog',
  'title_review: Great magazine for bird dog owners, hunters and nonhunters alike, text: If you own a bird dog breed, get this magazine. 70% of the articles involve dog training, dog health and wellness, and dog behavior of gun dogs written by professional dog trainers and veterinarians. Even if you aren\'t a hunter but own a bird dog breed, get a subscription to this magazine. You will learn so much about your dog. If you are a hunter, they also have articles about hunting areas throughout the USA., title_meta: Gun Dog, features: , description: , details: {"Date First Available": "September 22, 2009"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Hunting & Firearms'),
 ('B00006K8S5',
  'Christian-New Age Quarterly    Print Magazine',
  'title_review: A Breath of Fresh Air, text: Having been raised a Christian a long, long time ago -- but now more a student of Buddhism and other new edge philosophies -- I must admit I initially had doubts about reading this publication.  However, since subscribing to  Christian*New Age Quarterly about a year ago, I have found every issue to be just the right blend of traditional theology and new age ideas.<br /><br />Catherine Groves has the ability to attract some of the most insightful writers on the subjects at hand -- and the discourse that results has always been helpful to me.  (Coincidentally enough, each issue always seems to have some particle of wisdom or truth that focuses on an issue going on in my own life as I am reading it.<br /><br />So it\'s easy for me to see why this publication has been going strong for 20 years -- its brilliant ideas and polished writing make it a worthy companion to any other spiritual books you have in your library today.<br /><br />And after a grueling day in the "real world", reading C*NAQ can be a breath of fresh air!, title_meta: Christian-New Age Quarterly    Print Magazine, features: , description: Devoted to goodwill dialog, Christian*New Age Quarterly explores the differences between and common ground of Christianity and alternative spiritualities. Top-quality articles, sound scholarship and lively columns make this a genuine interfaith bridge - as entertaining as it is thought-provoking., details: {"Date First Available": "March 2, 2010", "Manufacturer": "Christian-New Age Quarterly"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Religion & Spirituality'),
 ('B000EGCIW8',
  'Coastal Living    Print Magazine',
  'title_review: get it, text: good deal, title_meta: Coastal Living    Print Magazine, features: , description: , details: {"Date First Available": "April 30, 2015"}, categories: Magazine Subscriptions, Travel, City & Regional'),
 ('B0000A8YW4',
  'Watercolor Artist',
  'title_review: A favorite!, text: I look forward to every issue of this magazine. It has great information and beautiful illustrations. Getting copies in both paper form and on line is especially useful to me., title_meta: Watercolor Artist, features: , description: , details: {"Date First Available": "September 18, 2006"}, categories: Magazine Subscriptions, Crafts & Hobbies, Painting'),
 ('B00007AWTU',
  'Draft Horse Journal',
  'title_review: The draft horse industry standard journal, text: The Draft Horse Journal has been highlighting the major shows and sales since 1964.  Articles cover harness, working horses, draft horse keeping, draft health issues, and important horses, breeds, and horsepeople.  Also important are the advertisements -- the DHJ serves as a directory of services and supplies for the draft horse industry.  Expect to keep your issues for future reference.  Usually around 220-240 pp., title_meta: Draft Horse Journal, features: , description: , details: {"Date First Available": "September 16, 2006"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Baseball'),
 ('B00026EEK4',
  'Mon Jardin Et Ma Maison    Print Magazine',
  'title_review: Five Stars, text: great!great! great pictures and articles<br />a great way of learning french, title_meta: Mon Jardin Et Ma Maison    Print Magazine, features: , description: MON JARDIN & MA MAISON achieves the balance between displaying beautiful landscaped gardens and the practical advice to achieve the same results in the readers own gardens. French language., details: {"Date First Available": "September 14, 2006", "Manufacturer": "Publications Grand Public"}, categories: Magazine Subscriptions, Home & Garden, Design & Decoration'),
 ('B002DHSFS2',
  'TV Guide Magazine Crosswords    Print Magazine',
  'title_review: Four Stars, text: awesome !, title_meta: TV Guide Magazine Crosswords    Print Magazine, features: , description: All kinds of crosswords for the TV fan, including Classics, Channel Surfers, Theme Puzzles, and a TV Word-Find, as well as two insightful columns and a quiz in every issue., details: {"Date First Available": "June 16, 2009", "Manufacturer": "Kappa Publishers Group"}, categories: '),
 ('B00005QJE2',
  'Nylon    Print Magazine',
  'title_review: inspiring, text: as a high school student aspiring to attend art school, nylon has provided me with countless sources of inspiration in their creative photography, layout, and decoration. i look forward to reading the magazine each month, and i honestly devour every last word and picture.<br /><br />nylon is a creative, whimsical and fantastic magazine. i highly reccomend it to anyone interested in a fashion magazine that goes beyond a "beach read.", title_meta: Nylon    Print Magazine, features: , description: A vibrant and proactive voice for today\'s hip, intelligent, young women seeking fresh perspectives on fashion, beauty and music., details: {"Date First Available": "September 14, 2006", "Manufacturer": "Nylon Media Inc."}, categories: Magazine Subscriptions, Business & Investing, International'),
 ('B00B8C8SWQ',
  'Current World Archaeology    Print Magazine',
  'title_review: Five Stars, text: The best general archaeology magazine I have read. I  highly recommend it!, title_meta: Current World Archaeology    Print Magazine, features: , description: Current World Archaeology, the magazine that studies archaeology round the world. CWA was founded in 2003 as a sister magazine to Current Archaeology which, since 1967, has been reporting on the latest discoveries in British archaeology. But CWA does not just look at the latest discoveries: it also travels the globe, looking at great monuments around the world, explaining how they came to be the sites - and sights - we see today., details: {"Date First Available": "January 30, 2013", "Manufacturer": "Current Publishing"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, History'),
 ('B002CT5156',
  'Cruising World',
  'title_review: Not what I expected, text: It was not what I expected and I would like to stop my subscription.&#34;cruising to me is not buying a boat, title_meta: Cruising World, features: , description: , details: {"Date First Available": "June 11, 2009"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Individual Sports'),
 ('B019R0URIS',
  'Simple Grace    Print Magazine',
  'title_review: Five Stars, text: Great inspirational reading<br />!, title_meta: Simple Grace    Print Magazine, features: , description: A Christian monthly magazine packed with inspirational stories, celebrity profiles and a media guide. Plus, a beautiful daily devotional with readings based on Jesus teachings. It s your daily dose of hope!, details: {"Date First Available": "December 23, 2015", "Manufacturer": "Bauer Publishing"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Religion & Spirituality'),
 ('B002PXVZDQ',
  'New Jersey Monthly',
  'title_review: :-(, text: Informative magazine however there are too many advertisements. I wish it had more information then it actually does. It was truly a disappointment., title_meta: New Jersey Monthly, features: , description: , details: {"Date First Available": "September 22, 2009"}, categories: Magazine Subscriptions, Travel, City & Regional, United States, Midwest'),
 ('B000066T0H',
  'Goldmine',
  'title_review: Goldmine is just what you are looking for, text: Great information on the music scene regardless of your inclinations....rock, jazz, alternative, etc., title_meta: Goldmine, features: , description: , details: {"Date First Available": "September 14, 2006"}, categories: Magazine Subscriptions, Arts, Music & Photography, Music'),
 ('B00HSUY3S0',
  'WATCH!    Print Magazine',
  'title_review: Five Stars, text: Interesting mix of articles., title_meta: WATCH!    Print Magazine, features: , description: , details: {"Date First Available": "January 11, 2014"}, categories: Magazine Subscriptions, Entertainment & Pop Culture, Celebrities & Gossip'),
 ('B00008KFZH',
  'Sports Afield',
  'title_review: Ruined, text: I wished a was able to find a copy of S.A. before I got a subscription.  The S.A. that I knew this is not.  The best features of this magazine have been stripped away.  I can\'t wait for my subscription to end, and I just received my first copy.  There are much better hunting magazines out there, wish I had the time to list them., title_meta: Sports Afield, features: , description: , details: {"Date First Available": "September 18, 2006"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Baseball'),
 ('B000063XJL',
  'National Geographic Kids    Print Magazine',

In [ ]:
user_id_test = merged_df['user_id_encoded'].iloc[8]
recent_purchases = get_purchase_history(merged_df, user_id_test, k=3)
recent_purchases

,asin,title_meta,description,combined_text
8,B00007AXX1,Horse Illustrated,,"title_review: Great Magazine, text: This magaz..."

In [ ]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (2.5.1+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->bitsandbytes) (3.0.2)
Downloading bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 6.6 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.44.1

In [ ]:
import torch
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer, pipeline
from langchain.document_loaders import TextLoader
from langchain.vectorstores import Chroma
from langchain.prompts import PromptTemplate
from langchain.embeddings import HuggingFaceEmbeddings
from langchain_huggingface.llms import HuggingFacePipeline
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.schema import Document
from langchain.chains import RetrievalQA

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

In [ ]:

# since max number of tokens of sentence transformers is 512
# split the text into smaller chunks that fit within this limit before embedding
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)

# prepare documents
def prepare_documents(user_id_test, recs):
    documents = []
    for asin, title_meta, combined_text in recs:
        chunks = text_splitter.split_text(combined_text)
        for chunk in chunks:
            metadata = {
                "asin": asin,
                "title_meta": title_meta,
            }
            doc = Document(page_content=chunk, metadata=metadata)
            documents.append(doc)
    return documents

user_documents = prepare_documents(user_id_test, top_k_recs)
# os.environ["HUGGINGFACEHUB_API_TOKEN"] = "YOUR_HUGGINGFACE_TOKEN_HERE"
# YOUR_HUGGINGFACE_TOKEN_HERE
embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
chroma_client = Chroma.from_documents(documents=user_documents, embedding=embeddings, persist_directory="./content/chroma_db")

def get_search_result(user_query, chroma_client, k):
    res = chroma_client.similarity_search(query=user_query, k=k)
    return res

<ipython-input-25-0d67646e6ac0>:22: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
user_query= "beauty magazine that can provide beauty tips"
retrieved_docs = get_search_result(user_query, chroma_client, k=5)
retrieved_docs

[Document(metadata={'asin': 'B00005QJE2', 'title_meta': 'Nylon    Print Magazine'}, page_content='interested in a fashion magazine that goes beyond a "beach read.", title_meta: Nylon    Print Magazine, features: , description: A vibrant and proactive voice for today\'s hip, intelligent, young women seeking fresh perspectives on fashion, beauty and music., details: {"Date First Available": "September 14, 2006", "Manufacturer": "Nylon Media Inc."}, categories: Magazine Subscriptions, Business & Investing, International'),
 Document(metadata={'asin': 'B00005QJE2', 'title_meta': 'Nylon    Print Magazine'}, page_content='title_review: inspiring, text: as a high school student aspiring to attend art school, nylon has provided me with countless sources of inspiration in their creative photography, layout, and decoration. i look forward to reading the magazine each month, and i honestly devour every last word and picture.<br /><br />nylon is a creative, whimsical and fantastic magazine. i highly reccomend it to anyone interested in a fashion magazine that goes beyond a "beach read.", title_meta: Nylon    Print'),
 Document(metadata={'asin': 'B00C2E2C0I', 'title_meta': 'Essential Homme    Print Magazine'}, page_content='title_review: ess homm -- piece of junk, text: ess homm piece of junk, title_meta: Essential Homme    Print Magazine, features: , description: Essential Homme is the style source for affluent, successful, and fashion-forward men who are passionate about high quality, high-end luxury fashion., details: {"Date First Available": "March 28, 2013", "Manufacturer": "Essential Publications Us Llc"}, categories: Magazine Subscriptions, Crafts & Hobbies, Needlecrafts'),
 Document(metadata={'asin': 'B001D0FSVW', 'title_meta': 'Tathaastu    Print Magazine'}, page_content='title_review: Love it!, text: Love this magazine! The articles bring me back to what really is important in life. The photography and artwork are absolutely beautiful; full of rich, vibrant colors and backgrounds., title_meta: Tathaastu    Print Magazine, features: , description: Tathaastu magazine is written to help you have a happier and healthier life. Nourish your mind, body and soul by helping you follow a more spiritual way of life and lead it with peace, harmony and dignity., details:'),
 Document(metadata={'asin': 'B002PXVZDQ', 'title_meta': 'New Jersey Monthly'}, page_content='title_review: :-(, text: Informative magazine however there are too many advertisements. I wish it had more information then it actually does. It was truly a disappointment., title_meta: New Jersey Monthly, features: , description: , details: {"Date First Available": "September 22, 2009"}, categories: Magazine Subscriptions, Travel, City & Regional, United States, Midwest')]

In [ ]:
# !pip install accelerate

In [ ]:
model_id = "nvidia/Mistral-NeMo-Minitron-8B-Base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
# dtype = torch.bfloat16
model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=100,
)

# HuggingFace pipeline integration
hf = HuggingFacePipeline(pipeline=pipe)
llm = hf

tokenizer_config.json:   0%|          | 0.00/177k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.26M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
`low_cpu_mem_usage` was None, now default to True since model is quantized.

model.safetensors.index.json:   0%|          | 0.00/29.9k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
prompt_template = """
Imagine you are a recommender. Given the user's recent purchase history, liked items, disliked items, and query:
User Query: {question}
Recent Purchases: {purchase_history}
Liked Items: {liked_items}
Disliked Items: {disliked_items}

Please rank the following items based on relevance and provide a brief explanation for each:
{context}
Reranked Recommendations:
"""

def personal_rerank(user_query, recent_purchase, retrieved_docs, like_items, dislike_items, llm, prompt_template):
    purchase_hist = "\n".join([f"{i+1}. {row['title_meta']}: {row['description']}" for i, (_, row) in enumerate(recent_purchases.iterrows())])
    context = "\n".join(f"{doc.metadata['title_meta']}: {doc.page_content}" for doc in retrieved_docs)
    prompt = prompt_template.format(
        question=user_query,
        purchase_history=purchase_hist,
        liked_items="\n".join(like_items),
        disliked_items="\n".join(dislike_items),
        context=context
    )
    return llm(prompt)

In [ ]:
user_query = "beauty magazine that can provide beauty tips"
retrieved_docs = get_search_result(user_query, chroma_client, k=5)