In [10]:
# !pip install U langchain-huggingface lightfm langchain sentence-transformers faiss-cpu langchain_community datasets chromadb ragas

In [13]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
# from difflib import SequenceMatcher
from datasets import load_dataset
# from lightfm import LightFM
# from lightfm.data import Dataset
# from lightfm.cross_validation import random_train_test_split
# from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

user_data = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_CDs_and_Vinyl", split="full", trust_remote_code=True)
meta = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_CDs_and_Vinyl", split="full", trust_remote_code=True)

def flatten_lst(col):
    # flatten lists by joining their elements with a separator (e.g., ', ')
    col['features'] = ', '.join(col['features']) if isinstance(col['features'], list) else col['features']
    col['description'] = ', '.join(col['description']) if isinstance(col['description'], list) else col['description']
    col['categories'] = ', '.join(col['categories']) if isinstance(col['categories'], list) else col['categories']

    return col

flattened_meta = meta.map(flatten_lst)

user_df = user_data.to_pandas().fillna(0)
meta_df = flattened_meta.to_pandas().fillna(0)

/var/folders/1l/fxxxl8p13clcn13ph4b5wcjc0000gn/T/ipykernel_98464/603599614.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  meta_df = flattened_meta.to_pandas().fillna(0)

In [14]:
user_df.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,[],B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,0,True
1,5.0,Five Stars,LOVE!!,[],B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,0,True
2,3.0,Three Stars,Sad there is not the versions with the real/or...,[],B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,0,True
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,[],B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,3,True
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,[],B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,0,False

In [16]:
user_df['verified_purchase'] = user_df['verified_purchase'].astype(int)
user_df.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,[],B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,0,1
1,5.0,Five Stars,LOVE!!,[],B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,0,1
2,3.0,Three Stars,Sad there is not the versions with the real/or...,[],B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,0,1
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,[],B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,3,1
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,[],B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,0,0

In [17]:
user_df.groupby(['rating','verified_purchase']).size().reset_index().pivot(columns='rating', index='verified_purchase', values=0)

rating                1.0    2.0     3.0     4.0      5.0
verified_purchase
0                   81604  63704  117798  288213   996369
1                  106123  76853  165893  376301  2554415

In [21]:
meta_df.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Digital Music,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,12.05,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",SWV Format: Audio CD,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro...",B000002X4C,0,0,0
1,Digital Music,Rio Angie,5.0,1,,"Shrimp City Slim (aka Gary Erwin, b. 1953, Chi...",14.98,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Shrimp City Slim (Artist) Format: Audio CD,"CDs & Vinyl, Jazz, Avant Garde & Free Jazz","{""Product Dimensions"": ""5.6 x 0.4 x 4.9 inches...",B00902T10Y,0,0,0
2,Digital Music,Lost in Love,5.0,9,,,24.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Nastyboy Klick Format: Audio CD,"CDs & Vinyl, Rap & Hip-Hop, Gangsta & Hardcore","{""Package Dimensions"": ""4.7 x 4.6 x 0.1 inches...",B00000DALY,0,0,0
3,Digital Music,Somewhere in Time,4.8,1186,,The 1980 soundtrack to the now classic motion ...,11.55,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}","John Barry (Composer), Barry, John (Comp...","CDs & Vinyl, Soundtracks, Movie Scores","{""Is Discontinued By Manufacturer"": ""No"", ""Lan...",B0000086D1,0,0,0
4,Digital Music,Kimmon Waldruff,5.0,1,,Solo acoustic fingerstyle guitar.,14.07,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Kimmon Waldruff (Artist) Format: Audio CD,"CDs & Vinyl, Folk","{""Is Discontinued By Manufacturer"": ""No"", ""Pro...",B000S6W7KC,0,0,0

In [19]:
meta_df['main_category'].unique()

array(['Digital Music', 'Movies & TV', 'Cell Phones & Accessories',
       'Books', 'Musical Instruments', 'Tools & Home Improvement',
       'Amazon Home', 'All Electronics', 'Toys & Games',
       'Health & Personal Care', 'Office Products', 0, 'Software',
       'Home Audio & Theater', 'Video Games', 'Audible Audiobooks',
       'Industrial & Scientific', 'Grocery', 'All Beauty',
       'Arts, Crafts & Sewing', 'Sports & Outdoors', 'Pet Supplies',
       'Baby', 'Camera & Photo', 'Appliances', 'Computers',
       'AMAZON FASHION', 'Collectible Coins', 'Entertainment',
       'Automotive'], dtype=object)

In [20]:
meta_df['categories'].unique()

array(['CDs & Vinyl, Dance & Electronic, House',
       'CDs & Vinyl, Jazz, Avant Garde & Free Jazz',
       'CDs & Vinyl, Rap & Hip-Hop, Gangsta & Hardcore',
       'CDs & Vinyl, Soundtracks, Movie Scores', 'CDs & Vinyl, Folk',
       'CDs & Vinyl, International Music, South & Central America, Argentina',
       'CDs & Vinyl, Pop', 'CDs & Vinyl, Jazz, Swing Jazz',
       'CDs & Vinyl, Country', 'CDs & Vinyl, Classical, Chamber Music',
       'CDs & Vinyl, Rock, Progressive, Progressive Rock',
       'CDs & Vinyl, Pop, Oldies, Traditional Pop',
       'CDs & Vinyl, International Music, Pacific Islands, Hawaii',
       'CDs & Vinyl, Pop, Oldies', 'CDs & Vinyl, Folk, Contemporary Folk',
       'CDs & Vinyl, Rock, Hard Rock',
       'CDs & Vinyl, Broadway & Vocalists, Musicals',
       'CDs & Vinyl, Jazz, Bebop', 'CDs & Vinyl, Vinyl Store',
       'CDs & Vinyl, Jazz, Modern Postbebop',
       'CDs & Vinyl, Classical, Forms & Genres, Concertos',
       'CDs & Vinyl, Metal', 'CDs & Vinyl, Pop, Teen Pop',
       'CDs & Vinyl, New Age', "CDs & Vinyl, Country, Today's Country",
       'CDs & Vinyl, Classical, Forms & Genres, Theatrical, Incidental & Program Music',
       'CDs & Vinyl, International Music, Europe, British Isles, Britain',
       'CDs & Vinyl, Christian & Gospel', 'CDs & Vinyl, Classical',
       'CDs & Vinyl, International Music',
       "CDs & Vinyl, Today's Deals in Music, Christian & Gospel, Gospel, CDs $7 - $10",
       'CDs & Vinyl, Christian & Gospel, Gospel',
       'CDs & Vinyl, Jazz, Soul-Jazz & Boogaloo',
       'CDs & Vinyl, Christian & Gospel, Pop & Contemporary',
       'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Indie Rock',
       'CDs & Vinyl, Rock', 'CDs & Vinyl, Rap & Hip-Hop, Pop Rap',
       'CDs & Vinyl, Metal, Pop Metal',
       'CDs & Vinyl, International Music, Europe, Continental Europe, Germany',
       'CDs & Vinyl, Metal, Death Metal',
       'CDs & Vinyl, Pop, Oldies, Doo Wop',
       'CDs & Vinyl, Christian & Gospel, Gospel, Contemporary',
       'CDs & Vinyl, International Music, Europe, Eastern Europe, Poland',
       'CDs & Vinyl, Reggae, Dance Hall',
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Hardcore',
       'CDs & Vinyl, Classical, Forms & Genres, Theatrical, Incidental & Program Music, Incidental Music',
       'CDs & Vinyl, Classical, Symphonies',
       'CDs & Vinyl, Classical, Forms & Genres, Fantasies',
       'CDs & Vinyl, Latin Music, Latin Pop',
       'CDs & Vinyl, Classic Rock, Glam',
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, American Punk',
       'CDs & Vinyl, International Music, Middle East, Israel',
       'CDs & Vinyl, Pop, Dance Pop',
       'CDs & Vinyl, Pop, Adult Alternative', 'CDs & Vinyl, CD Rarities',
       'CDs & Vinyl, New Age, Instrumental',
       'CDs & Vinyl, Latin Music, Tejano',
       'CDs & Vinyl, Blues, Vocal Blues', 'CDs & Vinyl, Rap & Hip-Hop',
       'CDs & Vinyl, Jazz, Vocal Jazz',
       'CDs & Vinyl, Jazz, Traditional Jazz & Ragtime',
       'CDs & Vinyl, R&B, Soul',
       "CDs & Vinyl, Children's Music, Educational", 'CDs & Vinyl, Blues',
       'CDs & Vinyl, Folk, British & Celtic Folk, British Folk',
       'CDs & Vinyl, Country, Roadhouse Country',
       "CDs & Vinyl, Today's Deals in Music, Blues, Contemporary Blues, CDs Under $7",
       'CDs & Vinyl, Classical, Forms & Genres, Short Forms, Character Pieces',
       'CDs & Vinyl, Jazz, Cool Jazz',
       'CDs & Vinyl, Jazz, Swing Jazz, Classic Big Band',
       'CDs & Vinyl, Dance & Electronic, Electronica',
       "CDs & Vinyl, Christian & Gospel, Children's",
       'CDs & Vinyl, International Music, Europe, British Isles, Ireland',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Lullabies & Berceuse',
       'CDs & Vinyl, Indie & Alternative, New Wave & Post-Punk, New Wave',
       'CDs & Vinyl, Pop, Adult Contemporary',
       'CDs & Vinyl, Jazz, Smooth Jazz', 'CDs & Vinyl, Latin Music',
       "CDs & Vinyl, Today's Deals in Music, Rock, Rock Guitarists, CDs $7 - $10",
       'CDs & Vinyl, Latin Music, Salsa', 'CDs & Vinyl, Rock, Blues Rock',
       'CDs & Vinyl, Rock, Oldies & Retro, Rockabilly',
       'CDs & Vinyl, Soundtracks, Movie Soundtracks', 'CDs & Vinyl, Jazz',
       'CDs & Vinyl, New Age, Meditation',
       'CDs & Vinyl, International Music, Far East & Asia, Japan',
       'CDs & Vinyl, Indie & Alternative, Alternative Rock',
       'CDs & Vinyl, Pop, Easy Listening',
       'CDs & Vinyl, Country, Americana',
       'CDs & Vinyl, International Music, South & Central America, Brazil',
       "CDs & Vinyl, Children's Music",
       'CDs & Vinyl, Indie & Alternative, Goth & Industrial, Goth',
       'CDs & Vinyl, Pop, Vocal Pop',
       "CDs & Vinyl, Today's Deals in Music, Folk, Folk General, CDs Under $7",
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Garage Punk',
       'CDs & Vinyl, Blues, Regional Blues, Chicago Blues',
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk',
       'CDs & Vinyl, Blues, Contemporary Blues',
       'CDs & Vinyl, Jazz, Swing Jazz, Contemporary Big Band',
       "CDs & Vinyl, Today's Deals in Music, Dance & DJ, House, CDs $7 - $10",
       'CDs & Vinyl, Christian & Gospel, Accompaniment',
       'CDs & Vinyl, AutoRip',
       "CDs & Vinyl, Today's Deals in Music, Classical, Classical General, CDs $7 - $10",
       'CDs & Vinyl, Pop, Oldies, Girl Groups',
       'CDs & Vinyl, Blues, Regional Blues, Texas Blues',
       'CDs & Vinyl, Classical, Forms & Genres, Toccatas',
       'CDs & Vinyl, Verve Music Group, Impulse',
       "CDs & Vinyl, Today's Deals in Music, Pop, Adult Contemporary, CDs $7 - $10",
       'CDs & Vinyl, International Music, Europe, Eastern Europe, Polka',
       'CDs & Vinyl, Pop, Soft Rock',
       'CDs & Vinyl, International Music, Caribbean & Cuba, Cuba',
       "CDs & Vinyl, Today's Deals in Music, Broadway & Vocalists, Classic Vocalists, CDs $7 - $10",
       'CDs & Vinyl, Classical, Forms & Genres, Suites',
       'CDs & Vinyl, Holiday & Wedding, Christmas',
       'CDs & Vinyl, Classic Rock, Album-Oriented Rock (AOR)',
       'CDs & Vinyl, Indie & Alternative, Alternative Rock, American Alternative',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Oratorios',
       'CDs & Vinyl, Classic Rock',
       'CDs & Vinyl, International Music, Far East & Asia, Korea',
       'CDs & Vinyl, Jazz, Latin Jazz',
       "CDs & Vinyl, Today's Deals in Music, Pop, Vocal Pop, CDs $7 - $10",
       'CDs & Vinyl, Special Interest', 'CDs & Vinyl, Imports, Rock',
       "CDs & Vinyl, Today's Deals in Music, Soundtracks, Soundtracks General, CDs $7 - $10",
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Noels',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Requiems',
       'CDs & Vinyl, Classic Rock, Southern Rock',
       'CDs & Vinyl, International Music, North America',
       'CDs & Vinyl, International Music, Europe, Continental Europe, Italy',
       'CDs & Vinyl, R&B, Funk', 'CDs & Vinyl, Jazz, New Orleans Jazz',
       "CDs & Vinyl, Today's Deals in Music, Christian & Gospel, Christian General, CDs Under $7",
       'CDs & Vinyl, Reggae',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Chansons',
       'CDs & Vinyl, Classical, Forms & Genres, Serenades & Divertimentos',
       'CDs & Vinyl, R&B',
       "CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs $7 - $10",
       'CDs & Vinyl, Classical, Ballets & Dances, Baroque Dance Suites',
       'CDs & Vinyl, R&B, Contemporary R&B',
       'CDs & Vinyl, International Music, Europe, Continental Europe, Belgium',
       'CDs & Vinyl, International Music, Europe, Continental Europe',
       'CDs & Vinyl, Opera & Classical Vocal, Operettas',
       'CDs & Vinyl, Classic Rock, British Invasion',
       'CDs & Vinyl, International Music, Far East & Asia, China',
       'CDs & Vinyl, Country, Bluegrass',
       'CDs & Vinyl, International Music, Far East & Asia, Russia',
       'CDs & Vinyl, Rock, Progressive, Progressive Metal',
       'CDs & Vinyl, Rap & Hip-Hop, Experimental Rap',
       'CDs & Vinyl, Pop, Singer-Songwriters',
       'CDs & Vinyl, R&B, Quiet Storm',
       'CDs & Vinyl, Dance & Electronic, Ambient', 'CDs & Vinyl, Karaoke',
       'CDs & Vinyl, Blues, Piano Blues',
       "CDs & Vinyl, Today's Deals in Music, Pop, Pop Rock, CDs $7 - $10",
       "CDs & Vinyl, Children's Music, Lullabies",
       'CDs & Vinyl, Blue Note Records',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Cantatas',
       'CDs & Vinyl, Blues, Acoustic Blues',
       'CDs & Vinyl, International Music, South & Central America, Brazil, Bossa Nova',
       'CDs & Vinyl, Christian & Gospel, Country & Bluegrass',
       'CDs & Vinyl, Folk, British & Celtic Folk, Irish Folk',
       'CDs & Vinyl, Dance & Electronic',
       'CDs & Vinyl, Classical, Ballets & Dances, Ballets',
       'CDs & Vinyl, Imports, Hard Rock & Metal',
       'CDs & Vinyl, International Music, India & Pakistan',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Anthems',
       'CDs & Vinyl, R&B, Soul, Southern Soul',
       "CDs & Vinyl, Today's Deals in Music, Rock, Rock General",
       "CDs & Vinyl, Today's Deals in Music, Country, Country General, CDs $7 - $10",
       "CDs & Vinyl, Today's Deals in Music, Dance & DJ, Disco, CDs Under $7",
       'CDs & Vinyl, Latin Music, Latin Hip-Hop',
       'CDs & Vinyl, International Music, Europe, Continental Europe, France',
       "CDs & Vinyl, Today's Deals in Music, R&B, Soul",
       'CDs & Vinyl, Pop, Oldies, Bubblegum',
       'CDs & Vinyl, Opera & Classical Vocal',
       'CDs & Vinyl, Special Interest, Exercise',
       'CDs & Vinyl, Folk, Traditional Folk',
       'CDs & Vinyl, Classical, Forms & Genres, Short Forms, Nocturnes',
       'CDs & Vinyl, Imports, Classical',
       'CDs & Vinyl, Dance & Electronic, Disco',
       'CDs & Vinyl, Indie & Alternative, Goth & Industrial, Industrial, Alt Industrial',
       "CDs & Vinyl, Today's Deals in Music, Country, Country General, CDs Under $7",
       'CDs & Vinyl, Rap & Hip-Hop, East Coast',
       "CDs & Vinyl, Today's Deals in Music, World Music, Mexico, CDs $7 - $10",
       'CDs & Vinyl, Dance & Electronic, Trip-Hop',
       'CDs & Vinyl, International Music, South & Central America',
       "CDs & Vinyl, Today's Deals in Music, R&B, R&B General, CDs $7 - $10",
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Proto Punk',
       'CDs & Vinyl, International Music, Europe, Scandinavia, Sweden',
       'CDs & Vinyl, Pop, Tributes', 'CDs & Vinyl, Holiday & Wedding',
       'CDs & Vinyl, International Music, Europe, Scandinavia, Finland',
       'CDs & Vinyl, Latin Music, Norteño',
       'CDs & Vinyl, Broadway & Vocalists, Traditional Vocal Pop',
       'CDs & Vinyl, Country, Classic Country, Nashville Sound',
       "CDs & Vinyl, Today's Deals in Music, Jazz, Jazz General, CDs $7 - $10",
       "CDs & Vinyl, Today's Deals in Music, Rock, Oldies & Retro",
       'CDs & Vinyl, Blues, Regional Blues, Delta Blues',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Hymns',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Songs & Lieder, Folk Songs',
       'CDs & Vinyl, Putumayo World Music Store, Dance & DJ',
       'CDs & Vinyl, Pop, Oldies, Baroque Pop',
       'CDs & Vinyl, R&B, Soul, Blue-Eyed Soul',
       "CDs & Vinyl, Today's Deals in Music, Dance & DJ, Dance General, CDs $7 - $10",
       'CDs & Vinyl, Country, Classic Country, Bakersfield Sound',
       'CDs & Vinyl, Metal, Alternative Metal',
       'CDs & Vinyl, Soundtracks',
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Emo',
       'CDs & Vinyl, International Music, North America, Native American',
       'CDs & Vinyl, Comedy & Spoken Word, Spoken Word',
       "CDs & Vinyl, Today's Deals in Music, Children's Music, All Bargain Titles",
       'CDs & Vinyl, International Music, South & Central America, Colombia',
       'CDs & Vinyl, International Music, Caribbean & Cuba, Dominican Republic',
       'CDs & Vinyl, Country, Classic Country',
       'CDs & Vinyl, International Music, Caribbean & Cuba, Jamaica',
       'CDs & Vinyl, Blues, Traditional Blues',
       'CDs & Vinyl, Special Interest, Instructional',
       'CDs & Vinyl, Dance & Electronic, Techno',
       'CDs & Vinyl, Dance & Electronic, Drum & Bass',
       "CDs & Vinyl, Today's Deals in Music, Broadway & Vocalists, Traditional Vocal Pop, CDs Under $7",
       'CDs & Vinyl, Classic Rock, Psychedelic Rock',
       'CDs & Vinyl, Classical, Forms & Genres, Sonatas, Sonatinas',
       'CDs & Vinyl, Rock, Rock Guitarists',
       'CDs & Vinyl, Rock, Oldies & Retro, Surf Rock',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Motets',
       'CDs & Vinyl, Jazz, Jazz Fusion',
       'CDs & Vinyl, Blues, Electric Blues',
       'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Jangle Pop',
       'CDs & Vinyl, Classical, Ballets & Dances, Polkas',
       'CDs & Vinyl, Comedy & Spoken Word, Comedic Music',
       'CDs & Vinyl, Rock, Folk Rock',
       'CDs & Vinyl, International Music, Europe, Eastern Europe',
       'CDs & Vinyl, Classical, Forms & Genres, Theatrical, Incidental & Program Music, Tone Poems',
       'CDs & Vinyl, Dance & Electronic, Freestyle',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Songs & Lieder',
       'CDs & Vinyl, Broadway & Vocalists, Cabaret',
       "CDs & Vinyl, Today's Deals in Music, Latin Music, Latin Pop, CDs $7 - $10",
       "CDs & Vinyl, Today's Deals in Music, Country, Country General",
       'CDs & Vinyl, Rock, Power Pop',
       "CDs & Vinyl, Today's Deals in Music, Miscellaneous, Holiday Music, CDs $7 - $10",
       'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Ambient Pop',
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk',
       'CDs & Vinyl, New Age, Healing',
       "CDs & Vinyl, Today's Deals in Music, Alternative Rock, Alternative General, CDs $7 - $10",
       'CDs & Vinyl, Rock, Country Rock',
       "CDs & Vinyl, Today's Deals in Music, Pop, Pop General, CDs Under $7",
       'CDs & Vinyl, Opera & Classical Vocal, Arias',
       'CDs & Vinyl, International Music, Far East & Asia',
       'CDs & Vinyl, Holiday & Wedding, Hanukkah',
       'CDs & Vinyl, Blues, Regional Blues, Cajun & Zydeco',
       'CDs & Vinyl, International Music, Australia & New Zealand',
       'CDs & Vinyl, Classical, Ballets & Dances, Dances',
       "CDs & Vinyl, Today's Deals in Music, Rap & Hip-Hop, Rap & Hip-Hop General, CDs $7 - $10",
       "CDs & Vinyl, Today's Deals in Music, Broadway & Vocalists, Traditional Vocal Pop, CDs $7 - $10",
       'CDs & Vinyl, Christian & Gospel, Praise & Worship',
       'CDs & Vinyl, harmonia mundi usa',
       'CDs & Vinyl, International Music, Europe, Eastern Europe, Hungary',
       'CDs & Vinyl, International Music, Europe, Scandinavia, Norway',
       "CDs & Vinyl, Today's Deals in Music, Dance & DJ, Dance General, CDs Under $7",
       'CDs & Vinyl, International Music, Caribbean & Cuba, Cuba, Charanga',
       "CDs & Vinyl, Today's Deals in Music, Rock, Rock General, CDs $7 - $10",
       'CDs & Vinyl, Reggae, Jamaican Ska', 'CDs & Vinyl, Rhino Records',
       'CDs & Vinyl, International Music, Africa, Ghana',
       "CDs & Vinyl, Today's Deals in Music, Christian & Gospel, Christian General, Tapes Under $6",
       'CDs & Vinyl, Rock, Jam Bands',
       'CDs & Vinyl, Classical, Forms & Genres, Preludes',
       'CDs & Vinyl, Latin Music, Bachata',
       'CDs & Vinyl, Comedy & Spoken Word, Country Comedy',
       'CDs & Vinyl, Rock, Roots Rock',
       'CDs & Vinyl, International Music, Caribbean & Cuba, Trinidad',
       'CDs & Vinyl, R&B, Soul, Northern',
       'CDs & Vinyl, International Music, Africa, South Africa',
       'CDs & Vinyl, International Music, Europe, Continental Europe, Greece',
       "CDs & Vinyl, Today's Deals in Music, Classical, Classical General, CDs Under $7",
       'CDs & Vinyl, Classical, Forms & Genres, Sonatas',
       'CDs & Vinyl, Comedy & Spoken Word',
       "CDs & Vinyl, Today's Deals in Music, Classic Rock, Album-Oriented Rock (AOR), CDs $7 - $10",
       'CDs & Vinyl, Rock, Progressive',
       'CDs & Vinyl, Jazz, Traditional Jazz & Ragtime, Ragtime',
       'CDs & Vinyl, Classical, Forms & Genres, Theatrical, Incidental & Program Music, Marches',
       'CDs & Vinyl, Latin Music, Latin Rock',
       'CDs & Vinyl, Classic Rock, Arena Rock',
       'CDs & Vinyl, International Music, Europe, Continental Europe, Spain',
       'CDs & Vinyl, Christian & Gospel, Gospel, Southern',
       'CDs & Vinyl, R&B, Classic R&B',
       'CDs & Vinyl, International Music, South & Central America, Brazil, Afro Brazilian',
       'CDs & Vinyl, Dance & Electronic, Dubstep',
       'CDs & Vinyl, Soundtracks, Television Soundtracks',
       'CDs & Vinyl, Dance & Electronic, Big Beat',
       'CDs & Vinyl, Latin Music, Tango',
       'CDs & Vinyl, Blues, Regional Blues, East Coast Blues',
       "CDs & Vinyl, Today's Deals in Music, Jazz, Jazz General, CDs Under $7",
       'CDs & Vinyl, Folk, Jewish & Yiddish',
       "CDs & Vinyl, Today's Deals in Music, R&B, R&B General, Tapes Under $6",
       'CDs & Vinyl, Dance & Electronic, World Dance',
       'CDs & Vinyl, Rock, Progressive, Electronic',
       'CDs & Vinyl, Rock, Rock Guitarists, Guitar Gods',
       'CDs & Vinyl, New Age, Relaxation',
       'CDs & Vinyl, Comedy & Spoken Word, Stand-Up Comedy',
       "CDs & Vinyl, Today's Deals in Music, New Age, New Age General, CDs $7 - $10",
       'CDs & Vinyl, Blues, Regional Blues, New York Blues',
       "CDs & Vinyl, Today's Deals in Music, Country, Country General, Tapes Under $6",
       "CDs & Vinyl, Today's Deals in Music, Dance & DJ, Dance General",
       'CDs & Vinyl, Classical, Forms & Genres, Ballads',
       'CDs & Vinyl, Classical, Sacred & Religious, Voluntaries',
       'CDs & Vinyl, Indie & Alternative, Hardcore & Punk, Punk-Pop',
       'CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi, Chamber Pop',
       'CDs & Vinyl, Indie & Alternative, Alternative Rock, British Alternative, Britpop',
       'CDs & Vinyl, Imports, Soundtracks', 'CDs & Vinyl, Reggae, Dub',
       "CDs & Vinyl, Today's Deals in Music, World Music, Mexico, CDs Under $7",
       'CDs & Vinyl, International Music, Europe, British Isles, Scotland',
       'CDs & Vinyl, Blues, Regional Blues, Memphis Blues',
       'CDs & Vinyl, Christian & Gospel, Rock & Alternative',
       'CDs & Vinyl, Classical, Forms & Genres, Short Forms, Impromptus',
       'CDs & Vinyl, Universal Music Group',
       'CDs & Vinyl, Country, Classic Country, Old-Time Country',
       'CDs & Vinyl, R&B, Motown',
       'CDs & Vinyl, Christian & Gospel, Gospel, Choir',
       'CDs & Vinyl, Dance & Electronic, Trance',
       "CDs & Vinyl, Today's Deals in Music, Hard Rock & Metal, Hard Rock, CDs Under $7",
       "CDs & Vinyl, Today's Deals in Music, R&B, R&B General, CDs Under $7",
       'CDs & Vinyl, Blues, Regional Blues, New Orleans Blues',
       'CDs & Vinyl, Rock, Oldies & Retro',
       "CDs & Vinyl, Today's Deals in Music, World Music, Caribbean & Cuba, CDs Under $7",
       'CDs & Vinyl, Metal, Thrash & Speed Metal',
       "CDs & Vinyl, Children's Music, Disney",
       "CDs & Vinyl, Today's Deals in Music, Jazz, Vocal Jazz, CDs Under $7",
       'CDs & Vinyl, Rap & Hip-Hop, West Coast',
       'CDs & Vinyl, Opera & Classical Vocal, Vocal Non-Opera, Songs & Lieder, Madrigals',
       'CDs & Vinyl, Dance & Electronic, Turntablists',
       'CDs & Vinyl, Pop, Euro Pop',
       'CDs & Vinyl, International Music, Europe, Continental Europe, Netherlands',
       'CDs & Vinyl, International Music, Africa, Mali',
       "CDs & Vinyl, Today's Deals deprecated",
       'CDs & Vinyl, Imports, Dance & Electronic',
       'CDs & Vinyl, Christian & Gospel, Hard Rock & Metal',

In [7]:
# drop cols dont provide contextual meaning
# user_df = user_df.drop(['images'], axis='columns')
# user_df

,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,0,True
1,5.0,Five Stars,LOVE!!,B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,0,True
2,3.0,Three Stars,Sad there is not the versions with the real/or...,B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,0,True
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,3,True
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,0,False
...,...,...,...,...,...,...,...,...,...
4827268,5.0,good cd,I love this cd and love the movie thank u I ha...,B000002VPH,B000002VPH,AHM36UEBOF2I6VH7CGAGHCDDUITQ,1308413175000,0,True
4827269,5.0,hot cd,I love the cd it play real well and was delive...,B000084T18,B000084T18,AHM36UEBOF2I6VH7CGAGHCDDUITQ,1308412875000,0,True
4827270,5.0,Superb sounding remaster,Such a great remaster you can fully appreciate...,B004OFWLO0,B004OFWLO0,AHRJPHOI5JHYEQVSDMNX6736QH3Q,1505425559120,1,True
4827271,1.0,"Very, very disappointing.",What this CD is lacking is a heart. The music...,B000GIXIAK,B000GIXIAK,AH4PJ73QN75AJM5VSCT53AOADCGA,1157470110000,6,False
4827272,5.0,Unexpectedly Good!,I am VERY impressed with this album as I was e...,B0001ADALU,B0001ADALU,AH4PJ73QN75AJM5VSCT53AOADCGA,1077661382000,6,False

In [8]:
# drop cols dont provide contextual meaning
meta_df = meta_df.drop(['main_category', 'images', 'videos', 'store', 'price', 'bought_together', 'subtitle', 'author'], axis='columns')

In [9]:
# merge df vs meta
merged_df = user_df.merge(meta_df, on='parent_asin', how='right', suffixes=('', '_meta'))
merged_df = merged_df.rename(columns={'title': 'title_review'})
merged_df['timestamp'] = pd.to_datetime(merged_df['timestamp'], unit='ms')
merged_df.head(5)

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,title_meta,average_rating,rating_number,features,description,categories,details
0,1.0,Weak,Definitely the weakest of the three albums SWV...,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,2015-01-03 06:22:17,1.0,False,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
1,1.0,Too Many Guest Spots,Unlike It's About Time and New Beginning this ...,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,2013-09-16 20:19:59,1.0,True,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
2,4.0,"When &quot;Tension&quot; is released, expect q...","Their third and final album as a group, &quot;...",B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,2000-03-19 00:44:40,1.0,False,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
3,5.0,Thanks,thank you,B000002X4C,B000002X4C,AE73R3KLFKXFNWUBOA4JCLT5UWKA,2015-03-27 18:15:21,0.0,True,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."
4,2.0,Release Some Tension - 2.5 stars,When I was trying to decide whether or not to ...,B000002X4C,B000002X4C,AFICHVZ62IFAWIBZK3U6B7NZWAVQ,2010-11-13 08:44:58,3.0,False,Release Some Tension,4.6,112,,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro..."

In [10]:
# filter merge_df with rating >= 3
merged_df['like'] = merged_df['rating'] > 3

# data.drop_duplicates(subset=['asin'])

In [11]:
# encode user_id and asin
merged_df['user_id_encoded'] = LabelEncoder().fit_transform(merged_df['user_id'])
merged_df['asin_encoded'] = LabelEncoder().fit_transform(merged_df['asin'])
merged_df['parent_asin_encoded'] = LabelEncoder().fit_transform(merged_df['parent_asin'])

# data partition
# merged_df = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)
df_train, df_test = train_test_split(merged_df, test_size=0.2, random_state=42)
train_interactions_set = set(zip(df_train['user_id_encoded'], df_train['asin_encoded']))
df_test = df_test[~df_test[['user_id_encoded', 'asin_encoded']].apply(tuple, axis=1).isin(train_interactions_set)]

In [12]:
# lightfm
dataset = Dataset()
dataset.fit(users= merged_df['user_id_encoded'], items = merged_df['asin_encoded'])
train_interactions, train_w = dataset.build_interactions((row['user_id_encoded'], row['asin_encoded']) for id, row in df_train.iterrows())
test_interactions, test_w = dataset.build_interactions((row['user_id_encoded'], row['asin_encoded']) for id, row in df_test.iterrows())

NameError: name 'Dataset' is not defined

In [ ]:
model = LightFM(loss='warp', item_alpha=1e-6, user_alpha=1e-6)
# train model
model.fit(train_interactions, epochs=50, num_threads=2, sample_weight=train_w)

In [ ]:
def add_combined_text(row):
    combined_text = f"title_review: {str(row['title_review'])}, text: {str(row['text'])}, title_meta: {str(row['title_meta'])}, features: {str(row['features'])}, description: {str(row['description'])}, details: {str(row['details'])}, categories: {str(row['categories'])}"
    row['combined_text'] = combined_text
    return row

# data = merged_df.map(add_combined_text)
merged_df = merged_df.apply(add_combined_text, axis=1)
# combined_texts = merged_df["combined_text"]
merged_df

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,title_meta,...,rating_number,features,description,categories,details,like,user_id_encoded,asin_encoded,parent_asin_encoded,combined_text
0,3.0,Three Stars,all advertizements,B00FA7T630,B00FA7T630,AFNRZBYAPLFKJNJU5BK3TTRWHJ6A,2015-10-26 17:49:26.000,0,1,GQ Print Access Print Magazine,...,10,,"Product Description, Dive into, GQ, ’s culture...",,"{""Date First Available"": ""June 2, 2020"", ""Manu...",False,24328,2499,2499,"title_review: Three Stars, text: all advertize..."
1,5.0,A great audiophile audio magazine that covers ...,A great audiophile audio magazine that covers ...,B00F8P62PO,B00F8P62PO,AETSCPCEEZ3S3BGNU4WCIN4H62ZQ,2018-01-11 07:17:33.014,6,1,Hi-Fi + Print Magazine,...,44,,Hi-Fi+ is Europe's premier English-language hi...,"Magazine Subscriptions, Arts, Music & Photogra...","{""Date First Available"": ""September 19, 2013"",...",True,12133,2498,2498,title_review: A great audiophile audio magazin...
2,3.0,inspirational,i really like the ideas they have in this maga...,B003F1W9T6,B003F1W9T6,AGQCHHMSO6S2DJLWGGFLCVUY477Q,2011-12-24 03:36:48.000,2,1,Paper Crafts,...,3,,,,"{""Date First Available"": ""May 12, 2021""}",False,40505,2095,2095,"title_review: inspirational, text: i really li..."
3,2.0,Should be called card making,"I ordered this magazine because I enjoy ""paper...",B003F1W9T6,B003F1W9T6,AEIKS6KU32T7VBIAP7YIMR2LICQQ,2013-03-03 05:28:59.000,0,1,Paper Crafts,...,3,,,,"{""Date First Available"": ""May 12, 2021""}",False,6799,2095,2095,"title_review: Should be called card making, te..."
4,4.0,Four Stars,Son loves this,B00007AXX1,B00007AXX1,AGDDHCNIGZPKBQRST6UVTCVPD53A,2015-12-04 12:24:30.000,0,1,Horse Illustrated,...,284,,,"Magazine Subscriptions, Sports, Recreation & O...","{""Package Dimensions"": ""10.79 x 8.11 x 0.31 in...",True,34411,871,871,"title_review: Four Stars, text: Son loves this..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71492,1.0,"Beautiful fashion magazine, subscription never...",I have been subscribing to V for a few years n...,B0007INIGI,B0007INIGI,AFDU3G7WMDWWA2XJLYNQLHSIEZMQ,2012-03-01 16:47:32.000,1,1,V Magazine - Ny Print Magazine,...,5,,"V Magazine, was launched in September 1999 as ...","Magazine Subscriptions, Fashion & Style, Men","{""Date First Available"": ""September 14, 2006"",...",False,19700,1315,1315,"title_review: Beautiful fashion magazine, subs..."
71493,1.0,What a fiasco,I subscribed to this magazine a year ago and n...,B0002800W8,B0002800W8,AG5BWPCEIS6FEJKQZTLJVQLGQNGA,2007-09-05 15:08:34.000,2,0,Victorian Review Print Magazine,...,1,,"Published since 1972,, Victorian Review, is an...",,"{""Date First Available"": ""September 14, 2006"",...",False,31564,1248,1248,"title_review: What a fiasco, text: I subscribe..."
71494,1.0,Have yet to receive the first issue,It has been a month since I purchased this mag...,B00007L0RC,B00007L0RC,AHA6K63RE5ODXSTDNPRND73U3EMQ,2011-02-15 16:55:54.000,0,1,Visto Print Magazine,...,2,,"A news magazine targeted at the wider public, ...",,"{""Date First Available"": ""September 15, 2013"",...",False,47920,1032,1032,title_review: Have yet to receive the first is...
71495,4.0,Super Fast Delivery,I was totally surprised how fast I received th...,B00007L0RC,B00007L0RC,AGQT3FF5NHZUOS3YSEAMIRY65VRQ,2012-01-18 22:58:43.000,0,1,Visto Print Magazine,...,2,,"A news magazine targeted at the wider public, ...",,"{""Date First Available"": ""September 15, 2013"",...",True,40744,1032,1032,"title_review: Super Fast Delivery, text: I was..."
71496,5.0,Five Stars,Don't remember buying this but I am sure it is...,B017L2BFQC,B017L2BFQC,AFBE73KK74B6YSG333PPIPCUBYKA,2018-03-03 16:04:21.386,0,1,Modern Pioneer Print Magazine,...,4,,,"Magazine Subscriptions, Sports, Recreation & O...","{""Date First Available"": ""November 4, 2015"", ""...",True,18564,2860,2860,"title_review: Five Stars, text: Don't remember..."

In [ ]:
def get_purchase_history(merged_df, user_id, k):
    user_hist = merged_df[merged_df['user_id_encoded']==user_id]
    user_hist_sorted = user_hist.sort_values(by='timestamp', ascending=False)
    recent_purchase = user_hist_sorted[['asin', 'title_meta', 'description', 'combined_text']].head(k)
    return recent_purchase

def get_like_items(merged_df, user_id):
    like_items = merged_df[(merged_df['user_id_encoded']==user_id) & (merged_df['like']==True)].sort_values(by='timestamp', ascending=False)
    like_items = like_items[['asin', 'title_meta', 'description']].iloc[:10]
    return like_items

def get_dislike_items(merged_df, user_id):
    dislike_items = merged_df[(merged_df['user_id_encoded']==user_id) & (merged_df['like']==False)].sort_values(by='timestamp', ascending=False)
    dislike_items = dislike_items[['asin', 'title_meta', 'description']].iloc[:10]
    return like_items

In [ ]:
def evaluate_recall(model, train_interactions, test_interactions, k):
    precision= precision_at_k(model, test_interactions, train_interactions=train_interactions, k=k).mean()
    recall= recall_at_k(model, test_interactions, train_interactions=train_interactions, k=k).mean()
    auc= auc_score(model, test_interactions, train_interactions=train_interactions).mean()
    return precision, recall, auc

eval_metrics = evaluate_recall(model, train_interactions, test_interactions, k=50)

In [ ]:
print(eval_metrics)

(0.010412165, 0.20115773521154753, 0.85380054)

In [ ]:
def get_top_k(model, dataset, merged_df, user_id, k):
    n_users, n_items = dataset.interactions_shape()

    user_ids = np.full(n_items, user_id)  # or use np.repeat(user_id, n_items)
    # item_ids = np.arange(n_items)
    interacted_items = set(merged_df[merged_df['user_id_encoded']==user_id]['asin_encoded'])

    scores = model.predict(user_ids, np.arange(n_items))
    scores[list(interacted_items)] = -np.inf

    top_items_encoded = np.argsort(-scores)[:k]
    asin_info = dict(zip(merged_df['asin_encoded'], zip(merged_df['asin'], merged_df['title_meta'], merged_df['combined_text'])))
    recs = [asin_info[item] for item in top_items_encoded if item in asin_info]
    return recs

# user_id_encoder = dict(zip(merged_df['user_id_encoded'], merged_df['user_id']))
recs_dict = {user_id: get_top_k(model, dataset, merged_df, user_id, k=50) for user_id in merged_df['user_id_encoded'].unique()}

def get_recs(user_id):
    return recs_dict.get(user_id, [])

In [ ]:
user_id_test = merged_df['user_id_encoded'].iloc[8]
recent_purchases = get_purchase_history(merged_df, user_id_test, k=10)
like_items = get_like_items(merged_df, user_id_test)
dislike_items = get_dislike_items(merged_df, user_id_test)
top_k_recs= get_recs(user_id_test)

In [ ]:
top_k_recs

[('B00007B1JS',
  'Soap Opera Digest',
  'title_review: Subscription, text: I am unable to review this magazine  I have never received an issue.<br /><br />Needless to say, I am not happy about this.<br /><br />Lynda Epler, title_meta: Soap Opera Digest, features: , description: , details: {"Date First Available": "April 30, 2015"}, categories: Magazine Subscriptions, Entertainment & Pop Culture, Television'),
 ('B00GBJIEQG',
  'Inked',
  'title_review: Five Stars, text: Great magazine, title_meta: Inked, features: , description: , details: {"Date First Available": "October 31, 2013"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Arts, Photography'),
 ('B00007EN1O',
  'Alpaca    Print Magazine',
  'title_review: Excellent publication about alpacas, text: This magazine is a must for any alpaca owner, would be alpaca owner, or one who is just learning about these beautiful animals.<br />It is beautifully done, showing pictures of alpacas,advertisements for alpaca farms, as well as very well-written articles.<br />The articles are timely and of great interest and learning tools for alpaca owners., title_meta: Alpaca    Print Magazine, features: , description: , details: {}, categories: '),
 ('B00005N7T1',
  'Teddy Bear and Friends    Print Magazine',
  'title_review: gift, text: I love ti so much it was a great gift and a surprise. I just had it renewed.again this year, title_meta: Teddy Bear and Friends    Print Magazine, features: , description: Teddy Bear & Friends is an art magazine for adult teddy bear collectors. Content includes artist and manufacturer profiles, secondary market pricing, convention coverage and calendars, and crafting patterns and tips. Along with coverage of collectible teddy bears, attention is given to other plush animals (friends) and to miniature teddy bears. Teddy Bear & Friends sponsors the TOBY program, an annual awards program in which plush creations are judged first by industry experts and then readers, honors the best of artist and manufactured teddy bears and friends in the industry. While Teddy Bear & Friends is mainly a consumer publication, it is also read as a trade magazine by retailers, artists, show promoters, and other members of the bear industry., details: {"Date First Available": "September 14, 2006", "Manufacturer": "JP Media LLC"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Arts, Crafts & Collectibles'),
 ('B00XDAH85O',
  'NEWSWEEK SPECIAL    Print Magazine',
  'title_review: Five Stars, text: The &#34;Dead&#34; are a legend!, title_meta: NEWSWEEK SPECIAL    Print Magazine, features: , description: Newsweek Special Issues celebrates the storied and legendary rock & roll band the Grateful Dead. Born in 1965 during the rise of counterculture, the Dead, as they are forever known, revolutionized music with their unique blend of rock, blues, folk, bluegrass, reggae, country, psychedelic and more. Fifty years later, the surviving members of the band—Mickey Hart, Bill Kreutzmann, Phil Lesh and Bob Weir—will take the stage together for their final concerts, Fare Thee Well. Produced in partnership with these living legends, this fully illustrated, 100-page special issue brings you a celebration of the peerless band to commemorate their 50th anniversary and the 20th anniversary of the death of their celebrated frontman and guitarist, Jerry Garcia., details: {"Package Dimensions": "8 x 0.5 x 0.2 inches; 11.2 Ounces", "Date First Available": "May 8, 2015", "Manufacturer": "Media Lab Publishing"}, categories: '),
 ('B01N2JMFXE',
  "Harper's Bazaar    Print Magazine",
  'title_review: Misleading, text: Beware! I didn’t receive all the issues, title_meta: Harper\'s Bazaar    Print Magazine, features: , description: Harper?s BAZAAR, the fashion authority, brings you the latest new looks from the hottest designers. You?ll get 12 beautiful issues a year full of best dressed secrets, must-haves and great finds. Experience the best in style and beauty with Harper?s BAZAAR., details: {"Date First Available": "November 21, 2016", "Manufacturer": "Hearst Magazines"}, categories: Magazine Subscriptions, Fashion & Style, Men'),
 ('B002NM7VNM',
  'Log Home Living',
  'title_review: Where\'s the magazine???!!!, text: STILL WAITING!!!  Purchased it over a month ago and haven\'t gotten it yet.  Is everything done by hand in these companies?  Why is it taking so long???  Oh, well, I\'ll let you know when I know., title_meta: Log Home Living, features: , description: , details: {"Date First Available": "September 3, 2009"}, categories: Magazine Subscriptions, Home & Garden, Design & Decoration'),
 ('B00F8P2VOK',
  'New Pioneer    Print Magazine',
  'title_review: Five Stars, text: great Magazine, wish there was more than just 4 issues., title_meta: New Pioneer    Print Magazine, features: , description: , details: {"Date First Available": "September 19, 2013", "Manufacturer": "Harris Publications"}, categories: '),
 ('B0000EI1K6',
  'Franchise Handbook    Print Magazine',
  'title_review: One Star, text: Poor information wrong numbers etc<br />Ex McDonalds pricing now is less than ten years ago I think not, title_meta: Franchise Handbook    Print Magazine, features: , description: The Franchise Handbook provides information about franchises available for purchase, costs to expect and other details about owning a franchise. The book outlines 1,700+ franchises, and listings are arranged alphabetically both by type of business and company name., details: {"Date First Available": "September 18, 2006", "Manufacturer": "Enterprise Magazines Inc"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Economics & Economic Theory'),
 ('B01I9FTYR2',
  "Woman's Day    Print Magazine",
  'title_review: Five Stars, text: Great, title_meta: Woman\'s Day    Print Magazine, features: , description: , details: {"Date First Available": "July 11, 2016"}, categories: '),
 ('B00CRPCWEI',
  'Simple Things',
  'title_review: A Trip to the UK, text: This is an amazing and beautiful magazine. I have subscribed to it for years. I’ve enjoyed articles on stone circles, historic bathhouses, nature, and recipes. Unfortunately, American mail service changed about 6 months ago. It now takes at least 3 months to receive an issue. Before that, they came within a week to a month., title_meta: Simple Things, features: , description: , details: {"Date First Available": "May 14, 2013"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Psychology'),
 ('B00005N7T6',
  'The Saturday Evening Post',
  'title_review: Not Worth The Price of a Subscription, text: As an aficionado of all things historic, old, and traditional, I subscribed to "The Saturday Evening Post." I was disappointed by what I received. With the exception of the excellent illustrations by Norman Rockwell, the magazine was largely advertisements for prescription medications and puff pieces about popular actors, authors, and other celebrities. This is not a worthy heir to the legacy of its founder, Benjamin Franklin, and the many gifted and talented individuals who have been associated with the magazine throughout its history. Simply put, it was not worth the price of a subscription., title_meta: The Saturday Evening Post, features: , description: , details: {"Date First Available": "September 14, 2006"}, categories: Magazine Subscriptions, Travel, City & Regional, United States, Midwest'),
 ('B005ML7WLM',
  'Man Magnum    Print Magazine',
  'title_review: Just fun reading. If you really want to put yourself ..., text: Disclosure:  I have written and published in Man Magnum.  An Alaskan hunting in Africa.  The magazine is a rich taste of hunting in Africa, and the real deal.  Think of this as Outdoor Life back in the 40\'s, 50\'s and 60\'s, but African.  Just fun reading.  If you really want to put yourself into Africa... and its adventures... this is the magazine for you., title_meta: Man Magnum    Print Magazine, features: , description: Magnum is Africa s oldest and leading magazine for hunters and shooters. Subjects include wingshooting, gundogs, rifles, shotguns, handguns, personal defence, ammo, ballistics, hand-loading, military weapons, antiques, muzzle-loaders, history, big game hunting and more. All with an African flavour., details: {"Date First Available": "September 14, 2011", "Manufacturer": "Media 24"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Baseball'),
 ('B002PXVZHM',
  'Gun Dog',
  'title_review: Great magazine for bird dog owners, hunters and nonhunters alike, text: If you own a bird dog breed, get this magazine. 70% of the articles involve dog training, dog health and wellness, and dog behavior of gun dogs written by professional dog trainers and veterinarians. Even if you aren\'t a hunter but own a bird dog breed, get a subscription to this magazine. You will learn so much about your dog. If you are a hunter, they also have articles about hunting areas throughout the USA., title_meta: Gun Dog, features: , description: , details: {"Date First Available": "September 22, 2009"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Hunting & Firearms'),
 ('B00006K8S5',
  'Christian-New Age Quarterly    Print Magazine',
  'title_review: A Breath of Fresh Air, text: Having been raised a Christian a long, long time ago -- but now more a student of Buddhism and other new edge philosophies -- I must admit I initially had doubts about reading this publication.  However, since subscribing to  Christian*New Age Quarterly about a year ago, I have found every issue to be just the right blend of traditional theology and new age ideas.<br /><br />Catherine Groves has the ability to attract some of the most insightful writers on the subjects at hand -- and the discourse that results has always been helpful to me.  (Coincidentally enough, each issue always seems to have some particle of wisdom or truth that focuses on an issue going on in my own life as I am reading it.<br /><br />So it\'s easy for me to see why this publication has been going strong for 20 years -- its brilliant ideas and polished writing make it a worthy companion to any other spiritual books you have in your library today.<br /><br />And after a grueling day in the "real world", reading C*NAQ can be a breath of fresh air!, title_meta: Christian-New Age Quarterly    Print Magazine, features: , description: Devoted to goodwill dialog, Christian*New Age Quarterly explores the differences between and common ground of Christianity and alternative spiritualities. Top-quality articles, sound scholarship and lively columns make this a genuine interfaith bridge - as entertaining as it is thought-provoking., details: {"Date First Available": "March 2, 2010", "Manufacturer": "Christian-New Age Quarterly"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Religion & Spirituality'),
 ('B000EGCIW8',
  'Coastal Living    Print Magazine',
  'title_review: get it, text: good deal, title_meta: Coastal Living    Print Magazine, features: , description: , details: {"Date First Available": "April 30, 2015"}, categories: Magazine Subscriptions, Travel, City & Regional'),
 ('B0000A8YW4',
  'Watercolor Artist',
  'title_review: A favorite!, text: I look forward to every issue of this magazine. It has great information and beautiful illustrations. Getting copies in both paper form and on line is especially useful to me., title_meta: Watercolor Artist, features: , description: , details: {"Date First Available": "September 18, 2006"}, categories: Magazine Subscriptions, Crafts & Hobbies, Painting'),
 ('B00007AWTU',
  'Draft Horse Journal',
  'title_review: The draft horse industry standard journal, text: The Draft Horse Journal has been highlighting the major shows and sales since 1964.  Articles cover harness, working horses, draft horse keeping, draft health issues, and important horses, breeds, and horsepeople.  Also important are the advertisements -- the DHJ serves as a directory of services and supplies for the draft horse industry.  Expect to keep your issues for future reference.  Usually around 220-240 pp., title_meta: Draft Horse Journal, features: , description: , details: {"Date First Available": "September 16, 2006"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Baseball'),
 ('B00026EEK4',
  'Mon Jardin Et Ma Maison    Print Magazine',
  'title_review: Five Stars, text: great!great! great pictures and articles<br />a great way of learning french, title_meta: Mon Jardin Et Ma Maison    Print Magazine, features: , description: MON JARDIN & MA MAISON achieves the balance between displaying beautiful landscaped gardens and the practical advice to achieve the same results in the readers own gardens. French language., details: {"Date First Available": "September 14, 2006", "Manufacturer": "Publications Grand Public"}, categories: Magazine Subscriptions, Home & Garden, Design & Decoration'),
 ('B002DHSFS2',
  'TV Guide Magazine Crosswords    Print Magazine',
  'title_review: Four Stars, text: awesome !, title_meta: TV Guide Magazine Crosswords    Print Magazine, features: , description: All kinds of crosswords for the TV fan, including Classics, Channel Surfers, Theme Puzzles, and a TV Word-Find, as well as two insightful columns and a quiz in every issue., details: {"Date First Available": "June 16, 2009", "Manufacturer": "Kappa Publishers Group"}, categories: '),
 ('B00005QJE2',
  'Nylon    Print Magazine',
  'title_review: inspiring, text: as a high school student aspiring to attend art school, nylon has provided me with countless sources of inspiration in their creative photography, layout, and decoration. i look forward to reading the magazine each month, and i honestly devour every last word and picture.<br /><br />nylon is a creative, whimsical and fantastic magazine. i highly reccomend it to anyone interested in a fashion magazine that goes beyond a "beach read.", title_meta: Nylon    Print Magazine, features: , description: A vibrant and proactive voice for today\'s hip, intelligent, young women seeking fresh perspectives on fashion, beauty and music., details: {"Date First Available": "September 14, 2006", "Manufacturer": "Nylon Media Inc."}, categories: Magazine Subscriptions, Business & Investing, International'),
 ('B00B8C8SWQ',
  'Current World Archaeology    Print Magazine',
  'title_review: Five Stars, text: The best general archaeology magazine I have read. I  highly recommend it!, title_meta: Current World Archaeology    Print Magazine, features: , description: Current World Archaeology, the magazine that studies archaeology round the world. CWA was founded in 2003 as a sister magazine to Current Archaeology which, since 1967, has been reporting on the latest discoveries in British archaeology. But CWA does not just look at the latest discoveries: it also travels the globe, looking at great monuments around the world, explaining how they came to be the sites - and sights - we see today., details: {"Date First Available": "January 30, 2013", "Manufacturer": "Current Publishing"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, History'),
 ('B002CT5156',
  'Cruising World',
  'title_review: Not what I expected, text: It was not what I expected and I would like to stop my subscription.&#34;cruising to me is not buying a boat, title_meta: Cruising World, features: , description: , details: {"Date First Available": "June 11, 2009"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Individual Sports'),
 ('B019R0URIS',
  'Simple Grace    Print Magazine',
  'title_review: Five Stars, text: Great inspirational reading<br />!, title_meta: Simple Grace    Print Magazine, features: , description: A Christian monthly magazine packed with inspirational stories, celebrity profiles and a media guide. Plus, a beautiful daily devotional with readings based on Jesus teachings. It s your daily dose of hope!, details: {"Date First Available": "December 23, 2015", "Manufacturer": "Bauer Publishing"}, categories: Magazine Subscriptions, Professional & Educational Journals, Professional & Trade, Humanities & Social Sciences, Religion & Spirituality'),
 ('B002PXVZDQ',
  'New Jersey Monthly',
  'title_review: :-(, text: Informative magazine however there are too many advertisements. I wish it had more information then it actually does. It was truly a disappointment., title_meta: New Jersey Monthly, features: , description: , details: {"Date First Available": "September 22, 2009"}, categories: Magazine Subscriptions, Travel, City & Regional, United States, Midwest'),
 ('B000066T0H',
  'Goldmine',
  'title_review: Goldmine is just what you are looking for, text: Great information on the music scene regardless of your inclinations....rock, jazz, alternative, etc., title_meta: Goldmine, features: , description: , details: {"Date First Available": "September 14, 2006"}, categories: Magazine Subscriptions, Arts, Music & Photography, Music'),
 ('B00HSUY3S0',
  'WATCH!    Print Magazine',
  'title_review: Five Stars, text: Interesting mix of articles., title_meta: WATCH!    Print Magazine, features: , description: , details: {"Date First Available": "January 11, 2014"}, categories: Magazine Subscriptions, Entertainment & Pop Culture, Celebrities & Gossip'),
 ('B00008KFZH',
  'Sports Afield',
  'title_review: Ruined, text: I wished a was able to find a copy of S.A. before I got a subscription.  The S.A. that I knew this is not.  The best features of this magazine have been stripped away.  I can\'t wait for my subscription to end, and I just received my first copy.  There are much better hunting magazines out there, wish I had the time to list them., title_meta: Sports Afield, features: , description: , details: {"Date First Available": "September 18, 2006"}, categories: Magazine Subscriptions, Sports, Recreation & Outdoors, Sports & Recreation, Baseball'),
 ('B000063XJL',
  'National Geographic Kids    Print Magazine',

In [ ]:
user_id_test = merged_df['user_id_encoded'].iloc[8]
recent_purchases = get_purchase_history(merged_df, user_id_test, k=3)
recent_purchases

,asin,title_meta,description,combined_text
8,B00007AXX1,Horse Illustrated,,"title_review: Great Magazine, text: This magaz..."

In [ ]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (2.5.1+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->bitsandbytes) (3.0.2)
Downloading bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 6.6 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.44.1

In [ ]:
import torch
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer, pipeline
from langchain.document_loaders import TextLoader
from langchain.vectorstores import Chroma
from langchain.prompts import PromptTemplate
from langchain.embeddings import HuggingFaceEmbeddings
from langchain_huggingface.llms import HuggingFacePipeline
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.schema import Document
from langchain.chains import RetrievalQA

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

In [ ]:

# since max number of tokens of sentence transformers is 512
# split the text into smaller chunks that fit within this limit before embedding
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)

# prepare documents
def prepare_documents(user_id_test, recs):
    documents = []
    for asin, title_meta, combined_text in recs:
        chunks = text_splitter.split_text(combined_text)
        for chunk in chunks:
            metadata = {
                "asin": asin,
                "title_meta": title_meta,
            }
            doc = Document(page_content=chunk, metadata=metadata)
            documents.append(doc)
    return documents

user_documents = prepare_documents(user_id_test, top_k_recs)
# os.environ["HUGGINGFACEHUB_API_TOKEN"] = "YOUR_HUGGINGFACE_TOKEN_HERE"
# YOUR_HUGGINGFACE_TOKEN_HERE
embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
chroma_client = Chroma.from_documents(documents=user_documents, embedding=embeddings, persist_directory="./content/chroma_db")

def get_search_result(user_query, chroma_client, k):
    res = chroma_client.similarity_search(query=user_query, k=k)
    return res

<ipython-input-25-0d67646e6ac0>:22: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
user_query= "beauty magazine that can provide beauty tips"
retrieved_docs = get_search_result(user_query, chroma_client, k=5)
retrieved_docs

[Document(metadata={'asin': 'B00005QJE2', 'title_meta': 'Nylon    Print Magazine'}, page_content='interested in a fashion magazine that goes beyond a "beach read.", title_meta: Nylon    Print Magazine, features: , description: A vibrant and proactive voice for today\'s hip, intelligent, young women seeking fresh perspectives on fashion, beauty and music., details: {"Date First Available": "September 14, 2006", "Manufacturer": "Nylon Media Inc."}, categories: Magazine Subscriptions, Business & Investing, International'),
 Document(metadata={'asin': 'B00005QJE2', 'title_meta': 'Nylon    Print Magazine'}, page_content='title_review: inspiring, text: as a high school student aspiring to attend art school, nylon has provided me with countless sources of inspiration in their creative photography, layout, and decoration. i look forward to reading the magazine each month, and i honestly devour every last word and picture.<br /><br />nylon is a creative, whimsical and fantastic magazine. i highly reccomend it to anyone interested in a fashion magazine that goes beyond a "beach read.", title_meta: Nylon    Print'),
 Document(metadata={'asin': 'B00C2E2C0I', 'title_meta': 'Essential Homme    Print Magazine'}, page_content='title_review: ess homm -- piece of junk, text: ess homm piece of junk, title_meta: Essential Homme    Print Magazine, features: , description: Essential Homme is the style source for affluent, successful, and fashion-forward men who are passionate about high quality, high-end luxury fashion., details: {"Date First Available": "March 28, 2013", "Manufacturer": "Essential Publications Us Llc"}, categories: Magazine Subscriptions, Crafts & Hobbies, Needlecrafts'),
 Document(metadata={'asin': 'B001D0FSVW', 'title_meta': 'Tathaastu    Print Magazine'}, page_content='title_review: Love it!, text: Love this magazine! The articles bring me back to what really is important in life. The photography and artwork are absolutely beautiful; full of rich, vibrant colors and backgrounds., title_meta: Tathaastu    Print Magazine, features: , description: Tathaastu magazine is written to help you have a happier and healthier life. Nourish your mind, body and soul by helping you follow a more spiritual way of life and lead it with peace, harmony and dignity., details:'),
 Document(metadata={'asin': 'B002PXVZDQ', 'title_meta': 'New Jersey Monthly'}, page_content='title_review: :-(, text: Informative magazine however there are too many advertisements. I wish it had more information then it actually does. It was truly a disappointment., title_meta: New Jersey Monthly, features: , description: , details: {"Date First Available": "September 22, 2009"}, categories: Magazine Subscriptions, Travel, City & Regional, United States, Midwest')]

In [ ]:
# !pip install accelerate

In [ ]:
model_id = "nvidia/Mistral-NeMo-Minitron-8B-Base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
# dtype = torch.bfloat16
model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=100,
)

# HuggingFace pipeline integration
hf = HuggingFacePipeline(pipeline=pipe)
llm = hf

tokenizer_config.json:   0%|          | 0.00/177k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.26M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
`low_cpu_mem_usage` was None, now default to True since model is quantized.

model.safetensors.index.json:   0%|          | 0.00/29.9k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
prompt_template = """
Imagine you are a recommender. Given the user's recent purchase history, liked items, disliked items, and query:
User Query: {question}
Recent Purchases: {purchase_history}
Liked Items: {liked_items}
Disliked Items: {disliked_items}

Please rank the following items based on relevance and provide a brief explanation for each:
{context}
Reranked Recommendations:
"""

def personal_rerank(user_query, recent_purchase, retrieved_docs, like_items, dislike_items, llm, prompt_template):
    purchase_hist = "\n".join([f"{i+1}. {row['title_meta']}: {row['description']}" for i, (_, row) in enumerate(recent_purchases.iterrows())])
    context = "\n".join(f"{doc.metadata['title_meta']}: {doc.page_content}" for doc in retrieved_docs)
    prompt = prompt_template.format(
        question=user_query,
        purchase_history=purchase_hist,
        liked_items="\n".join(like_items),
        disliked_items="\n".join(dislike_items),
        context=context
    )
    return llm(prompt)

In [ ]:
user_query = "beauty magazine that can provide beauty tips"
retrieved_docs = get_search_result(user_query, chroma_client, k=5)